/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/rutube/client";
import fetch from "@/lib/rutube/client";

import type {
  GetUserProfile404,
  GetUserProfile500,
  GetUserProfilePathParams,
  GetUserProfileQueryResponse,
} from "../models/get-user-profile.ts";
import { getUserProfileQueryResponseSchema } from "../zod/get-user-profile-schema.ts";

function getGetUserProfileUrl({
  author_id,
}: {
  author_id: GetUserProfilePathParams["author_id"];
}) {
  const res = { method: "GET", url: `/api/profile/user/${author_id}` as const };
  return res;
}

/**
 * @description Информация о канале по числовому идентификатору автора.
 * @summary Профиль пользователя / канала
 * {@link /api/profile/user/:author_id}
 */
export async function getUserProfile(
  { author_id }: { author_id: GetUserProfilePathParams["author_id"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserProfileQueryResponse,
    ResponseErrorConfig<GetUserProfile404 | GetUserProfile500>,
    unknown
  >({
    method: "GET",
    url: getGetUserProfileUrl({ author_id }).url.toString(),
    ...requestConfig,
  });
  return getUserProfileQueryResponseSchema.parse(res.data);
}
