/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetInstagramDownloadQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Download URL generated
 */
export type GetInstagramDownload200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    title?: string;
    /**
     * @type string | undefined
     */
    duration?: string;
    /**
     * @type string | undefined
     */
    downloadUrl?: string;
    /**
     * @type number | undefined
     */
    fileSize?: number;
    /**
     * @type string | undefined
     */
    fileSizeMB?: string;
    /**
     * @type string | undefined
     */
    format?: string;
    /**
     * @type string | undefined
     */
    quality?: string;
    /**
     * @type string | undefined
     */
    expiresIn?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetInstagramDownload400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetInstagramDownload403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetInstagramDownload404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetInstagramDownload500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetInstagramDownloadQueryResponse = GetInstagramDownload200;

export type GetInstagramDownloadQuery = {
  Response: GetInstagramDownload200;
  QueryParams: GetInstagramDownloadQueryParams;
  Errors:
    | GetInstagramDownload400
    | GetInstagramDownload403
    | GetInstagramDownload404
    | GetInstagramDownload500;
};
