/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetInstagramReelsSearchQueryParams = {
  /**
   * @description Search query
   * @type string | undefined
   */
  query?: string;
  /**
   * @description Maximum number of results
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Reels search results returned
 */
export type GetInstagramReelsSearch200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    query?: string;
    /**
     * @type array | undefined
     */
    items?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      url?: string;
      /**
       * @type string | undefined
       */
      caption?: string;
      /**
       * @type integer | undefined
       */
      likes?: number;
      /**
       * @type integer | undefined
       */
      comments?: number;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type object | undefined
       */
      author?: {
        /**
         * @type string | undefined
         */
        id?: string;
        /**
         * @type string | undefined
         */
        username?: string;
        /**
         * @type string | undefined
         */
        fullName?: string;
        /**
         * @type boolean | undefined
         */
        isVerified?: boolean;
        /**
         * @type string | undefined
         */
        profilePicUrl?: string;
      };
    }[];
    /**
     * @type integer | undefined
     */
    count?: number;
    /**
     * @type boolean | undefined
     */
    hasMore?: boolean;
  };
};

/**
 * @description Missing required parameter
 */
export type GetInstagramReelsSearch400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetInstagramReelsSearch403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetInstagramReelsSearch404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetInstagramReelsSearch500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetInstagramReelsSearchQueryResponse = GetInstagramReelsSearch200;

export type GetInstagramReelsSearchQuery = {
  Response: GetInstagramReelsSearch200;
  QueryParams: GetInstagramReelsSearchQueryParams;
  Errors:
    | GetInstagramReelsSearch400
    | GetInstagramReelsSearch403
    | GetInstagramReelsSearch404
    | GetInstagramReelsSearch500;
};
