/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetYoutubeStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Video stats retrieved successfully
 */
export type GetYoutubeStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    videoId?: string;
    /**
     * @type string | undefined
     */
    title?: string;
    /**
     * @type string | undefined
     */
    description?: string;
    /**
     * @type string | undefined
     */
    channelName?: string;
    /**
     * @type string | undefined
     */
    channelLink?: string;
    /**
     * @type string | undefined
     */
    channelHandle?: string;
    /**
     * @type integer | undefined
     */
    views?: number;
    /**
     * @type integer | undefined
     */
    likes?: number;
    /**
     * @type integer | undefined
     */
    comments?: number;
    /**
     * @type string | undefined
     */
    duration?: string;
    /**
     * @type string | undefined
     */
    publishedAt?: string;
    /**
     * @type string | undefined
     */
    thumbnailUrl?: string;
    /**
     * @type string | undefined
     */
    contentType?: string;
    /**
     * @type boolean | undefined
     */
    isShortForm?: boolean;
  };
};

/**
 * @description Missing required parameter
 */
export type GetYoutubeStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetYoutubeStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetYoutubeStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetYoutubeStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetYoutubeStatsQueryResponse = GetYoutubeStats200;

export type GetYoutubeStatsQuery = {
  Response: GetYoutubeStats200;
  QueryParams: GetYoutubeStatsQueryParams;
  Errors:
    | GetYoutubeStats400
    | GetYoutubeStats403
    | GetYoutubeStats404
    | GetYoutubeStats500;
};
