/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetInstagramChannelStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Profile stats retrieved successfully
 */
export type GetInstagramChannelStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type string | undefined
     */
    username?: string;
    /**
     * @type string | undefined
     */
    fullName?: string;
    /**
     * @type boolean | undefined
     */
    verified?: boolean;
    /**
     * @type integer | undefined
     */
    followers?: number;
    /**
     * @type integer | undefined
     */
    following?: number;
    /**
     * @type integer | undefined
     */
    totalPosts?: number;
    /**
     * @type string | undefined
     */
    bio?: string;
    /**
     * @type string | undefined
     */
    avatar?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetInstagramChannelStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetInstagramChannelStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetInstagramChannelStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetInstagramChannelStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetInstagramChannelStatsQueryResponse = GetInstagramChannelStats200;

export type GetInstagramChannelStatsQuery = {
  Response: GetInstagramChannelStats200;
  QueryParams: GetInstagramChannelStatsQueryParams;
  Errors:
    | GetInstagramChannelStats400
    | GetInstagramChannelStats403
    | GetInstagramChannelStats404
    | GetInstagramChannelStats500;
};
