/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetTiktokChannelVideosQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel videos retrieved successfully
 */
export type GetTiktokChannelVideos200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type string | undefined
     */
    channelName?: string;
    /**
     * @type array | undefined
     */
    results?: {
      /**
       * @type string | undefined
       */
      videoId?: string;
      /**
       * @type string | undefined
       */
      description?: string;
      /**
       * @type string | undefined
       */
      url?: string;
      /**
       * @type string | undefined
       */
      thumbnail?: string;
      /**
       * @type number | undefined
       */
      duration?: number;
      /**
       * @type string | undefined
       */
      createTime?: string;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type integer | undefined
       */
      likes?: number;
      /**
       * @type integer | undefined
       */
      comments?: number;
      /**
       * @type integer | undefined
       */
      shares?: number;
      /**
       * @type integer | undefined
       */
      collects?: number;
    }[];
    /**
     * @type boolean | undefined
     */
    hasMore?: boolean;
    /**
     * @type string | undefined
     */
    cursor?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetTiktokChannelVideos400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetTiktokChannelVideos403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetTiktokChannelVideos404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetTiktokChannelVideos500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTiktokChannelVideosQueryResponse = GetTiktokChannelVideos200;

export type GetTiktokChannelVideosQuery = {
  Response: GetTiktokChannelVideos200;
  QueryParams: GetTiktokChannelVideosQueryParams;
  Errors:
    | GetTiktokChannelVideos400
    | GetTiktokChannelVideos403
    | GetTiktokChannelVideos404
    | GetTiktokChannelVideos500;
};
