/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetVideoSummarizeQueryParams = {
  /**
   * @description Direct URL to the video file
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Summary generated successfully
 */
export type GetVideoSummarize200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    summary?: string;
    /**
     * @type array | undefined
     */
    mainTopics?: string[];
    /**
     * @type array | undefined
     */
    keyPoints?: string[];
    /**
     * @type string | undefined
     */
    tone?: string;
    /**
     * @type string | undefined
     */
    targetAudience?: string;
    /**
     * @type array | undefined
     */
    quotes?: string[];
  };
};

/**
 * @description Missing required parameter
 */
export type GetVideoSummarize400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetVideoSummarize403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetVideoSummarize404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetVideoSummarize500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetVideoSummarizeQueryResponse = GetVideoSummarize200;

export type GetVideoSummarizeQuery = {
  Response: GetVideoSummarize200;
  QueryParams: GetVideoSummarizeQueryParams;
  Errors:
    | GetVideoSummarize400
    | GetVideoSummarize403
    | GetVideoSummarize404
    | GetVideoSummarize500;
};
