/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetYoutubeDownloadQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Download URL generated
 */
export type GetYoutubeDownload200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    title?: string;
    /**
     * @type string | undefined
     */
    duration?: string;
    /**
     * @type string | undefined
     */
    downloadUrl?: string;
    /**
     * @type number | undefined
     */
    fileSize?: number;
    /**
     * @type string | undefined
     */
    fileSizeMB?: string;
    /**
     * @type string | undefined
     */
    format?: string;
    /**
     * @type string | undefined
     */
    quality?: string;
    /**
     * @type string | undefined
     */
    expiresIn?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetYoutubeDownload400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetYoutubeDownload403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetYoutubeDownload404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetYoutubeDownload500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetYoutubeDownloadQueryResponse = GetYoutubeDownload200;

export type GetYoutubeDownloadQuery = {
  Response: GetYoutubeDownload200;
  QueryParams: GetYoutubeDownloadQueryParams;
  Errors:
    | GetYoutubeDownload400
    | GetYoutubeDownload403
    | GetYoutubeDownload404
    | GetYoutubeDownload500;
};
