/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetInstagramChannelReelsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel reels retrieved successfully
 */
export type GetInstagramChannelReels200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type string | undefined
     */
    username?: string;
    /**
     * @type array | undefined
     */
    items?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      shortcode?: string;
      /**
       * @type string | undefined
       */
      url?: string;
      /**
       * @type string | undefined
       */
      caption?: string;
      /**
       * @type integer | undefined
       */
      likes?: number;
      /**
       * @type integer | undefined
       */
      comments?: number;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type number | undefined
       */
      duration?: number;
      /**
       * @type string | undefined
       */
      thumbnailUrl?: string;
      /**
       * @type object | undefined
       */
      author?: {
        /**
         * @type string | undefined
         */
        id?: string;
        /**
         * @type string | undefined
         */
        username?: string;
        /**
         * @type string | undefined
         */
        fullName?: string;
        /**
         * @type boolean | undefined
         */
        isVerified?: boolean;
        /**
         * @type string | undefined
         */
        profilePicUrl?: string;
      };
    }[];
    /**
     * @type integer | undefined
     */
    count?: number;
    /**
     * @type boolean | undefined
     */
    hasMore?: boolean;
    /**
     * @type string | undefined
     */
    cursor?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetInstagramChannelReels400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetInstagramChannelReels403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetInstagramChannelReels404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetInstagramChannelReels500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetInstagramChannelReelsQueryResponse = GetInstagramChannelReels200;

export type GetInstagramChannelReelsQuery = {
  Response: GetInstagramChannelReels200;
  QueryParams: GetInstagramChannelReelsQueryParams;
  Errors:
    | GetInstagramChannelReels400
    | GetInstagramChannelReels403
    | GetInstagramChannelReels404
    | GetInstagramChannelReels500;
};
