/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetYoutubeVideosQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel videos retrieved successfully
 */
export type GetYoutubeVideos200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @description \'playlist\' or \'channel\'
     * @type string | undefined
     */
    type?: string;
    /**
     * @type array | undefined
     */
    results?: {
      /**
       * @type string | undefined
       */
      videoId?: string;
      /**
       * @type string | undefined
       */
      title?: string;
      /**
       * @type string | undefined
       */
      thumbnail?: string;
      /**
       * @type string | undefined
       */
      channelName?: string;
      /**
       * @type string | undefined
       */
      duration?: string;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type string | undefined
       */
      viewsFormatted?: string;
      /**
       * @type string | undefined
       */
      publishedTime?: string;
      /**
       * @type string | undefined
       */
      url?: string;
    }[];
  };
};

/**
 * @description Missing required parameter
 */
export type GetYoutubeVideos400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetYoutubeVideos403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetYoutubeVideos404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetYoutubeVideos500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetYoutubeVideosQueryResponse = GetYoutubeVideos200;

export type GetYoutubeVideosQuery = {
  Response: GetYoutubeVideos200;
  QueryParams: GetYoutubeVideosQueryParams;
  Errors:
    | GetYoutubeVideos400
    | GetYoutubeVideos403
    | GetYoutubeVideos404
    | GetYoutubeVideos500;
};
