/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetInstagramStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Post stats retrieved successfully
 */
export type GetInstagramStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    postUrl?: string;
    /**
     * @type string | undefined
     */
    id?: string;
    /**
     * @type string | undefined
     */
    shortcode?: string;
    /**
     * @type string | undefined
     */
    title?: string;
    /**
     * @type string | undefined
     */
    description?: string;
    /**
     * @type integer | undefined
     */
    views?: number;
    /**
     * @type integer | undefined
     */
    likes?: number;
    /**
     * @type integer | undefined
     */
    comments?: number;
    /**
     * @type string | undefined
     */
    publishedAt?: string;
    /**
     * @type string | undefined
     */
    author?: string;
    /**
     * @type string | undefined
     */
    authorLink?: string;
    /**
     * @type string | undefined
     */
    duration?: string;
    /**
     * @type string | undefined
     */
    thumbnail?: string;
    /**
     * @type boolean | undefined
     */
    isVideo?: boolean;
    /**
     * @type string | undefined
     */
    contentType?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetInstagramStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetInstagramStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetInstagramStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetInstagramStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetInstagramStatsQueryResponse = GetInstagramStats200;

export type GetInstagramStatsQuery = {
  Response: GetInstagramStats200;
  QueryParams: GetInstagramStatsQueryParams;
  Errors:
    | GetInstagramStats400
    | GetInstagramStats403
    | GetInstagramStats404
    | GetInstagramStats500;
};
