/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetInstagramCommentsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Comments retrieved successfully
 */
export type GetInstagramComments200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    postUrl?: string;
    /**
     * @type array | undefined
     */
    comments?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      text?: string;
      /**
       * @type integer | undefined
       */
      likeCount?: number;
      /**
       * @type integer | undefined
       */
      replyCount?: number;
      /**
       * @type object | undefined
       */
      user?: {
        /**
         * @type string | undefined
         */
        id?: string;
        /**
         * @type string | undefined
         */
        username?: string;
        /**
         * @type string | undefined
         */
        fullName?: string;
        /**
         * @type boolean | undefined
         */
        isVerified?: boolean;
        /**
         * @type string | undefined
         */
        profilePicUrl?: string;
      };
    }[];
    /**
     * @type integer | undefined
     */
    commentCount?: number;
    /**
     * @type boolean | undefined
     */
    hasMore?: boolean;
    /**
     * @type string | undefined
     */
    cursor?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetInstagramComments400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetInstagramComments403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetInstagramComments404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetInstagramComments500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetInstagramCommentsQueryResponse = GetInstagramComments200;

export type GetInstagramCommentsQuery = {
  Response: GetInstagramComments200;
  QueryParams: GetInstagramCommentsQueryParams;
  Errors:
    | GetInstagramComments400
    | GetInstagramComments403
    | GetInstagramComments404
    | GetInstagramComments500;
};
