/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetYoutubeSearchQueryParams = {
  /**
   * @description Search query
   * @type string | undefined
   */
  query?: string;
  /**
   * @description Maximum number of results
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Search results returned
 */
export type GetYoutubeSearch200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    query?: string;
    /**
     * @type array | undefined
     */
    results?: {
      /**
       * @type string | undefined
       */
      videoId?: string;
      /**
       * @type string | undefined
       */
      title?: string;
      /**
       * @type string | undefined
       */
      thumbnail?: string;
      /**
       * @type string | undefined
       */
      channelName?: string;
      /**
       * @type string | undefined
       */
      channelId?: string;
      /**
       * @type string | undefined
       */
      channelUrl?: string;
      /**
       * @type string | undefined
       */
      publishedTime?: string;
      /**
       * @type string | undefined
       */
      duration?: string;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type string | undefined
       */
      viewsFormatted?: string;
      /**
       * @type string | undefined
       */
      description?: string;
      /**
       * @type string | undefined
       */
      url?: string;
      /**
       * @type boolean | undefined
       */
      verified?: boolean;
    }[];
  };
};

/**
 * @description Missing required parameter
 */
export type GetYoutubeSearch400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetYoutubeSearch403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetYoutubeSearch404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetYoutubeSearch500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetYoutubeSearchQueryResponse = GetYoutubeSearch200;

export type GetYoutubeSearchQuery = {
  Response: GetYoutubeSearch200;
  QueryParams: GetYoutubeSearchQueryParams;
  Errors:
    | GetYoutubeSearch400
    | GetYoutubeSearch403
    | GetYoutubeSearch404
    | GetYoutubeSearch500;
};
