/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetTiktokStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Video stats retrieved successfully
 */
export type GetTiktokStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    videoId?: string;
    /**
     * @type string | undefined
     */
    title?: string;
    /**
     * @type string | undefined
     */
    channelName?: string;
    /**
     * @type string | undefined
     */
    channelLink?: string;
    /**
     * @type integer | undefined
     */
    likes?: number;
    /**
     * @type integer | undefined
     */
    comments?: number;
    /**
     * @type integer | undefined
     */
    collects?: number;
    /**
     * @type integer | undefined
     */
    shares?: number;
    /**
     * @type integer | undefined
     */
    views?: number;
    /**
     * @type string | undefined
     */
    description?: string;
    /**
     * @type string | undefined
     */
    duration?: string;
    /**
     * @type string | undefined
     */
    thumbnailUrl?: string;
    /**
     * @type string | undefined
     */
    publishedAt?: string;
    /**
     * @type string | undefined
     */
    contentType?: string;
    /**
     * @type boolean | undefined
     */
    isShortForm?: boolean;
  };
};

/**
 * @description Missing required parameter
 */
export type GetTiktokStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetTiktokStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetTiktokStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetTiktokStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTiktokStatsQueryResponse = GetTiktokStats200;

export type GetTiktokStatsQuery = {
  Response: GetTiktokStats200;
  QueryParams: GetTiktokStatsQueryParams;
  Errors:
    | GetTiktokStats400
    | GetTiktokStats403
    | GetTiktokStats404
    | GetTiktokStats500;
};
