/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetTiktokChannelStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel stats retrieved successfully
 */
export type GetTiktokChannelStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type string | undefined
     */
    username?: string;
    /**
     * @type string | undefined
     */
    nickname?: string;
    /**
     * @type string | undefined
     */
    signature?: string;
    /**
     * @type boolean | undefined
     */
    verified?: boolean;
    /**
     * @type string | undefined
     */
    avatar?: string;
    /**
     * @type integer | undefined
     */
    followers?: number;
    /**
     * @type integer | undefined
     */
    following?: number;
    /**
     * @type integer | undefined
     */
    totalLikes?: number;
    /**
     * @type integer | undefined
     */
    totalVideos?: number;
    /**
     * @type string | undefined
     */
    bioLink?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type GetTiktokChannelStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type GetTiktokChannelStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type GetTiktokChannelStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type GetTiktokChannelStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTiktokChannelStatsQueryResponse = GetTiktokChannelStats200;

export type GetTiktokChannelStatsQuery = {
  Response: GetTiktokChannelStats200;
  QueryParams: GetTiktokChannelStatsQueryParams;
  Errors:
    | GetTiktokChannelStats400
    | GetTiktokChannelStats403
    | GetTiktokChannelStats404
    | GetTiktokChannelStats500;
};
