/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Batch results returned
 */
export type PostYoutubeTranscriptBulk200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type array | undefined
     */
    results?: object[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostYoutubeTranscriptBulk400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostYoutubeTranscriptBulk403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostYoutubeTranscriptBulk404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostYoutubeTranscriptBulk500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostYoutubeTranscriptBulkMutationRequest = {
  /**
   * @description List of URLs to process
   * @type array | undefined
   */
  urls?: string[];
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

export type PostYoutubeTranscriptBulkMutationResponse =
  PostYoutubeTranscriptBulk200;

export type PostYoutubeTranscriptBulkMutation = {
  Response: PostYoutubeTranscriptBulk200;
  Request: PostYoutubeTranscriptBulkMutationRequest;
  Errors:
    | PostYoutubeTranscriptBulk400
    | PostYoutubeTranscriptBulk403
    | PostYoutubeTranscriptBulk404
    | PostYoutubeTranscriptBulk500;
};
