/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostTiktokDownloadQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Download URL generated
 */
export type PostTiktokDownload200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    title?: string;
    /**
     * @type string | undefined
     */
    duration?: string;
    /**
     * @type string | undefined
     */
    downloadUrl?: string;
    /**
     * @type number | undefined
     */
    fileSize?: number;
    /**
     * @type string | undefined
     */
    fileSizeMB?: string;
    /**
     * @type string | undefined
     */
    format?: string;
    /**
     * @type string | undefined
     */
    quality?: string;
    /**
     * @type string | undefined
     */
    expiresIn?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type PostTiktokDownload400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostTiktokDownload403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostTiktokDownload404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostTiktokDownload500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostTiktokDownloadMutationResponse = PostTiktokDownload200;

export type PostTiktokDownloadMutation = {
  Response: PostTiktokDownload200;
  QueryParams: PostTiktokDownloadQueryParams;
  Errors:
    | PostTiktokDownload400
    | PostTiktokDownload403
    | PostTiktokDownload404
    | PostTiktokDownload500;
};
