/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostYoutubeChannelStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel stats retrieved successfully
 */
export type PostYoutubeChannelStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type string | undefined
     */
    username?: string;
    /**
     * @type string | undefined
     */
    nickname?: string;
    /**
     * @type string | undefined
     */
    bio?: string;
    /**
     * @type boolean | undefined
     */
    verified?: boolean;
    /**
     * @type string | undefined
     */
    avatar?: string;
    /**
     * @type integer | undefined
     */
    subscribers?: number;
    /**
     * @type integer | undefined
     */
    totalVideos?: number;
    /**
     * @type string | undefined
     */
    bioLink?: string;
    /**
     * @type string | undefined
     */
    banner?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type PostYoutubeChannelStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostYoutubeChannelStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostYoutubeChannelStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostYoutubeChannelStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostYoutubeChannelStatsMutationResponse =
  PostYoutubeChannelStats200;

export type PostYoutubeChannelStatsMutation = {
  Response: PostYoutubeChannelStats200;
  QueryParams: PostYoutubeChannelStatsQueryParams;
  Errors:
    | PostYoutubeChannelStats400
    | PostYoutubeChannelStats403
    | PostYoutubeChannelStats404
    | PostYoutubeChannelStats500;
};
