/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostYoutubeCommentsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Comments retrieved successfully
 */
export type PostYoutubeComments200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type array | undefined
     */
    comments?: {
      /**
       * @type string | undefined
       */
      author?: string;
      /**
       * @type string | undefined
       */
      text?: string;
      /**
       * @type integer | undefined
       */
      likes?: number;
      /**
       * @type string | undefined
       */
      date?: string;
      /**
       * @type string | undefined
       */
      avatar?: string;
      /**
       * @type integer | undefined
       */
      replyCount?: number;
      /**
       * @type integer | undefined
       */
      position?: number;
    }[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostYoutubeComments400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostYoutubeComments403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostYoutubeComments404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostYoutubeComments500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostYoutubeCommentsMutationResponse = PostYoutubeComments200;

export type PostYoutubeCommentsMutation = {
  Response: PostYoutubeComments200;
  QueryParams: PostYoutubeCommentsQueryParams;
  Errors:
    | PostYoutubeComments400
    | PostYoutubeComments403
    | PostYoutubeComments404
    | PostYoutubeComments500;
};
