/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostTiktokChannelVideoMetricsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel video metrics retrieved
 */
export type PostTiktokChannelVideoMetrics200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type number | undefined
     */
    median?: number;
    /**
     * @type number | undefined
     */
    average?: number;
    /**
     * @type number | undefined
     */
    min?: number;
    /**
     * @type number | undefined
     */
    max?: number;
    /**
     * @type number | undefined
     */
    total?: number;
    /**
     * @type array | undefined
     */
    viewCounts?: number[];
    /**
     * @type integer | undefined
     */
    videosAnalyzed?: number;
  };
};

/**
 * @description Missing required parameter
 */
export type PostTiktokChannelVideoMetrics400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostTiktokChannelVideoMetrics403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostTiktokChannelVideoMetrics404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostTiktokChannelVideoMetrics500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostTiktokChannelVideoMetricsMutationResponse =
  PostTiktokChannelVideoMetrics200;

export type PostTiktokChannelVideoMetricsMutation = {
  Response: PostTiktokChannelVideoMetrics200;
  QueryParams: PostTiktokChannelVideoMetricsQueryParams;
  Errors:
    | PostTiktokChannelVideoMetrics400
    | PostTiktokChannelVideoMetrics403
    | PostTiktokChannelVideoMetrics404
    | PostTiktokChannelVideoMetrics500;
};
