/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Batch results returned
 */
export type PostTiktokStatsBulk200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type array | undefined
     */
    results?: object[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostTiktokStatsBulk400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostTiktokStatsBulk403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostTiktokStatsBulk404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostTiktokStatsBulk500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostTiktokStatsBulkMutationRequest = {
  /**
   * @description List of URLs to process
   * @type array | undefined
   */
  urls?: string[];
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

export type PostTiktokStatsBulkMutationResponse = PostTiktokStatsBulk200;

export type PostTiktokStatsBulkMutation = {
  Response: PostTiktokStatsBulk200;
  Request: PostTiktokStatsBulkMutationRequest;
  Errors:
    | PostTiktokStatsBulk400
    | PostTiktokStatsBulk403
    | PostTiktokStatsBulk404
    | PostTiktokStatsBulk500;
};
