/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostYoutubeSearchQueryParams = {
  /**
   * @description Search query
   * @type string | undefined
   */
  query?: string;
  /**
   * @description Maximum number of results
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Search results returned
 */
export type PostYoutubeSearch200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    query?: string;
    /**
     * @type array | undefined
     */
    results?: {
      /**
       * @type string | undefined
       */
      videoId?: string;
      /**
       * @type string | undefined
       */
      title?: string;
      /**
       * @type string | undefined
       */
      thumbnail?: string;
      /**
       * @type string | undefined
       */
      channelName?: string;
      /**
       * @type string | undefined
       */
      channelId?: string;
      /**
       * @type string | undefined
       */
      channelUrl?: string;
      /**
       * @type string | undefined
       */
      publishedTime?: string;
      /**
       * @type string | undefined
       */
      duration?: string;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type string | undefined
       */
      viewsFormatted?: string;
      /**
       * @type string | undefined
       */
      description?: string;
      /**
       * @type string | undefined
       */
      url?: string;
      /**
       * @type boolean | undefined
       */
      verified?: boolean;
    }[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostYoutubeSearch400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostYoutubeSearch403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostYoutubeSearch404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostYoutubeSearch500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostYoutubeSearchMutationResponse = PostYoutubeSearch200;

export type PostYoutubeSearchMutation = {
  Response: PostYoutubeSearch200;
  QueryParams: PostYoutubeSearchQueryParams;
  Errors:
    | PostYoutubeSearch400
    | PostYoutubeSearch403
    | PostYoutubeSearch404
    | PostYoutubeSearch500;
};
