/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Batch results returned
 */
export type PostInstagramStatsBulk200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type array | undefined
     */
    results?: object[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostInstagramStatsBulk400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostInstagramStatsBulk403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostInstagramStatsBulk404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostInstagramStatsBulk500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostInstagramStatsBulkMutationRequest = {
  /**
   * @description List of URLs to process
   * @type array | undefined
   */
  urls?: string[];
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

export type PostInstagramStatsBulkMutationResponse = PostInstagramStatsBulk200;

export type PostInstagramStatsBulkMutation = {
  Response: PostInstagramStatsBulk200;
  Request: PostInstagramStatsBulkMutationRequest;
  Errors:
    | PostInstagramStatsBulk400
    | PostInstagramStatsBulk403
    | PostInstagramStatsBulk404
    | PostInstagramStatsBulk500;
};
