/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Batch results returned
 */
export type PostYoutubeCommentsBulk200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type array | undefined
     */
    results?: object[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostYoutubeCommentsBulk400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostYoutubeCommentsBulk403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostYoutubeCommentsBulk404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostYoutubeCommentsBulk500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostYoutubeCommentsBulkMutationRequest = {
  /**
   * @description List of URLs to process
   * @type array | undefined
   */
  urls?: string[];
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

export type PostYoutubeCommentsBulkMutationResponse =
  PostYoutubeCommentsBulk200;

export type PostYoutubeCommentsBulkMutation = {
  Response: PostYoutubeCommentsBulk200;
  Request: PostYoutubeCommentsBulkMutationRequest;
  Errors:
    | PostYoutubeCommentsBulk400
    | PostYoutubeCommentsBulk403
    | PostYoutubeCommentsBulk404
    | PostYoutubeCommentsBulk500;
};
