/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostTiktokChannelStatsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel stats retrieved successfully
 */
export type PostTiktokChannelStats200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    profileUrl?: string;
    /**
     * @type string | undefined
     */
    username?: string;
    /**
     * @type string | undefined
     */
    nickname?: string;
    /**
     * @type string | undefined
     */
    signature?: string;
    /**
     * @type boolean | undefined
     */
    verified?: boolean;
    /**
     * @type string | undefined
     */
    avatar?: string;
    /**
     * @type integer | undefined
     */
    followers?: number;
    /**
     * @type integer | undefined
     */
    following?: number;
    /**
     * @type integer | undefined
     */
    totalLikes?: number;
    /**
     * @type integer | undefined
     */
    totalVideos?: number;
    /**
     * @type string | undefined
     */
    bioLink?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type PostTiktokChannelStats400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostTiktokChannelStats403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostTiktokChannelStats404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostTiktokChannelStats500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostTiktokChannelStatsMutationResponse = PostTiktokChannelStats200;

export type PostTiktokChannelStatsMutation = {
  Response: PostTiktokChannelStats200;
  QueryParams: PostTiktokChannelStatsQueryParams;
  Errors:
    | PostTiktokChannelStats400
    | PostTiktokChannelStats403
    | PostTiktokChannelStats404
    | PostTiktokChannelStats500;
};
