/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostTiktokSummarizeQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Summary generated successfully
 */
export type PostTiktokSummarize200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @type string | undefined
     */
    summary?: string;
    /**
     * @type array | undefined
     */
    mainTopics?: string[];
    /**
     * @type array | undefined
     */
    keyPoints?: string[];
    /**
     * @type string | undefined
     */
    tone?: string;
    /**
     * @type string | undefined
     */
    targetAudience?: string;
    /**
     * @type array | undefined
     */
    quotes?: string[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostTiktokSummarize400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostTiktokSummarize403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostTiktokSummarize404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostTiktokSummarize500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostTiktokSummarizeMutationResponse = PostTiktokSummarize200;

export type PostTiktokSummarizeMutation = {
  Response: PostTiktokSummarize200;
  QueryParams: PostTiktokSummarizeQueryParams;
  Errors:
    | PostTiktokSummarize400
    | PostTiktokSummarize403
    | PostTiktokSummarize404
    | PostTiktokSummarize500;
};
