/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostYoutubeVideosQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Channel videos retrieved successfully
 */
export type PostYoutubeVideos200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    url?: string;
    /**
     * @description \'playlist\' or \'channel\'
     * @type string | undefined
     */
    type?: string;
    /**
     * @type array | undefined
     */
    results?: {
      /**
       * @type string | undefined
       */
      videoId?: string;
      /**
       * @type string | undefined
       */
      title?: string;
      /**
       * @type string | undefined
       */
      thumbnail?: string;
      /**
       * @type string | undefined
       */
      channelName?: string;
      /**
       * @type string | undefined
       */
      duration?: string;
      /**
       * @type integer | undefined
       */
      views?: number;
      /**
       * @type string | undefined
       */
      viewsFormatted?: string;
      /**
       * @type string | undefined
       */
      publishedTime?: string;
      /**
       * @type string | undefined
       */
      url?: string;
    }[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostYoutubeVideos400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostYoutubeVideos403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostYoutubeVideos404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostYoutubeVideos500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostYoutubeVideosMutationResponse = PostYoutubeVideos200;

export type PostYoutubeVideosMutation = {
  Response: PostYoutubeVideos200;
  QueryParams: PostYoutubeVideosQueryParams;
  Errors:
    | PostYoutubeVideos400
    | PostYoutubeVideos403
    | PostYoutubeVideos404
    | PostYoutubeVideos500;
};
