/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostTiktokCommentsQueryParams = {
  /**
   * @description Full URL of the resource
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Maximum number of results to return
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

/**
 * @description Comments retrieved successfully
 */
export type PostTiktokComments200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type string | undefined
     */
    videoId?: string;
    /**
     * @type array | undefined
     */
    comments?: {
      /**
       * @type string | undefined
       */
      id?: string;
      /**
       * @type string | undefined
       */
      author?: string;
      /**
       * @type string | undefined
       */
      username?: string;
      /**
       * @type string | undefined
       */
      text?: string;
      /**
       * @type integer | undefined
       */
      likes?: number;
      /**
       * @type string | undefined
       */
      avatar?: string;
      /**
       * @type string | undefined
       */
      createTime?: string;
      /**
       * @type integer | undefined
       */
      replyCount?: number;
    }[];
    /**
     * @type integer | undefined
     */
    commentCount?: number;
    /**
     * @type boolean | undefined
     */
    hasMore?: boolean;
    /**
     * @type string | undefined
     */
    cursor?: string;
  };
};

/**
 * @description Missing required parameter
 */
export type PostTiktokComments400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostTiktokComments403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostTiktokComments404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostTiktokComments500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostTiktokCommentsMutationResponse = PostTiktokComments200;

export type PostTiktokCommentsMutation = {
  Response: PostTiktokComments200;
  QueryParams: PostTiktokCommentsQueryParams;
  Errors:
    | PostTiktokComments400
    | PostTiktokComments403
    | PostTiktokComments404
    | PostTiktokComments500;
};
