/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Batch results returned
 */
export type PostInstagramChannelStatsBulk200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type array | undefined
     */
    results?: object[];
  };
};

/**
 * @description Missing required parameter
 */
export type PostInstagramChannelStatsBulk400 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Credit limit exceeded
 */
export type PostInstagramChannelStatsBulk403 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Content not found or unavailable
 */
export type PostInstagramChannelStatsBulk404 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal server error
 */
export type PostInstagramChannelStatsBulk500 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostInstagramChannelStatsBulkMutationRequest = {
  /**
   * @description List of URLs to process
   * @type array | undefined
   */
  urls?: string[];
  /**
   * @description Project access key (also accepted as x-access-key header)
   * @type string | undefined
   */
  access_key?: string;
};

export type PostInstagramChannelStatsBulkMutationResponse =
  PostInstagramChannelStatsBulk200;

export type PostInstagramChannelStatsBulkMutation = {
  Response: PostInstagramChannelStatsBulk200;
  Request: PostInstagramChannelStatsBulkMutationRequest;
  Errors:
    | PostInstagramChannelStatsBulk400
    | PostInstagramChannelStatsBulk403
    | PostInstagramChannelStatsBulk404
    | PostInstagramChannelStatsBulk500;
};
