/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const acquiringPaymentOrderRefundRequestModelSchema = z.object({
  amount: z.number().gt(0).describe("Не больше суммы оплаты"),
});
