/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { externalAcquiringPaymentTypeEnumSchema } from "./external-acquiring-payment-type-enum-schema.ts";
import { paymentItemModelSchema } from "./payment-item-model-schema.ts";

export const acquiringPaymentRegistryItemModelSchema = z.object({
  get paymentType() {
    return externalAcquiringPaymentTypeEnumSchema;
  },
  totalAmount: z.number(),
  paymentId: z.optional(z.string()),
  get payments() {
    return z.array(paymentItemModelSchema).min(1);
  },
});
