/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { acquiringGetPaymentOperationListResponseModelSchema } from "./acquiring-get-payment-operation-list-response-model-schema.ts";
import { metaModelSchema } from "./meta-model-schema.ts";
import { paginatedLinkModelSchema } from "./paginated-link-model-schema.ts";

export const acquiringGetPaymentOperationListResponseDataModelSchema = z.object(
  {
    get Data() {
      return acquiringGetPaymentOperationListResponseModelSchema;
    },
    get Links() {
      return paginatedLinkModelSchema;
    },
    get Meta() {
      return metaModelSchema;
    },
  },
);
