/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { acquiringPaymentRegistryModelSchema } from "./acquiring-payment-registry-model-schema.ts";
import { linkModelSchema } from "./link-model-schema.ts";
import { metaModelSchema } from "./meta-model-schema.ts";

export const acquiringPaymentRegistryResponseDataModelSchema = z.object({
  get Data() {
    return acquiringPaymentRegistryModelSchema;
  },
  get Links() {
    return linkModelSchema;
  },
  get Meta() {
    return metaModelSchema;
  },
});
