/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { acquiringPaymentOperationRefundModelSchema } from "./acquiring-payment-operation-refund-model-schema.ts";
import { linkModelSchema } from "./link-model-schema.ts";
import { metaModelSchema } from "./meta-model-schema.ts";

export const acquiringPaymentOperationRefundResponseModelSchema = z.object({
  get Data() {
    return acquiringPaymentOperationRefundModelSchema;
  },
  get Links() {
    return linkModelSchema;
  },
  get Meta() {
    return metaModelSchema;
  },
});
