/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const acquiringPaymentStatusSchema = z.enum([
  "CREATED",
  "APPROVED",
  "ON-REFUND",
  "REFUNDED",
  "EXPIRED",
  "REFUNDED_PARTIALLY",
  "AUTHORIZED",
  "WAIT_FULL_PAYMENT",
]);
