/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const acquiringPaymentOperationRefundModelSchema = z.object({
  isRefund: z.boolean(),
  operationId: z.string(),
  amount: z.number(),
  date: z.iso.date(),
  orderId: z.string(),
});
