/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const acquiringRetailerStatusSchema = z.enum([
  "NEW",
  "ADDRESS_DADATA",
  "OPEN_ACCOUNT",
  "TWPG_SENDED",
  "RETAILER_CREATED",
  "TERMINAL_CREATED",
  "FILE_SENT",
  "REG",
  "CLOSE",
]);
