/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { acquiringCreatePaymentOperationWithReceiptRequestModelSchema } from "./acquiring-create-payment-operation-with-receipt-request-model-schema.ts";

export const acquiringCreatePaymentOperationWithReceiptRequestDataModelSchema =
  z.object({
    get Data() {
      return acquiringCreatePaymentOperationWithReceiptRequestModelSchema;
    },
  });
