/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { acquiringCreatePaymentOperationResponseModelSchema } from "./acquiring-create-payment-operation-response-model-schema.ts";
import { linkModelSchema } from "./link-model-schema.ts";
import { metaModelSchema } from "./meta-model-schema.ts";

export const acquiringCreatePaymentOperationResponseDataModelSchema = z.object({
  get Data() {
    return acquiringCreatePaymentOperationResponseModelSchema;
  },
  get Links() {
    return linkModelSchema;
  },
  get Meta() {
    return metaModelSchema;
  },
});
