/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { acquiringPaymentOrderRefundRequestModelSchema } from "./acquiring-payment-order-refund-request-model-schema.ts";

export const acquiringPaymentOrderRefundRequestDataModelSchema = z.object({
  get Data() {
    return acquiringPaymentOrderRefundRequestModelSchema;
  },
});
