/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { acquiringCapturePaymentResponseModelSchema } from "./acquiring-capture-payment-response-model-schema.ts";
import { badRequestErrorResponseSchema } from "./bad-request-error-response-schema.ts";
import { errorResponseSchema } from "./error-response-schema.ts";
import { forbiddenErrorResponseSchema } from "./forbidden-error-response-schema.ts";
import { notFoundErrorResponseSchema } from "./not-found-error-response-schema.ts";
import { unauthorizedErrorResponseSchema } from "./unauthorized-error-response-schema.ts";

export const capturePaymentAcquiringV10PaymentsOperationIdCapturePostPathParamsSchema =
  z.object({
    operationId: z.string().describe("Идентификатор подписки"),
  });

/**
 * @description Successful Response
 */
export const capturePaymentAcquiringV10PaymentsOperationIdCapturePost200Schema =
  z.lazy(() => acquiringCapturePaymentResponseModelSchema);

/**
 * @description Bad Request
 */
export const capturePaymentAcquiringV10PaymentsOperationIdCapturePost400Schema =
  z.lazy(() => badRequestErrorResponseSchema);

/**
 * @description Unauthorized
 */
export const capturePaymentAcquiringV10PaymentsOperationIdCapturePost401Schema =
  z.lazy(() => unauthorizedErrorResponseSchema);

/**
 * @description Forbidden
 */
export const capturePaymentAcquiringV10PaymentsOperationIdCapturePost403Schema =
  z.lazy(() => forbiddenErrorResponseSchema);

/**
 * @description Not Found
 */
export const capturePaymentAcquiringV10PaymentsOperationIdCapturePost404Schema =
  z.lazy(() => notFoundErrorResponseSchema);

/**
 * @description Server error
 */
export const capturePaymentAcquiringV10PaymentsOperationIdCapturePost500Schema =
  z.lazy(() => errorResponseSchema);

export const capturePaymentAcquiringV10PaymentsOperationIdCapturePostMutationResponseSchema =
  z.lazy(
    () => capturePaymentAcquiringV10PaymentsOperationIdCapturePost200Schema,
  );
