/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const externalAcquiringPaymentTypeEnumSchema = z.enum([
  "sbp",
  "card",
  "tinkoff",
  "dolyame",
]);
