/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { acquiringPaymentRegistryResponseDataModelSchema } from "./acquiring-payment-registry-response-data-model-schema.ts";
import { badRequestErrorResponseSchema } from "./bad-request-error-response-schema.ts";
import { errorResponseSchema } from "./error-response-schema.ts";
import { forbiddenErrorResponseSchema } from "./forbidden-error-response-schema.ts";
import { notFoundErrorResponseSchema } from "./not-found-error-response-schema.ts";
import { unauthorizedErrorResponseSchema } from "./unauthorized-error-response-schema.ts";

export const getPaymentRegistryAcquiringV10RegistryGetQueryParamsSchema =
  z.object({
    customerCode: z.string().describe("Уникальный код клиента"),
    merchantId: z
      .string()
      .describe("Идентификатор торговой точки в интернет-эквайринге"),
    paymentId: z.optional(
      z
        .string()
        .describe(
          "Уникальный идентификатор платежа, по которому произошла транзакция",
        ),
    ),
    date: z.string().describe("Дата реестра"),
  });

/**
 * @description Successful Response
 */
export const getPaymentRegistryAcquiringV10RegistryGet200Schema = z.lazy(
  () => acquiringPaymentRegistryResponseDataModelSchema,
);

/**
 * @description Bad Request
 */
export const getPaymentRegistryAcquiringV10RegistryGet400Schema = z.lazy(
  () => badRequestErrorResponseSchema,
);

/**
 * @description Unauthorized
 */
export const getPaymentRegistryAcquiringV10RegistryGet401Schema = z.lazy(
  () => unauthorizedErrorResponseSchema,
);

/**
 * @description Forbidden
 */
export const getPaymentRegistryAcquiringV10RegistryGet403Schema = z.lazy(
  () => forbiddenErrorResponseSchema,
);

/**
 * @description Not Found
 */
export const getPaymentRegistryAcquiringV10RegistryGet404Schema = z.lazy(
  () => notFoundErrorResponseSchema,
);

/**
 * @description Server error
 */
export const getPaymentRegistryAcquiringV10RegistryGet500Schema = z.lazy(
  () => errorResponseSchema,
);

export const getPaymentRegistryAcquiringV10RegistryGetQueryResponseSchema =
  z.lazy(() => getPaymentRegistryAcquiringV10RegistryGet200Schema);
