/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { acquiringRetailerListResponseModelSchema } from "./acquiring-retailer-list-response-model-schema.ts";
import { badRequestErrorResponseSchema } from "./bad-request-error-response-schema.ts";
import { errorResponseSchema } from "./error-response-schema.ts";
import { forbiddenErrorResponseSchema } from "./forbidden-error-response-schema.ts";
import { notFoundErrorResponseSchema } from "./not-found-error-response-schema.ts";
import { unauthorizedErrorResponseSchema } from "./unauthorized-error-response-schema.ts";

export const getRetailersAcquiringV10RetailersGetQueryParamsSchema = z.object({
  customerCode: z.string().describe("Уникальный код клиента"),
});

/**
 * @description Successful Response
 */
export const getRetailersAcquiringV10RetailersGet200Schema = z.lazy(
  () => acquiringRetailerListResponseModelSchema,
);

/**
 * @description Bad Request
 */
export const getRetailersAcquiringV10RetailersGet400Schema = z.lazy(
  () => badRequestErrorResponseSchema,
);

/**
 * @description Unauthorized
 */
export const getRetailersAcquiringV10RetailersGet401Schema = z.lazy(
  () => unauthorizedErrorResponseSchema,
);

/**
 * @description Forbidden
 */
export const getRetailersAcquiringV10RetailersGet403Schema = z.lazy(
  () => forbiddenErrorResponseSchema,
);

/**
 * @description Not Found
 */
export const getRetailersAcquiringV10RetailersGet404Schema = z.lazy(
  () => notFoundErrorResponseSchema,
);

/**
 * @description Server error
 */
export const getRetailersAcquiringV10RetailersGet500Schema = z.lazy(
  () => errorResponseSchema,
);

export const getRetailersAcquiringV10RetailersGetQueryResponseSchema = z.lazy(
  () => getRetailersAcquiringV10RetailersGet200Schema,
);
