/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { acquiringGetPaymentOperationInfoResponseDataModelSchema } from "./acquiring-get-payment-operation-info-response-data-model-schema.ts";
import { badRequestErrorResponseSchema } from "./bad-request-error-response-schema.ts";
import { errorResponseSchema } from "./error-response-schema.ts";
import { forbiddenErrorResponseSchema } from "./forbidden-error-response-schema.ts";
import { notFoundErrorResponseSchema } from "./not-found-error-response-schema.ts";
import { unauthorizedErrorResponseSchema } from "./unauthorized-error-response-schema.ts";

export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGetPathParamsSchema =
  z.object({
    operationId: z.string().describe("Идентификатор платежа"),
  });

/**
 * @description Successful Response
 */
export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet200Schema =
  z.lazy(() => acquiringGetPaymentOperationInfoResponseDataModelSchema);

/**
 * @description Bad Request
 */
export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet400Schema =
  z.lazy(() => badRequestErrorResponseSchema);

/**
 * @description Unauthorized
 */
export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet401Schema =
  z.lazy(() => unauthorizedErrorResponseSchema);

/**
 * @description Forbidden
 */
export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet403Schema =
  z.lazy(() => forbiddenErrorResponseSchema);

/**
 * @description Not Found
 */
export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet404Schema =
  z.lazy(() => notFoundErrorResponseSchema);

/**
 * @description Server error
 */
export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet500Schema =
  z.lazy(() => errorResponseSchema);

export const getPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQueryResponseSchema =
  z.lazy(
    () => getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet200Schema,
  );
