/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { acquiringGetPaymentOperationListResponseDataModelSchema } from "./acquiring-get-payment-operation-list-response-data-model-schema.ts";
import { acquiringPaymentStatusSchema } from "./acquiring-payment-status-schema.ts";
import { badRequestErrorResponseSchema } from "./bad-request-error-response-schema.ts";
import { errorResponseSchema } from "./error-response-schema.ts";
import { forbiddenErrorResponseSchema } from "./forbidden-error-response-schema.ts";
import { notFoundErrorResponseSchema } from "./not-found-error-response-schema.ts";
import { unauthorizedErrorResponseSchema } from "./unauthorized-error-response-schema.ts";

export const getPaymentOperationListAcquiringV10PaymentsGetQueryParamsSchema =
  z.object({
    customerCode: z.string().describe("Уникальный код клиента"),
    fromDate: z.optional(
      z.string().describe("Начало периода создания операций"),
    ),
    toDate: z.optional(z.string().describe("Конец периода создания операций")),
    page: z.optional(
      z.coerce.number().int().default(1).describe("Номер страницы"),
    ),
    perPage: z.optional(
      z.coerce
        .number()
        .int()
        .default(1000)
        .describe("Количество записей на странице"),
    ),
    get status() {
      return acquiringPaymentStatusSchema
        .describe("Статус операции")
        .optional();
    },
  });

/**
 * @description Successful Response
 */
export const getPaymentOperationListAcquiringV10PaymentsGet200Schema = z.lazy(
  () => acquiringGetPaymentOperationListResponseDataModelSchema,
);

/**
 * @description Bad Request
 */
export const getPaymentOperationListAcquiringV10PaymentsGet400Schema = z.lazy(
  () => badRequestErrorResponseSchema,
);

/**
 * @description Unauthorized
 */
export const getPaymentOperationListAcquiringV10PaymentsGet401Schema = z.lazy(
  () => unauthorizedErrorResponseSchema,
);

/**
 * @description Forbidden
 */
export const getPaymentOperationListAcquiringV10PaymentsGet403Schema = z.lazy(
  () => forbiddenErrorResponseSchema,
);

/**
 * @description Not Found
 */
export const getPaymentOperationListAcquiringV10PaymentsGet404Schema = z.lazy(
  () => notFoundErrorResponseSchema,
);

/**
 * @description Server error
 */
export const getPaymentOperationListAcquiringV10PaymentsGet500Schema = z.lazy(
  () => errorResponseSchema,
);

export const getPaymentOperationListAcquiringV10PaymentsGetQueryResponseSchema =
  z.lazy(() => getPaymentOperationListAcquiringV10PaymentsGet200Schema);
