/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const notFoundErrorSchema = z.object({
  errorCode: z.string(),
  message: z.string().max(603),
  url: z.string(),
});
