/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { notFoundErrorSchema } from "./not-found-error-schema.ts";

export const notFoundErrorResponseSchema = z.object({
  code: z.string().max(40),
  id: z.string().max(40),
  message: z.string().max(600),
  get Errors() {
    return z.array(notFoundErrorSchema);
  },
});
