/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const paginatedLinkModelSchema = z.object({
  self: z.url().min(1).max(2083),
  first: z.optional(z.url().min(1).max(2083)),
  prev: z.optional(z.url().min(1).max(2083)),
  next: z.optional(z.url().min(1).max(2083)),
  last: z.optional(z.url().min(1).max(2083)),
});
