/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { acquiringPaymentStatusSchema } from "./acquiring-payment-status-schema.ts";

export const paymentItemModelSchema = z.object({
  purpose: z.string(),
  get status() {
    return acquiringPaymentStatusSchema.default("CREATED").optional();
  },
  amount: z.number(),
  operationId: z.string(),
  paymentLink: z.string(),
  time: z.string(),
  number: z.string(),
  commission: z.number(),
  enrollmentAmount: z.number(),
});
