/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const receiptClientModelSchema = z.object({
  name: z.optional(z.string()),
  email: z.email(),
  phone: z.optional(z.string()),
});
