/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const supplierModelSchema = z.object({
  phone: z
    .string()
    .min(11)
    .max(15)
    .regex(/^\+?\d+$/),
  name: z.string(),
  taxCode: z.string().min(10).max(12).regex(/^\d+$/),
});
