/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { unauthorizedErrorSchema } from "./unauthorized-error-schema.ts";

export const unauthorizedErrorResponseSchema = z.object({
  code: z.string().max(40),
  id: z.string().max(40),
  message: z.string().max(600),
  get Errors() {
    return z.array(unauthorizedErrorSchema);
  },
});
