/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const vatTypeHistoricalSchema = z.enum([
  "none",
  "vat0",
  "vat5",
  "vat7",
  "vat10",
  "vat20",
  "vat22",
  "vat105",
  "vat107",
  "vat110",
  "vat120",
  "vat122",
]);
