export enum OpenAPITags {
  Archive = "Archive",
  Credits = "Credits",
  Ideas = "Ideas",
  IdeasLists = "Ideas lists",
  Plans = "Plans",
  Platforms = "Platforms",
  Profiles = "Profiles",
  Referral = "Referral",
  Scenarios = "Scenarios",
  Subscriptions = "Subscriptions",
  Templates = "Templates",
  Tones = "Tones",
  VideoDurations = "Video durations",
  VideoTypes = "Video types",
}
