services:
  server:
    build: .
    command: pnpm run start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - POLZA_AI_BASE_URL=${POLZA_AI_BASE_URL}
      - POLZA_AI_API_KEY=${POLZA_AI_API_KEY}
      - POLZA_AI_STRUCTURED_OUTPUT_MODEL=${POLZA_AI_STRUCTURED_OUTPUT_MODEL}
      - POLZA_AI_IMAGE_MODEL=${POLZA_AI_IMAGE_MODEL}
      - WEB_APP_BASE_URL=${WEB_APP_BASE_URL}
      - LANDING_BASE_URL=${LANDING_BASE_URL}

  workers:
    build: .
    command: pnpm run start:workers
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - POLZA_AI_BASE_URL=${POLZA_AI_BASE_URL}
      - POLZA_AI_API_KEY=${POLZA_AI_API_KEY}
      - POLZA_AI_STRUCTURED_OUTPUT_MODEL=${POLZA_AI_STRUCTURED_OUTPUT_MODEL}
      - POLZA_AI_IMAGE_MODEL=${POLZA_AI_IMAGE_MODEL}
      - WEB_APP_BASE_URL=${WEB_APP_BASE_URL}
      - LANDING_BASE_URL=${LANDING_BASE_URL}
