FROM node:22-alpine AS base

# Установка pnpm версии 9.x (совместимо с lockfileVersion 6.0)
RUN corepack enable && corepack prepare pnpm@9 --activate

FROM base AS builder

RUN apk add --no-cache gcompat
WORKDIR /app

# Принимаем build аргументы для переменных окружения
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

ARG POSTGRES_URL
ENV POSTGRES_URL=$POSTGRES_URL

ARG REDIS_URL
ENV REDIS_URL=$REDIS_URL

ARG S3_BUCKET_BASE_URL
ENV S3_BUCKET_BASE_URL=$S3_BUCKET_BASE_URL

ARG S3_BUCKET_NAME
ENV S3_BUCKET_NAME=$S3_BUCKET_NAME

ARG S3_REGION
ENV S3_REGION=$S3_REGION

ARG S3_ACCESS_KEY
ENV S3_ACCESS_KEY=$S3_ACCESS_KEY

ARG S3_SECRET_ACCESS_KEY
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY

ARG BETTER_AUTH_SECRET
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

ARG BETTER_AUTH_URL
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL

ARG POLZA_AI_BASE_URL
ENV POLZA_AI_BASE_URL=$POLZA_AI_BASE_URL

ARG POLZA_AI_API_KEY
ENV POLZA_AI_API_KEY=$POLZA_AI_API_KEY

ARG POLZA_AI_STRUCTURED_OUTPUT_MODEL
ENV POLZA_AI_STRUCTURED_OUTPUT_MODEL=$POLZA_AI_STRUCTURED_OUTPUT_MODEL

ARG POLZA_AI_IMAGE_MODEL
ENV POLZA_AI_IMAGE_MODEL=$POLZA_AI_IMAGE_MODEL

ARG ROUTER_AI_BASE_URL
ENV ROUTER_AI_BASE_URL=$ROUTER_AI_BASE_URL

ARG ROUTER_AI_API_KEY
ENV ROUTER_AI_API_KEY=$ROUTER_AI_API_KEY

ARG ROUTER_AI_STRUCTURED_OUTPUT_MODEL
ENV ROUTER_AI_STRUCTURED_OUTPUT_MODEL=$ROUTER_AI_STRUCTURED_OUTPUT_MODEL

ARG ROUTER_AI_IMAGE_MODEL
ENV ROUTER_AI_IMAGE_MODEL=$ROUTER_AI_IMAGE_MODEL

ARG VSELLM_BASE_URL
ENV VSELLM_BASE_URL=$VSELLM_BASE_URL

ARG VSELLM_API_KEY
ENV VSELLM_API_KEY=$VSELLM_API_KEY

ARG VSELLM_STRUCTURED_OUTPUT_MODEL
ENV VSELLM_STRUCTURED_OUTPUT_MODEL=$VSELLM_STRUCTURED_OUTPUT_MODEL

ARG VSELLM_IMAGE_MODEL
ENV VSELLM_IMAGE_MODEL=$VSELLM_IMAGE_MODEL

ARG WEB_APP_BASE_URL
ENV WEB_APP_BASE_URL=$WEB_APP_BASE_URL

ARG LANDING_BASE_URL
ENV LANDING_BASE_URL=$LANDING_BASE_URL

# Копируем файлы зависимостей
COPY package.json pnpm-lock.yaml ./
COPY tsconfig.json tsup.config.ts drizzle.config.ts auth.ts ./

# Копируем исходный код
COPY src ./src

# Устанавливаем зависимости и собираем проект
RUN pnpm install --frozen-lockfile && \
    pnpm run build && \
    pnpm prune --production

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 hono

# Копируем собранные файлы и зависимости
COPY --from=builder --chown=hono:nodejs /app/node_modules /app/node_modules
COPY --from=builder --chown=hono:nodejs /app/dist /app/dist
COPY --from=builder --chown=hono:nodejs /app/package.json /app/package.json

USER hono
EXPOSE 3000

CMD ["pnpm", "run", "start"]