/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const getTiktokChannelStatsQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Channel stats retrieved successfully
 */
export const getTiktokChannelStats200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        profileUrl: z.optional(z.string()),
        username: z.optional(z.string()),
        nickname: z.optional(z.string()),
        signature: z.optional(z.string()),
        verified: z.optional(z.boolean()),
        avatar: z.optional(z.string()),
        followers: z.optional(z.int()),
        following: z.optional(z.int()),
        totalLikes: z.optional(z.int()),
        totalVideos: z.optional(z.int()),
        bioLink: z.optional(z.string()),
      }),
    ),
  })
  .describe("Channel stats retrieved successfully");

/**
 * @description Missing required parameter
 */
export const getTiktokChannelStats400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const getTiktokChannelStats403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const getTiktokChannelStats404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const getTiktokChannelStats500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const getTiktokChannelStatsQueryResponseSchema = z.lazy(
  () => getTiktokChannelStats200Schema,
);
