/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const getYoutubeDownloadQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Download URL generated
 */
export const getYoutubeDownload200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        url: z.optional(z.string()),
        title: z.optional(z.string()),
        duration: z.optional(z.string()),
        downloadUrl: z.optional(z.string()),
        fileSize: z.optional(z.number()),
        fileSizeMB: z.optional(z.string()),
        format: z.optional(z.string()),
        quality: z.optional(z.string()),
        expiresIn: z.optional(z.string()),
      }),
    ),
  })
  .describe("Download URL generated");

/**
 * @description Missing required parameter
 */
export const getYoutubeDownload400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const getYoutubeDownload403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const getYoutubeDownload404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const getYoutubeDownload500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const getYoutubeDownloadQueryResponseSchema = z.lazy(
  () => getYoutubeDownload200Schema,
);
