/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const getYoutubeSearchQueryParamsSchema = z
  .object({
    query: z.optional(z.string().describe("Search query")),
    limit: z.optional(
      z.coerce.number().int().describe("Maximum number of results"),
    ),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Search results returned
 */
export const getYoutubeSearch200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        query: z.optional(z.string()),
        results: z.optional(
          z.array(
            z.object({
              videoId: z.optional(z.string()),
              title: z.optional(z.string()),
              thumbnail: z.optional(z.string()),
              channelName: z.optional(z.string()),
              channelId: z.optional(z.string()),
              channelUrl: z.optional(z.string()),
              publishedTime: z.optional(z.string()),
              duration: z.optional(z.string()),
              views: z.optional(z.int()),
              viewsFormatted: z.optional(z.string()),
              description: z.optional(z.string()),
              url: z.optional(z.string()),
              verified: z.optional(z.boolean()),
            }),
          ),
        ),
      }),
    ),
  })
  .describe("Search results returned");

/**
 * @description Missing required parameter
 */
export const getYoutubeSearch400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const getYoutubeSearch403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const getYoutubeSearch404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const getYoutubeSearch500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const getYoutubeSearchQueryResponseSchema = z.lazy(
  () => getYoutubeSearch200Schema,
);
