/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const getInstagramChannelReelsQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    limit: z.optional(
      z.coerce.number().int().describe("Maximum number of results to return"),
    ),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Channel reels retrieved successfully
 */
export const getInstagramChannelReels200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        profileUrl: z.optional(z.string()),
        username: z.optional(z.string()),
        items: z.optional(
          z.array(
            z.object({
              id: z.optional(z.string()),
              shortcode: z.optional(z.string()),
              url: z.optional(z.string()),
              caption: z.optional(z.string()),
              likes: z.optional(z.int()),
              comments: z.optional(z.int()),
              views: z.optional(z.int()),
              duration: z.optional(z.number()),
              thumbnailUrl: z.optional(z.string()),
              author: z.optional(
                z.object({
                  id: z.optional(z.string()),
                  username: z.optional(z.string()),
                  fullName: z.optional(z.string()),
                  isVerified: z.optional(z.boolean()),
                  profilePicUrl: z.optional(z.string()),
                }),
              ),
            }),
          ),
        ),
        count: z.optional(z.int()),
        hasMore: z.optional(z.boolean()),
        cursor: z.optional(z.string()),
      }),
    ),
  })
  .describe("Channel reels retrieved successfully");

/**
 * @description Missing required parameter
 */
export const getInstagramChannelReels400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const getInstagramChannelReels403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const getInstagramChannelReels404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const getInstagramChannelReels500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const getInstagramChannelReelsQueryResponseSchema = z.lazy(
  () => getInstagramChannelReels200Schema,
);
