/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const getTiktokCommentsQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    limit: z.optional(
      z.coerce.number().int().describe("Maximum number of results to return"),
    ),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Comments retrieved successfully
 */
export const getTiktokComments200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        videoId: z.optional(z.string()),
        comments: z.optional(
          z.array(
            z.object({
              id: z.optional(z.string()),
              author: z.optional(z.string()),
              username: z.optional(z.string()),
              text: z.optional(z.string()),
              likes: z.optional(z.int()),
              avatar: z.optional(z.string()),
              createTime: z.optional(z.string()),
              replyCount: z.optional(z.int()),
            }),
          ),
        ),
        commentCount: z.optional(z.int()),
        hasMore: z.optional(z.boolean()),
        cursor: z.optional(z.string()),
      }),
    ),
  })
  .describe("Comments retrieved successfully");

/**
 * @description Missing required parameter
 */
export const getTiktokComments400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const getTiktokComments403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const getTiktokComments404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const getTiktokComments500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const getTiktokCommentsQueryResponseSchema = z.lazy(
  () => getTiktokComments200Schema,
);
