/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postInstagramCommentsQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    limit: z.optional(
      z.coerce.number().int().describe("Maximum number of results to return"),
    ),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Comments retrieved successfully
 */
export const postInstagramComments200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        postUrl: z.optional(z.string()),
        comments: z.optional(
          z.array(
            z.object({
              id: z.optional(z.string()),
              text: z.optional(z.string()),
              likeCount: z.optional(z.int()),
              replyCount: z.optional(z.int()),
              user: z.optional(
                z.object({
                  id: z.optional(z.string()),
                  username: z.optional(z.string()),
                  fullName: z.optional(z.string()),
                  isVerified: z.optional(z.boolean()),
                  profilePicUrl: z.optional(z.string()),
                }),
              ),
            }),
          ),
        ),
        commentCount: z.optional(z.int()),
        hasMore: z.optional(z.boolean()),
        cursor: z.optional(z.string()),
      }),
    ),
  })
  .describe("Comments retrieved successfully");

/**
 * @description Missing required parameter
 */
export const postInstagramComments400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postInstagramComments403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postInstagramComments404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postInstagramComments500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postInstagramCommentsMutationResponseSchema = z.lazy(
  () => postInstagramComments200Schema,
);
