/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postInstagramChannelStatsQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Profile stats retrieved successfully
 */
export const postInstagramChannelStats200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        profileUrl: z.optional(z.string()),
        username: z.optional(z.string()),
        fullName: z.optional(z.string()),
        verified: z.optional(z.boolean()),
        followers: z.optional(z.int()),
        following: z.optional(z.int()),
        totalPosts: z.optional(z.int()),
        bio: z.optional(z.string()),
        avatar: z.optional(z.string()),
      }),
    ),
  })
  .describe("Profile stats retrieved successfully");

/**
 * @description Missing required parameter
 */
export const postInstagramChannelStats400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postInstagramChannelStats403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postInstagramChannelStats404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postInstagramChannelStats500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postInstagramChannelStatsMutationResponseSchema = z.lazy(
  () => postInstagramChannelStats200Schema,
);
