/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postTiktokTranscriptQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Transcript extracted successfully
 */
export const postTiktokTranscript200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        url: z.optional(z.string()),
        videoId: z.optional(z.string()),
        transcript: z.optional(
          z.string().describe("Full plain-text transcript"),
        ),
        transcriptSegments: z.optional(
          z.array(
            z.object({
              text: z.optional(z.string()),
              start: z.optional(z.number()),
              duration: z.optional(z.number()),
              timestamp: z.optional(z.string()),
            }),
          ),
        ),
        wordCount: z.optional(z.int()),
        segments: z.optional(z.int()),
        language: z.optional(z.string()),
      }),
    ),
  })
  .describe("Transcript extracted successfully");

/**
 * @description Missing required parameter
 */
export const postTiktokTranscript400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postTiktokTranscript403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postTiktokTranscript404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postTiktokTranscript500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postTiktokTranscriptMutationResponseSchema = z.lazy(
  () => postTiktokTranscript200Schema,
);
