/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Batch results returned
 */
export const postTiktokChannelVideoMetricsBulk200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        results: z.optional(z.array(z.object({}))),
      }),
    ),
  })
  .describe("Batch results returned");

/**
 * @description Missing required parameter
 */
export const postTiktokChannelVideoMetricsBulk400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postTiktokChannelVideoMetricsBulk403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postTiktokChannelVideoMetricsBulk404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postTiktokChannelVideoMetricsBulk500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postTiktokChannelVideoMetricsBulkMutationRequestSchema = z.object({
  urls: z.optional(z.array(z.string()).describe("List of URLs to process")),
  access_key: z.optional(
    z
      .string()
      .describe("Project access key (also accepted as x-access-key header)"),
  ),
});

export const postTiktokChannelVideoMetricsBulkMutationResponseSchema = z.lazy(
  () => postTiktokChannelVideoMetricsBulk200Schema,
);
