/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postYoutubeStatsQueryParamsSchema = z
  .object({
    url: z.optional(z.string().describe("Full URL of the resource")),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Video stats retrieved successfully
 */
export const postYoutubeStats200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        url: z.optional(z.string()),
        videoId: z.optional(z.string()),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        channelName: z.optional(z.string()),
        channelLink: z.optional(z.string()),
        channelHandle: z.optional(z.string()),
        views: z.optional(z.int()),
        likes: z.optional(z.int()),
        comments: z.optional(z.int()),
        duration: z.optional(z.string()),
        publishedAt: z.optional(z.string()),
        thumbnailUrl: z.optional(z.string()),
        contentType: z.optional(z.string()),
        isShortForm: z.optional(z.boolean()),
      }),
    ),
  })
  .describe("Video stats retrieved successfully");

/**
 * @description Missing required parameter
 */
export const postYoutubeStats400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postYoutubeStats403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postYoutubeStats404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postYoutubeStats500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postYoutubeStatsMutationResponseSchema = z.lazy(
  () => postYoutubeStats200Schema,
);
