/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postTiktokHashtagSearchQueryParamsSchema = z
  .object({
    hashtag: z.optional(z.string().describe("Hashtag to search (without #)")),
    limit: z.optional(
      z.coerce.number().int().describe("Maximum number of results"),
    ),
    access_key: z.optional(
      z
        .string()
        .describe("Project access key (also accepted as x-access-key header)"),
    ),
  })
  .optional();

/**
 * @description Hashtag search results returned
 */
export const postTiktokHashtagSearch200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        hashtag: z.optional(z.string()),
        results: z.optional(
          z.array(
            z.object({
              id: z.optional(z.string()),
              desc: z.optional(z.string()),
              url: z.optional(z.string()),
              author: z.optional(
                z.object({
                  id: z.optional(z.string()),
                  uniqueId: z.optional(z.string()),
                  nickname: z.optional(z.string()),
                  avatar: z.optional(z.string()),
                  verified: z.optional(z.boolean()),
                }),
              ),
              stats: z.optional(
                z.object({
                  views: z.optional(z.int()),
                  likes: z.optional(z.int()),
                  comments: z.optional(z.int()),
                  shares: z.optional(z.int()),
                  saves: z.optional(z.int()),
                }),
              ),
            }),
          ),
        ),
        hasMore: z.optional(z.boolean()),
        cursor: z.optional(z.string()),
      }),
    ),
  })
  .describe("Hashtag search results returned");

/**
 * @description Missing required parameter
 */
export const postTiktokHashtagSearch400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postTiktokHashtagSearch403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postTiktokHashtagSearch404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postTiktokHashtagSearch500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postTiktokHashtagSearchMutationResponseSchema = z.lazy(
  () => postTiktokHashtagSearch200Schema,
);
