/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Batch results returned
 */
export const postTiktokStatsBulk200Schema = z
  .object({
    success: z.optional(z.boolean()),
    data: z.optional(
      z.object({
        results: z.optional(z.array(z.object({}))),
      }),
    ),
  })
  .describe("Batch results returned");

/**
 * @description Missing required parameter
 */
export const postTiktokStatsBulk400Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Missing required parameter");

/**
 * @description Credit limit exceeded
 */
export const postTiktokStatsBulk403Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Credit limit exceeded");

/**
 * @description Content not found or unavailable
 */
export const postTiktokStatsBulk404Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Content not found or unavailable");

/**
 * @description Internal server error
 */
export const postTiktokStatsBulk500Schema = z
  .object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
  })
  .describe("Internal server error");

export const postTiktokStatsBulkMutationRequestSchema = z.object({
  urls: z.optional(z.array(z.string()).describe("List of URLs to process")),
  access_key: z.optional(
    z
      .string()
      .describe("Project access key (also accepted as x-access-key header)"),
  ),
});

export const postTiktokStatsBulkMutationResponseSchema = z.lazy(
  () => postTiktokStatsBulk200Schema,
);
