CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "verification_identifier_value_idx" ON "verification" USING btree ("identifier","value");--> statement-breakpoint
CREATE INDEX "verification_expires_at_idx" ON "verification" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "credits_batch_user_id_created_at_idx" ON "credits_batch" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "credits_batch_user_id_status_expires_at_idx" ON "credits_batch" USING btree ("user_id","status","expires_at");--> statement-breakpoint
CREATE INDEX "credits_batch_credits_package_id_idx" ON "credits_batch" USING btree ("credits_package_id");--> statement-breakpoint
CREATE INDEX "credits_usage_user_id_created_at_idx" ON "credits_usage" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "credits_usage_batch_id_idx" ON "credits_usage" USING btree ("credits_batch_id");--> statement-breakpoint
CREATE INDEX "payment_payment_id_idx" ON "payment" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "payment_user_id_created_at_idx" ON "payment" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "payment_user_id_status_created_at_idx" ON "payment" USING btree ("user_id","status","created_at");--> statement-breakpoint
CREATE INDEX "payment_payment_method_id_idx" ON "payment" USING btree ("payment_method_id");--> statement-breakpoint
CREATE INDEX "payment_method_payment_method_id_idx" ON "payment_method" USING btree ("payment_method_id");--> statement-breakpoint
CREATE INDEX "payment_method_user_id_created_at_idx" ON "payment_method" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "payment_method_user_id_status_created_at_idx" ON "payment_method" USING btree ("user_id","status","created_at");--> statement-breakpoint
CREATE INDEX "subscription_user_id_starts_at_idx" ON "subscription" USING btree ("user_id","starts_at");--> statement-breakpoint
CREATE INDEX "subscription_user_id_cycle_ends_at_created_at_idx" ON "subscription" USING btree ("user_id","cycle_ends_at","created_at");--> statement-breakpoint
CREATE INDEX "subscription_tariff_id_idx" ON "subscription" USING btree ("tariff_id");--> statement-breakpoint
CREATE INDEX "profiles_from_channels_job_user_id_created_at_idx" ON "profiles_from_channels_job" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "credits_batch_to_payment_credits_batch_id_idx" ON "credits_batch_to_payment" USING btree ("credits_batch_id");--> statement-breakpoint
CREATE INDEX "credits_batch_to_payment_payment_id_idx" ON "credits_batch_to_payment" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "ideas_list_to_export_document_list_saved_created_idx" ON "ideas_list_to_export_document" USING btree ("ideas_list_id","saved_only","created_at");--> statement-breakpoint
CREATE INDEX "ideas_list_to_export_document_list_export_idx" ON "ideas_list_to_export_document" USING btree ("ideas_list_id","export_document_id");--> statement-breakpoint
CREATE INDEX "ideas_list_to_tone_ideas_list_id_idx" ON "ideas_list_to_tone" USING btree ("ideas_list_id");--> statement-breakpoint
CREATE INDEX "ideas_list_to_tone_tone_id_ideas_list_id_idx" ON "ideas_list_to_tone" USING btree ("tone_id","ideas_list_id");--> statement-breakpoint
CREATE INDEX "ideas_list_to_video_type_ideas_list_id_idx" ON "ideas_list_to_video_type" USING btree ("ideas_list_id");--> statement-breakpoint
CREATE INDEX "ideas_list_to_video_type_video_type_id_ideas_list_id_idx" ON "ideas_list_to_video_type" USING btree ("video_type_id","ideas_list_id");--> statement-breakpoint
CREATE INDEX "profile_to_platform_profile_id_platform_id_idx" ON "profile_to_platform" USING btree ("profile_id","platform_id");--> statement-breakpoint
CREATE INDEX "profile_to_tone_profile_id_tone_id_idx" ON "profile_to_tone" USING btree ("profile_id","tone_id");--> statement-breakpoint
CREATE INDEX "scenario_to_platform_scenario_id_idx" ON "scenario_to_platform" USING btree ("scenario_id");--> statement-breakpoint
CREATE INDEX "scenario_to_platform_platform_id_scenario_id_idx" ON "scenario_to_platform" USING btree ("platform_id","scenario_id");--> statement-breakpoint
CREATE INDEX "scenario_to_tone_scenario_id_idx" ON "scenario_to_tone" USING btree ("scenario_id");--> statement-breakpoint
CREATE INDEX "scenario_to_tone_tone_id_scenario_id_idx" ON "scenario_to_tone" USING btree ("tone_id","scenario_id");--> statement-breakpoint
CREATE INDEX "scenario_version_to_export_document_version_created_idx" ON "scenario_version_to_export_document" USING btree ("scenario_version_id","created_at");--> statement-breakpoint
CREATE INDEX "scenario_version_to_export_document_version_export_idx" ON "scenario_version_to_export_document" USING btree ("scenario_version_id","export_document_id");--> statement-breakpoint
CREATE INDEX "subscription_to_credits_batch_subscription_id_idx" ON "subscription_to_credits_batch" USING btree ("subscription_id");--> statement-breakpoint
CREATE INDEX "subscription_to_credits_batch_credits_batch_id_idx" ON "subscription_to_credits_batch" USING btree ("credits_batch_id");--> statement-breakpoint
CREATE INDEX "subscription_to_payment_subscription_id_idx" ON "subscription_to_payment" USING btree ("subscription_id");--> statement-breakpoint
CREATE INDEX "subscription_to_payment_payment_id_idx" ON "subscription_to_payment" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "idea_ideas_list_id_created_at_idx" ON "idea" USING btree ("ideas_list_id","created_at");--> statement-breakpoint
CREATE INDEX "ideas_list_user_id_created_at_idx" ON "ideas_list" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "ideas_list_user_id_updated_at_idx" ON "ideas_list" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE INDEX "ideas_list_profile_id_idx" ON "ideas_list" USING btree ("profile_id");--> statement-breakpoint
CREATE INDEX "ideas_list_template_id_idx" ON "ideas_list" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "profile_user_id_created_at_idx" ON "profile" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "profile_type_id_idx" ON "profile" USING btree ("type_id");--> statement-breakpoint
CREATE INDEX "scenario_user_id_created_at_idx" ON "scenario" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "scenario_user_id_updated_at_idx" ON "scenario" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE INDEX "scenario_user_id_scheduled_start_at_idx" ON "scenario" USING btree ("user_id","scheduled_start_at");--> statement-breakpoint
CREATE INDEX "scenario_profile_id_idx" ON "scenario" USING btree ("profile_id");--> statement-breakpoint
CREATE INDEX "scenario_template_id_idx" ON "scenario" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "scenario_video_type_id_idx" ON "scenario" USING btree ("video_type_id");--> statement-breakpoint
CREATE INDEX "scenario_video_duration_id_idx" ON "scenario" USING btree ("video_duration_id");--> statement-breakpoint
CREATE INDEX "scenario_production_status_id_idx" ON "scenario" USING btree ("production_status_id");--> statement-breakpoint
CREATE INDEX "scenario_chapter_version_id_start_time_idx" ON "scenario_chapter" USING btree ("scenario_version_id","start_time");--> statement-breakpoint
CREATE INDEX "scenario_chapter_production_status_id_idx" ON "scenario_chapter" USING btree ("production_status_id");--> statement-breakpoint
CREATE INDEX "scenario_metadata_scenario_id_platform_id_idx" ON "scenario_metadata" USING btree ("scenario_id","platform_id");--> statement-breakpoint
CREATE INDEX "scenario_scene_chapter_id_start_time_idx" ON "scenario_scene" USING btree ("scenario_chapter_id","start_time");--> statement-breakpoint
CREATE INDEX "scenario_scene_component_scene_id_created_at_idx" ON "scenario_scene_component" USING btree ("scenario_scene_id","created_at");--> statement-breakpoint
CREATE INDEX "scenario_scene_component_type_id_idx" ON "scenario_scene_component" USING btree ("type_id");--> statement-breakpoint
CREATE INDEX "scenario_scene_preview_scene_id_idx" ON "scenario_scene_preview" USING btree ("scenario_scene_id");--> statement-breakpoint
CREATE INDEX "scenario_version_scenario_id_created_at_idx" ON "scenario_version" USING btree ("scenario_id","created_at");--> statement-breakpoint
CREATE INDEX "referral_code_user_id_created_at_idx" ON "referral_code" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "referral_code_reward_id_idx" ON "referral_code" USING btree ("referral_reward_id");--> statement-breakpoint
CREATE INDEX "referral_invite_source_user_created_at_idx" ON "referral_invite" USING btree ("referral_source_user_id","created_at");--> statement-breakpoint
CREATE INDEX "referral_invite_source_user_updated_at_idx" ON "referral_invite" USING btree ("referral_source_user_id","updated_at");--> statement-breakpoint
CREATE INDEX "referral_invite_target_user_id_idx" ON "referral_invite" USING btree ("referral_target_user_id");--> statement-breakpoint
CREATE INDEX "referral_invite_code_id_idx" ON "referral_invite" USING btree ("referral_code_id");--> statement-breakpoint
CREATE INDEX "alert_status_expires_at_created_at_idx" ON "alert" USING btree ("status","expires_at","created_at");