/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetTiktokChannelStats400,
  GetTiktokChannelStats403,
  GetTiktokChannelStats404,
  GetTiktokChannelStats500,
  GetTiktokChannelStatsQueryParams,
  GetTiktokChannelStatsQueryResponse,
} from "../models/get-tiktok-channel-stats.ts";

function getGetTiktokChannelStatsUrl() {
  const res = { method: "GET", url: `/tiktok/channel-stats` as const };
  return res;
}

/**
 * @description Get stats and metadata for a TikTok creator profile.
 * @summary Tiktok Channel Stats
 * {@link /tiktok/channel-stats}
 */
export async function getTiktokChannelStats(
  { params }: { params?: GetTiktokChannelStatsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTiktokChannelStatsQueryResponse,
    ResponseErrorConfig<
      | GetTiktokChannelStats400
      | GetTiktokChannelStats403
      | GetTiktokChannelStats404
      | GetTiktokChannelStats500
    >,
    unknown
  >({
    method: "GET",
    url: getGetTiktokChannelStatsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
