/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetYoutubeStats400,
  GetYoutubeStats403,
  GetYoutubeStats404,
  GetYoutubeStats500,
  GetYoutubeStatsQueryParams,
  GetYoutubeStatsQueryResponse,
} from "../models/get-youtube-stats.ts";

function getGetYoutubeStatsUrl() {
  const res = { method: "GET", url: `/youtube/stats` as const };
  return res;
}

/**
 * @description Get detailed metadata and engagement stats for a YouTube video.
 * @summary Youtube Stats
 * {@link /youtube/stats}
 */
export async function getYoutubeStats(
  { params }: { params?: GetYoutubeStatsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetYoutubeStatsQueryResponse,
    ResponseErrorConfig<
      | GetYoutubeStats400
      | GetYoutubeStats403
      | GetYoutubeStats404
      | GetYoutubeStats500
    >,
    unknown
  >({
    method: "GET",
    url: getGetYoutubeStatsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
