/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetTiktokSearch400,
  GetTiktokSearch403,
  GetTiktokSearch404,
  GetTiktokSearch500,
  GetTiktokSearchQueryParams,
  GetTiktokSearchQueryResponse,
} from "../models/get-tiktok-search.ts";

function getGetTiktokSearchUrl() {
  const res = { method: "GET", url: `/tiktok/search` as const };
  return res;
}

/**
 * @description Search TikTok videos by keyword.
 * @summary Tiktok Search
 * {@link /tiktok/search}
 */
export async function getTiktokSearch(
  { params }: { params?: GetTiktokSearchQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTiktokSearchQueryResponse,
    ResponseErrorConfig<
      | GetTiktokSearch400
      | GetTiktokSearch403
      | GetTiktokSearch404
      | GetTiktokSearch500
    >,
    unknown
  >({
    method: "GET",
    url: getGetTiktokSearchUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
