/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetYoutubeDownload400,
  GetYoutubeDownload403,
  GetYoutubeDownload404,
  GetYoutubeDownload500,
  GetYoutubeDownloadQueryParams,
  GetYoutubeDownloadQueryResponse,
} from "../models/get-youtube-download.ts";

function getGetYoutubeDownloadUrl() {
  const res = { method: "GET", url: `/youtube/download` as const };
  return res;
}

/**
 * @description Get a direct download URL for a YouTube video.
 * @summary Youtube Download
 * {@link /youtube/download}
 */
export async function getYoutubeDownload(
  { params }: { params?: GetYoutubeDownloadQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetYoutubeDownloadQueryResponse,
    ResponseErrorConfig<
      | GetYoutubeDownload400
      | GetYoutubeDownload403
      | GetYoutubeDownload404
      | GetYoutubeDownload500
    >,
    unknown
  >({
    method: "GET",
    url: getGetYoutubeDownloadUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
