/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetTiktokChannelVideoMetrics400,
  GetTiktokChannelVideoMetrics403,
  GetTiktokChannelVideoMetrics404,
  GetTiktokChannelVideoMetrics500,
  GetTiktokChannelVideoMetricsQueryParams,
  GetTiktokChannelVideoMetricsQueryResponse,
} from "../models/get-tiktok-channel-video-metrics.ts";

function getGetTiktokChannelVideoMetricsUrl() {
  const res = { method: "GET", url: `/tiktok/channel-video-metrics` as const };
  return res;
}

/**
 * @description Get aggregated view metrics across all videos on a TikTok creator's profile.
 * @summary Tiktok Channel Video Metrics
 * {@link /tiktok/channel-video-metrics}
 */
export async function getTiktokChannelVideoMetrics(
  { params }: { params?: GetTiktokChannelVideoMetricsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTiktokChannelVideoMetricsQueryResponse,
    ResponseErrorConfig<
      | GetTiktokChannelVideoMetrics400
      | GetTiktokChannelVideoMetrics403
      | GetTiktokChannelVideoMetrics404
      | GetTiktokChannelVideoMetrics500
    >,
    unknown
  >({
    method: "GET",
    url: getGetTiktokChannelVideoMetricsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
