/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetInstagramStats400,
  GetInstagramStats403,
  GetInstagramStats404,
  GetInstagramStats500,
  GetInstagramStatsQueryParams,
  GetInstagramStatsQueryResponse,
} from "../models/get-instagram-stats.ts";

function getGetInstagramStatsUrl() {
  const res = { method: "GET", url: `/instagram/stats` as const };
  return res;
}

/**
 * @description Get engagement metrics and metadata for an Instagram post or reel.
 * @summary Instagram Stats
 * {@link /instagram/stats}
 */
export async function getInstagramStats(
  { params }: { params?: GetInstagramStatsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetInstagramStatsQueryResponse,
    ResponseErrorConfig<
      | GetInstagramStats400
      | GetInstagramStats403
      | GetInstagramStats404
      | GetInstagramStats500
    >,
    unknown
  >({
    method: "GET",
    url: getGetInstagramStatsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
