/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetInstagramChannelReels400,
  GetInstagramChannelReels403,
  GetInstagramChannelReels404,
  GetInstagramChannelReels500,
  GetInstagramChannelReelsQueryParams,
  GetInstagramChannelReelsQueryResponse,
} from "../models/get-instagram-channel-reels.ts";

function getGetInstagramChannelReelsUrl() {
  const res = { method: "GET", url: `/instagram/channel-reels` as const };
  return res;
}

/**
 * @description Get recent reels from an Instagram profile's reels tab.
 * @summary Instagram Channel Reels
 * {@link /instagram/channel-reels}
 */
export async function getInstagramChannelReels(
  { params }: { params?: GetInstagramChannelReelsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetInstagramChannelReelsQueryResponse,
    ResponseErrorConfig<
      | GetInstagramChannelReels400
      | GetInstagramChannelReels403
      | GetInstagramChannelReels404
      | GetInstagramChannelReels500
    >,
    unknown
  >({
    method: "GET",
    url: getGetInstagramChannelReelsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
