/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetYoutubeComments400,
  GetYoutubeComments403,
  GetYoutubeComments404,
  GetYoutubeComments500,
  GetYoutubeCommentsQueryParams,
  GetYoutubeCommentsQueryResponse,
} from "../models/get-youtube-comments.ts";

function getGetYoutubeCommentsUrl() {
  const res = { method: "GET", url: `/youtube/comments` as const };
  return res;
}

/**
 * @description Fetch top comments from a YouTube video.
 * @summary Youtube Comments
 * {@link /youtube/comments}
 */
export async function getYoutubeComments(
  { params }: { params?: GetYoutubeCommentsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetYoutubeCommentsQueryResponse,
    ResponseErrorConfig<
      | GetYoutubeComments400
      | GetYoutubeComments403
      | GetYoutubeComments404
      | GetYoutubeComments500
    >,
    unknown
  >({
    method: "GET",
    url: getGetYoutubeCommentsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
