/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetTiktokChannelVideos400,
  GetTiktokChannelVideos403,
  GetTiktokChannelVideos404,
  GetTiktokChannelVideos500,
  GetTiktokChannelVideosQueryParams,
  GetTiktokChannelVideosQueryResponse,
} from "../models/get-tiktok-channel-videos.ts";

function getGetTiktokChannelVideosUrl() {
  const res = { method: "GET", url: `/tiktok/channel-videos` as const };
  return res;
}

/**
 * @description Get a list of recent videos from a TikTok creator's profile.
 * @summary Tiktok Channel Videos
 * {@link /tiktok/channel-videos}
 */
export async function getTiktokChannelVideos(
  { params }: { params?: GetTiktokChannelVideosQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTiktokChannelVideosQueryResponse,
    ResponseErrorConfig<
      | GetTiktokChannelVideos400
      | GetTiktokChannelVideos403
      | GetTiktokChannelVideos404
      | GetTiktokChannelVideos500
    >,
    unknown
  >({
    method: "GET",
    url: getGetTiktokChannelVideosUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
