/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetTiktokDownload400,
  GetTiktokDownload403,
  GetTiktokDownload404,
  GetTiktokDownload500,
  GetTiktokDownloadQueryParams,
  GetTiktokDownloadQueryResponse,
} from "../models/get-tiktok-download.ts";

function getGetTiktokDownloadUrl() {
  const res = { method: "GET", url: `/tiktok/download` as const };
  return res;
}

/**
 * @description Get a direct download URL for a TikTok video (watermark-free).
 * @summary Tiktok Download
 * {@link /tiktok/download}
 */
export async function getTiktokDownload(
  { params }: { params?: GetTiktokDownloadQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTiktokDownloadQueryResponse,
    ResponseErrorConfig<
      | GetTiktokDownload400
      | GetTiktokDownload403
      | GetTiktokDownload404
      | GetTiktokDownload500
    >,
    unknown
  >({
    method: "GET",
    url: getGetTiktokDownloadUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
