/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetTiktokStats400,
  GetTiktokStats403,
  GetTiktokStats404,
  GetTiktokStats500,
  GetTiktokStatsQueryParams,
  GetTiktokStatsQueryResponse,
} from "../models/get-tiktok-stats.ts";

function getGetTiktokStatsUrl() {
  const res = { method: "GET", url: `/tiktok/stats` as const };
  return res;
}

/**
 * @description Get engagement metrics and metadata for a TikTok video.
 * @summary Tiktok Stats
 * {@link /tiktok/stats}
 */
export async function getTiktokStats(
  { params }: { params?: GetTiktokStatsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTiktokStatsQueryResponse,
    ResponseErrorConfig<
      | GetTiktokStats400
      | GetTiktokStats403
      | GetTiktokStats404
      | GetTiktokStats500
    >,
    unknown
  >({
    method: "GET",
    url: getGetTiktokStatsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
