/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetYoutubeSummarize400,
  GetYoutubeSummarize403,
  GetYoutubeSummarize404,
  GetYoutubeSummarize500,
  GetYoutubeSummarizeQueryParams,
  GetYoutubeSummarizeQueryResponse,
} from "../models/get-youtube-summarize.ts";

function getGetYoutubeSummarizeUrl() {
  const res = { method: "GET", url: `/youtube/summarize` as const };
  return res;
}

/**
 * @description Summarize a YouTube video using AI. Returns a structured summary with key points.
 * @summary Youtube Summarize
 * {@link /youtube/summarize}
 */
export async function getYoutubeSummarize(
  { params }: { params?: GetYoutubeSummarizeQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetYoutubeSummarizeQueryResponse,
    ResponseErrorConfig<
      | GetYoutubeSummarize400
      | GetYoutubeSummarize403
      | GetYoutubeSummarize404
      | GetYoutubeSummarize500
    >,
    unknown
  >({
    method: "GET",
    url: getGetYoutubeSummarizeUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
