/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetInstagramDownload400,
  GetInstagramDownload403,
  GetInstagramDownload404,
  GetInstagramDownload500,
  GetInstagramDownloadQueryParams,
  GetInstagramDownloadQueryResponse,
} from "../models/get-instagram-download.ts";

function getGetInstagramDownloadUrl() {
  const res = { method: "GET", url: `/instagram/download` as const };
  return res;
}

/**
 * @description Get a direct download URL for an Instagram video or reel.
 * @summary Instagram Download
 * {@link /instagram/download}
 */
export async function getInstagramDownload(
  { params }: { params?: GetInstagramDownloadQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetInstagramDownloadQueryResponse,
    ResponseErrorConfig<
      | GetInstagramDownload400
      | GetInstagramDownload403
      | GetInstagramDownload404
      | GetInstagramDownload500
    >,
    unknown
  >({
    method: "GET",
    url: getGetInstagramDownloadUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
