/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetInstagramTranscript400,
  GetInstagramTranscript403,
  GetInstagramTranscript404,
  GetInstagramTranscript500,
  GetInstagramTranscriptQueryParams,
  GetInstagramTranscriptQueryResponse,
} from "../models/get-instagram-transcript.ts";

function getGetInstagramTranscriptUrl() {
  const res = { method: "GET", url: `/instagram/transcript` as const };
  return res;
}

/**
 * @description Extract the spoken transcript from an Instagram video or reel.
 * @summary Instagram Transcript
 * {@link /instagram/transcript}
 */
export async function getInstagramTranscript(
  { params }: { params?: GetInstagramTranscriptQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetInstagramTranscriptQueryResponse,
    ResponseErrorConfig<
      | GetInstagramTranscript400
      | GetInstagramTranscript403
      | GetInstagramTranscript404
      | GetInstagramTranscript500
    >,
    unknown
  >({
    method: "GET",
    url: getGetInstagramTranscriptUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
