/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  GetYoutubeChannelStats400,
  GetYoutubeChannelStats403,
  GetYoutubeChannelStats404,
  GetYoutubeChannelStats500,
  GetYoutubeChannelStatsQueryParams,
  GetYoutubeChannelStatsQueryResponse,
} from "../models/get-youtube-channel-stats.ts";

function getGetYoutubeChannelStatsUrl() {
  const res = { method: "GET", url: `/youtube/channel-stats` as const };
  return res;
}

/**
 * @description Get stats and metadata for a YouTube channel.
 * @summary Youtube Channel Stats
 * {@link /youtube/channel-stats}
 */
export async function getYoutubeChannelStats(
  { params }: { params?: GetYoutubeChannelStatsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetYoutubeChannelStatsQueryResponse,
    ResponseErrorConfig<
      | GetYoutubeChannelStats400
      | GetYoutubeChannelStats403
      | GetYoutubeChannelStats404
      | GetYoutubeChannelStats500
    >,
    unknown
  >({
    method: "GET",
    url: getGetYoutubeChannelStatsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
