/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokSearch400,
  PostTiktokSearch403,
  PostTiktokSearch404,
  PostTiktokSearch500,
  PostTiktokSearchMutationResponse,
  PostTiktokSearchQueryParams,
} from "../models/post-tiktok-search.ts";

function getPostTiktokSearchUrl() {
  const res = { method: "POST", url: `/tiktok/search` as const };
  return res;
}

/**
 * @description Search TikTok videos by keyword.
 * @summary Tiktok Search
 * {@link /tiktok/search}
 */
export async function postTiktokSearch(
  { params }: { params?: PostTiktokSearchQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostTiktokSearchMutationResponse,
    ResponseErrorConfig<
      | PostTiktokSearch400
      | PostTiktokSearch403
      | PostTiktokSearch404
      | PostTiktokSearch500
    >,
    unknown
  >({
    method: "POST",
    url: getPostTiktokSearchUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
