/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostYoutubeDownload400,
  PostYoutubeDownload403,
  PostYoutubeDownload404,
  PostYoutubeDownload500,
  PostYoutubeDownloadMutationResponse,
  PostYoutubeDownloadQueryParams,
} from "../models/post-youtube-download.ts";

function getPostYoutubeDownloadUrl() {
  const res = { method: "POST", url: `/youtube/download` as const };
  return res;
}

/**
 * @description Get a direct download URL for a YouTube video.
 * @summary Youtube Download
 * {@link /youtube/download}
 */
export async function postYoutubeDownload(
  { params }: { params?: PostYoutubeDownloadQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostYoutubeDownloadMutationResponse,
    ResponseErrorConfig<
      | PostYoutubeDownload400
      | PostYoutubeDownload403
      | PostYoutubeDownload404
      | PostYoutubeDownload500
    >,
    unknown
  >({
    method: "POST",
    url: getPostYoutubeDownloadUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
