/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostYoutubeVideos400,
  PostYoutubeVideos403,
  PostYoutubeVideos404,
  PostYoutubeVideos500,
  PostYoutubeVideosMutationResponse,
  PostYoutubeVideosQueryParams,
} from "../models/post-youtube-videos.ts";

function getPostYoutubeVideosUrl() {
  const res = { method: "POST", url: `/youtube/videos` as const };
  return res;
}

/**
 * @description Get a list of videos from a YouTube channel or playlist.
 * @summary Youtube Videos
 * {@link /youtube/videos}
 */
export async function postYoutubeVideos(
  { params }: { params?: PostYoutubeVideosQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostYoutubeVideosMutationResponse,
    ResponseErrorConfig<
      | PostYoutubeVideos400
      | PostYoutubeVideos403
      | PostYoutubeVideos404
      | PostYoutubeVideos500
    >,
    unknown
  >({
    method: "POST",
    url: getPostYoutubeVideosUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
