/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramTranscriptBulk400,
  PostInstagramTranscriptBulk403,
  PostInstagramTranscriptBulk404,
  PostInstagramTranscriptBulk500,
  PostInstagramTranscriptBulkMutationRequest,
  PostInstagramTranscriptBulkMutationResponse,
} from "../models/post-instagram-transcript-bulk.ts";

function getPostInstagramTranscriptBulkUrl() {
  const res = { method: "POST", url: `/instagram/transcript/bulk` as const };
  return res;
}

/**
 * @description Extract transcripts from multiple Instagram videos.
 * @summary Instagram Transcript Bulk
 * {@link /instagram/transcript/bulk}
 */
export async function postInstagramTranscriptBulk(
  { data }: { data: PostInstagramTranscriptBulkMutationRequest },
  config: Partial<RequestConfig<PostInstagramTranscriptBulkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostInstagramTranscriptBulkMutationResponse,
    ResponseErrorConfig<
      | PostInstagramTranscriptBulk400
      | PostInstagramTranscriptBulk403
      | PostInstagramTranscriptBulk404
      | PostInstagramTranscriptBulk500
    >,
    PostInstagramTranscriptBulkMutationRequest
  >({
    method: "POST",
    url: getPostInstagramTranscriptBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
