/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokChannelStatsBulk400,
  PostTiktokChannelStatsBulk403,
  PostTiktokChannelStatsBulk404,
  PostTiktokChannelStatsBulk500,
  PostTiktokChannelStatsBulkMutationRequest,
  PostTiktokChannelStatsBulkMutationResponse,
} from "../models/post-tiktok-channel-stats-bulk.ts";

function getPostTiktokChannelStatsBulkUrl() {
  const res = { method: "POST", url: `/tiktok/channel-stats/bulk` as const };
  return res;
}

/**
 * @description Get stats for multiple TikTok channels.
 * @summary Tiktok Channel Stats Bulk
 * {@link /tiktok/channel-stats/bulk}
 */
export async function postTiktokChannelStatsBulk(
  { data }: { data: PostTiktokChannelStatsBulkMutationRequest },
  config: Partial<RequestConfig<PostTiktokChannelStatsBulkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostTiktokChannelStatsBulkMutationResponse,
    ResponseErrorConfig<
      | PostTiktokChannelStatsBulk400
      | PostTiktokChannelStatsBulk403
      | PostTiktokChannelStatsBulk404
      | PostTiktokChannelStatsBulk500
    >,
    PostTiktokChannelStatsBulkMutationRequest
  >({
    method: "POST",
    url: getPostTiktokChannelStatsBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
