/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramComments400,
  PostInstagramComments403,
  PostInstagramComments404,
  PostInstagramComments500,
  PostInstagramCommentsMutationResponse,
  PostInstagramCommentsQueryParams,
} from "../models/post-instagram-comments.ts";

function getPostInstagramCommentsUrl() {
  const res = { method: "POST", url: `/instagram/comments` as const };
  return res;
}

/**
 * @description Fetch top comments from an Instagram post or reel.
 * @summary Instagram Comments
 * {@link /instagram/comments}
 */
export async function postInstagramComments(
  { params }: { params?: PostInstagramCommentsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostInstagramCommentsMutationResponse,
    ResponseErrorConfig<
      | PostInstagramComments400
      | PostInstagramComments403
      | PostInstagramComments404
      | PostInstagramComments500
    >,
    unknown
  >({
    method: "POST",
    url: getPostInstagramCommentsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
