/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokSummarizeBulk400,
  PostTiktokSummarizeBulk403,
  PostTiktokSummarizeBulk404,
  PostTiktokSummarizeBulk500,
  PostTiktokSummarizeBulkMutationRequest,
  PostTiktokSummarizeBulkMutationResponse,
} from "../models/post-tiktok-summarize-bulk.ts";

function getPostTiktokSummarizeBulkUrl() {
  const res = { method: "POST", url: `/tiktok/summarize/bulk` as const };
  return res;
}

/**
 * @description Summarize multiple TikTok videos.
 * @summary Tiktok Summarize Bulk
 * {@link /tiktok/summarize/bulk}
 */
export async function postTiktokSummarizeBulk(
  { data }: { data: PostTiktokSummarizeBulkMutationRequest },
  config: Partial<RequestConfig<PostTiktokSummarizeBulkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostTiktokSummarizeBulkMutationResponse,
    ResponseErrorConfig<
      | PostTiktokSummarizeBulk400
      | PostTiktokSummarizeBulk403
      | PostTiktokSummarizeBulk404
      | PostTiktokSummarizeBulk500
    >,
    PostTiktokSummarizeBulkMutationRequest
  >({
    method: "POST",
    url: getPostTiktokSummarizeBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
