/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokChannelVideoMetricsBulk400,
  PostTiktokChannelVideoMetricsBulk403,
  PostTiktokChannelVideoMetricsBulk404,
  PostTiktokChannelVideoMetricsBulk500,
  PostTiktokChannelVideoMetricsBulkMutationRequest,
  PostTiktokChannelVideoMetricsBulkMutationResponse,
} from "../models/post-tiktok-channel-video-metrics-bulk.ts";

function getPostTiktokChannelVideoMetricsBulkUrl() {
  const res = {
    method: "POST",
    url: `/tiktok/channel-video-metrics/bulk` as const,
  };
  return res;
}

/**
 * @description Get video metrics for multiple TikTok channels.
 * @summary Tiktok Channel Video Metrics Bulk
 * {@link /tiktok/channel-video-metrics/bulk}
 */
export async function postTiktokChannelVideoMetricsBulk(
  { data }: { data: PostTiktokChannelVideoMetricsBulkMutationRequest },
  config: Partial<
    RequestConfig<PostTiktokChannelVideoMetricsBulkMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostTiktokChannelVideoMetricsBulkMutationResponse,
    ResponseErrorConfig<
      | PostTiktokChannelVideoMetricsBulk400
      | PostTiktokChannelVideoMetricsBulk403
      | PostTiktokChannelVideoMetricsBulk404
      | PostTiktokChannelVideoMetricsBulk500
    >,
    PostTiktokChannelVideoMetricsBulkMutationRequest
  >({
    method: "POST",
    url: getPostTiktokChannelVideoMetricsBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
