/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostYoutubeCommentsBulk400,
  PostYoutubeCommentsBulk403,
  PostYoutubeCommentsBulk404,
  PostYoutubeCommentsBulk500,
  PostYoutubeCommentsBulkMutationRequest,
  PostYoutubeCommentsBulkMutationResponse,
} from "../models/post-youtube-comments-bulk.ts";

function getPostYoutubeCommentsBulkUrl() {
  const res = { method: "POST", url: `/youtube/comments/bulk` as const };
  return res;
}

/**
 * @description Fetch comments from multiple YouTube videos.
 * @summary Youtube Comments Bulk
 * {@link /youtube/comments/bulk}
 */
export async function postYoutubeCommentsBulk(
  { data }: { data: PostYoutubeCommentsBulkMutationRequest },
  config: Partial<RequestConfig<PostYoutubeCommentsBulkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostYoutubeCommentsBulkMutationResponse,
    ResponseErrorConfig<
      | PostYoutubeCommentsBulk400
      | PostYoutubeCommentsBulk403
      | PostYoutubeCommentsBulk404
      | PostYoutubeCommentsBulk500
    >,
    PostYoutubeCommentsBulkMutationRequest
  >({
    method: "POST",
    url: getPostYoutubeCommentsBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
