/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokComments400,
  PostTiktokComments403,
  PostTiktokComments404,
  PostTiktokComments500,
  PostTiktokCommentsMutationResponse,
  PostTiktokCommentsQueryParams,
} from "../models/post-tiktok-comments.ts";

function getPostTiktokCommentsUrl() {
  const res = { method: "POST", url: `/tiktok/comments` as const };
  return res;
}

/**
 * @description Fetch top comments from a TikTok video.
 * @summary Tiktok Comments
 * {@link /tiktok/comments}
 */
export async function postTiktokComments(
  { params }: { params?: PostTiktokCommentsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostTiktokCommentsMutationResponse,
    ResponseErrorConfig<
      | PostTiktokComments400
      | PostTiktokComments403
      | PostTiktokComments404
      | PostTiktokComments500
    >,
    unknown
  >({
    method: "POST",
    url: getPostTiktokCommentsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
