/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramStats400,
  PostInstagramStats403,
  PostInstagramStats404,
  PostInstagramStats500,
  PostInstagramStatsMutationResponse,
  PostInstagramStatsQueryParams,
} from "../models/post-instagram-stats.ts";

function getPostInstagramStatsUrl() {
  const res = { method: "POST", url: `/instagram/stats` as const };
  return res;
}

/**
 * @description Get engagement metrics and metadata for an Instagram post or reel.
 * @summary Instagram Stats
 * {@link /instagram/stats}
 */
export async function postInstagramStats(
  { params }: { params?: PostInstagramStatsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostInstagramStatsMutationResponse,
    ResponseErrorConfig<
      | PostInstagramStats400
      | PostInstagramStats403
      | PostInstagramStats404
      | PostInstagramStats500
    >,
    unknown
  >({
    method: "POST",
    url: getPostInstagramStatsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
