/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostVideoSummarize400,
  PostVideoSummarize403,
  PostVideoSummarize404,
  PostVideoSummarize500,
  PostVideoSummarizeMutationResponse,
  PostVideoSummarizeQueryParams,
} from "../models/post-video-summarize.ts";

function getPostVideoSummarizeUrl() {
  const res = { method: "POST", url: `/video/summarize` as const };
  return res;
}

/**
 * @description Summarize any publicly accessible video URL using AI.
 * @summary Video Summarize
 * {@link /video/summarize}
 */
export async function postVideoSummarize(
  { params }: { params?: PostVideoSummarizeQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostVideoSummarizeMutationResponse,
    ResponseErrorConfig<
      | PostVideoSummarize400
      | PostVideoSummarize403
      | PostVideoSummarize404
      | PostVideoSummarize500
    >,
    unknown
  >({
    method: "POST",
    url: getPostVideoSummarizeUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
