/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostYoutubeTranscript400,
  PostYoutubeTranscript403,
  PostYoutubeTranscript404,
  PostYoutubeTranscript500,
  PostYoutubeTranscriptMutationResponse,
  PostYoutubeTranscriptQueryParams,
} from "../models/post-youtube-transcript.ts";

function getPostYoutubeTranscriptUrl() {
  const res = { method: "POST", url: `/youtube/transcript` as const };
  return res;
}

/**
 * @description Extract the full transcript (with timestamps) from a YouTube video or Short.
 * @summary Youtube Transcript
 * {@link /youtube/transcript}
 */
export async function postYoutubeTranscript(
  { params }: { params?: PostYoutubeTranscriptQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostYoutubeTranscriptMutationResponse,
    ResponseErrorConfig<
      | PostYoutubeTranscript400
      | PostYoutubeTranscript403
      | PostYoutubeTranscript404
      | PostYoutubeTranscript500
    >,
    unknown
  >({
    method: "POST",
    url: getPostYoutubeTranscriptUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
