/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramDownload400,
  PostInstagramDownload403,
  PostInstagramDownload404,
  PostInstagramDownload500,
  PostInstagramDownloadMutationResponse,
  PostInstagramDownloadQueryParams,
} from "../models/post-instagram-download.ts";

function getPostInstagramDownloadUrl() {
  const res = { method: "POST", url: `/instagram/download` as const };
  return res;
}

/**
 * @description Get a direct download URL for an Instagram video or reel.
 * @summary Instagram Download
 * {@link /instagram/download}
 */
export async function postInstagramDownload(
  { params }: { params?: PostInstagramDownloadQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostInstagramDownloadMutationResponse,
    ResponseErrorConfig<
      | PostInstagramDownload400
      | PostInstagramDownload403
      | PostInstagramDownload404
      | PostInstagramDownload500
    >,
    unknown
  >({
    method: "POST",
    url: getPostInstagramDownloadUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
