/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokDownload400,
  PostTiktokDownload403,
  PostTiktokDownload404,
  PostTiktokDownload500,
  PostTiktokDownloadMutationResponse,
  PostTiktokDownloadQueryParams,
} from "../models/post-tiktok-download.ts";

function getPostTiktokDownloadUrl() {
  const res = { method: "POST", url: `/tiktok/download` as const };
  return res;
}

/**
 * @description Get a direct download URL for a TikTok video (watermark-free).
 * @summary Tiktok Download
 * {@link /tiktok/download}
 */
export async function postTiktokDownload(
  { params }: { params?: PostTiktokDownloadQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostTiktokDownloadMutationResponse,
    ResponseErrorConfig<
      | PostTiktokDownload400
      | PostTiktokDownload403
      | PostTiktokDownload404
      | PostTiktokDownload500
    >,
    unknown
  >({
    method: "POST",
    url: getPostTiktokDownloadUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
