/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramChannelStatsBulk400,
  PostInstagramChannelStatsBulk403,
  PostInstagramChannelStatsBulk404,
  PostInstagramChannelStatsBulk500,
  PostInstagramChannelStatsBulkMutationRequest,
  PostInstagramChannelStatsBulkMutationResponse,
} from "../models/post-instagram-channel-stats-bulk.ts";

function getPostInstagramChannelStatsBulkUrl() {
  const res = { method: "POST", url: `/instagram/channel-stats/bulk` as const };
  return res;
}

/**
 * @description Get stats for multiple Instagram profiles.
 * @summary Instagram Channel Stats Bulk
 * {@link /instagram/channel-stats/bulk}
 */
export async function postInstagramChannelStatsBulk(
  { data }: { data: PostInstagramChannelStatsBulkMutationRequest },
  config: Partial<
    RequestConfig<PostInstagramChannelStatsBulkMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostInstagramChannelStatsBulkMutationResponse,
    ResponseErrorConfig<
      | PostInstagramChannelStatsBulk400
      | PostInstagramChannelStatsBulk403
      | PostInstagramChannelStatsBulk404
      | PostInstagramChannelStatsBulk500
    >,
    PostInstagramChannelStatsBulkMutationRequest
  >({
    method: "POST",
    url: getPostInstagramChannelStatsBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
