/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramChannelPosts400,
  PostInstagramChannelPosts403,
  PostInstagramChannelPosts404,
  PostInstagramChannelPosts500,
  PostInstagramChannelPostsMutationResponse,
  PostInstagramChannelPostsQueryParams,
} from "../models/post-instagram-channel-posts.ts";

function getPostInstagramChannelPostsUrl() {
  const res = { method: "POST", url: `/instagram/channel-posts` as const };
  return res;
}

/**
 * @description Get recent posts from an Instagram profile's feed.
 * @summary Instagram Channel Posts
 * {@link /instagram/channel-posts}
 */
export async function postInstagramChannelPosts(
  { params }: { params?: PostInstagramChannelPostsQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostInstagramChannelPostsMutationResponse,
    ResponseErrorConfig<
      | PostInstagramChannelPosts400
      | PostInstagramChannelPosts403
      | PostInstagramChannelPosts404
      | PostInstagramChannelPosts500
    >,
    unknown
  >({
    method: "POST",
    url: getPostInstagramChannelPostsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
