/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostTiktokSummarize400,
  PostTiktokSummarize403,
  PostTiktokSummarize404,
  PostTiktokSummarize500,
  PostTiktokSummarizeMutationResponse,
  PostTiktokSummarizeQueryParams,
} from "../models/post-tiktok-summarize.ts";

function getPostTiktokSummarizeUrl() {
  const res = { method: "POST", url: `/tiktok/summarize` as const };
  return res;
}

/**
 * @description Summarize a TikTok video using AI.
 * @summary Tiktok Summarize
 * {@link /tiktok/summarize}
 */
export async function postTiktokSummarize(
  { params }: { params?: PostTiktokSummarizeQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostTiktokSummarizeMutationResponse,
    ResponseErrorConfig<
      | PostTiktokSummarize400
      | PostTiktokSummarize403
      | PostTiktokSummarize404
      | PostTiktokSummarize500
    >,
    unknown
  >({
    method: "POST",
    url: getPostTiktokSummarizeUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
