/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostInstagramStatsBulk400,
  PostInstagramStatsBulk403,
  PostInstagramStatsBulk404,
  PostInstagramStatsBulk500,
  PostInstagramStatsBulkMutationRequest,
  PostInstagramStatsBulkMutationResponse,
} from "../models/post-instagram-stats-bulk.ts";

function getPostInstagramStatsBulkUrl() {
  const res = { method: "POST", url: `/instagram/stats/bulk` as const };
  return res;
}

/**
 * @description Get stats for multiple Instagram posts.
 * @summary Instagram Stats Bulk
 * {@link /instagram/stats/bulk}
 */
export async function postInstagramStatsBulk(
  { data }: { data: PostInstagramStatsBulkMutationRequest },
  config: Partial<RequestConfig<PostInstagramStatsBulkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostInstagramStatsBulkMutationResponse,
    ResponseErrorConfig<
      | PostInstagramStatsBulk400
      | PostInstagramStatsBulk403
      | PostInstagramStatsBulk404
      | PostInstagramStatsBulk500
    >,
    PostInstagramStatsBulkMutationRequest
  >({
    method: "POST",
    url: getPostInstagramStatsBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
