/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/socialkit/client";
import fetch from "@/lib/socialkit/client";

import type {
  PostYoutubeSummarizeBulk400,
  PostYoutubeSummarizeBulk403,
  PostYoutubeSummarizeBulk404,
  PostYoutubeSummarizeBulk500,
  PostYoutubeSummarizeBulkMutationRequest,
  PostYoutubeSummarizeBulkMutationResponse,
} from "../models/post-youtube-summarize-bulk.ts";

function getPostYoutubeSummarizeBulkUrl() {
  const res = { method: "POST", url: `/youtube/summarize/bulk` as const };
  return res;
}

/**
 * @description Summarize multiple YouTube videos.
 * @summary Youtube Summarize Bulk
 * {@link /youtube/summarize/bulk}
 */
export async function postYoutubeSummarizeBulk(
  { data }: { data: PostYoutubeSummarizeBulkMutationRequest },
  config: Partial<RequestConfig<PostYoutubeSummarizeBulkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostYoutubeSummarizeBulkMutationResponse,
    ResponseErrorConfig<
      | PostYoutubeSummarizeBulk400
      | PostYoutubeSummarizeBulk403
      | PostYoutubeSummarizeBulk404
      | PostYoutubeSummarizeBulk500
    >,
    PostYoutubeSummarizeBulkMutationRequest
  >({
    method: "POST",
    url: getPostYoutubeSummarizeBulkUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
