/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AirlineLeg } from "./airline-leg.ts";
import type { AirlinePassenger } from "./airline-passenger.ts";

/**
 * @description Объект с данными для продажи авиабилетов: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/airline-tickets. Используется только для платежей банковской картой.
 */
export type Airline = {
  /**
   * @description Unique ticket number. If you already know the ticket number during payment creation, ticket_number is a required parameter. If you don\'t, specify booking_reference instead of ticket_number.
   * @minLength 1
   * @maxLength 150
   * @pattern [0-9]{1,150}
   * @type string | undefined
   */
  ticket_number?: string;
  /**
   * @description Booking reference number, required if ticket_number is not specified.
   * @minLength 1
   * @maxLength 20
   * @type string | undefined
   */
  booking_reference?: string;
  /**
   * @description List of passengers.
   * @type array | undefined
   */
  passengers?: AirlinePassenger[];
  /**
   * @description List of flight legs.
   * @type array | undefined
   */
  legs?: AirlineLeg[];
};
