/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Банковские реквизиты плательщика (юридического лица или ИП).
 */
export type B2BSberbankPayerBankDetails = {
  /**
   * @description Полное наименование организации.
   * @maxLength 800
   * @type string
   */
  full_name: string;
  /**
   * @description Сокращенное наименование организации.
   * @maxLength 160
   * @type string
   */
  short_name: string;
  /**
   * @description Адрес организации.
   * @maxLength 500
   * @type string
   */
  address: string;
  /**
   * @description Индивидуальный налоговый номер (ИНН) организации.
   * @pattern \d{10}|\d{12}
   * @type string
   */
  inn: string;
  /**
   * @description Наименование банка организации.
   * @minLength 1
   * @maxLength 350
   * @type string
   */
  bank_name: string;
  /**
   * @description Отделение банка организации.
   * @minLength 1
   * @maxLength 140
   * @type string
   */
  bank_branch: string;
  /**
   * @description Банковский идентификационный код (БИК) банка организации.
   * @pattern \d{9}
   * @type string
   */
  bank_bik: string;
  /**
   * @description Номер счета организации.
   * @pattern \d{20}
   * @type string
   */
  account: string;
  /**
   * @description Код причины постановки на учет (КПП) организации.
   * @pattern \d{9}
   * @type string | undefined
   */
  kpp?: string;
};
