/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const B2BSberbankVatDataTypeEnum = {
  calculated: "calculated",
  untaxed: "untaxed",
  mixed: "mixed",
} as const;

export type B2BSberbankVatDataTypeEnumKey =
  (typeof B2BSberbankVatDataTypeEnum)[keyof typeof B2BSberbankVatDataTypeEnum];

/**
 * @description Тип способа расчета НДС.
 * @example calculated
 */
export type B2BSberbankVatDataType = B2BSberbankVatDataTypeEnumKey;
