/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./error.ts";

export const badRequestCodeEnum = {
  invalid_request: "invalid_request",
} as const;

export type BadRequestCodeEnumKey =
  (typeof badRequestCodeEnum)[keyof typeof badRequestCodeEnum];

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export type BadRequest = Error & {
  /**
   * @description Код ошибки
   * @type string | undefined
   */
  code?: BadRequestCodeEnumKey;
};
