/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BankCardDataSource } from "./bank-card-data-source.ts";
import type { BankCardExpiryMonth } from "./bank-card-expiry-month.ts";
import type { BankCardExpiryYear } from "./bank-card-expiry-year.ts";
import type { BankCardFirst6 } from "./bank-card-first6.ts";
import type { BankCardIssuerCountry } from "./bank-card-issuer-country.ts";
import type { BankCardIssuerName } from "./bank-card-issuer-name.ts";
import type { BankCardLast4 } from "./bank-card-last4.ts";
import type { BankCardProduct } from "./bank-card-product.ts";
import type { BankCardType } from "./bank-card-type.ts";

/**
 * @description Данные банковской карты.
 */
export type BankCardData = {
  /**
   * @description Первые 6 цифр номера карты (BIN). При оплате картой, сохраненной в ЮKassa: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/basics и других сервисах, переданный BIN может не соответствовать значениям last4, expiry_year, expiry_month.
   * @pattern [0-9]{6}
   * @type string | undefined
   */
  first6?: BankCardFirst6;
  /**
   * @description Последние 4 цифры номера карты.
   * @pattern [0-9]{4}
   * @type string
   */
  last4: BankCardLast4;
  /**
   * @description Срок действия, год, YYYY.
   * @pattern [0-9]{4}
   * @type string
   */
  expiry_year: BankCardExpiryYear;
  /**
   * @description Срок действия, месяц, MM.
   * @type string
   */
  expiry_month: BankCardExpiryMonth;
  /**
   * @description Тип банковской карты. Возможные значения: MasterCard (для карт Mastercard и Maestro), Visa (для карт Visa и Visa Electron), Mir, UnionPay, JCB, AmericanExpress, DinersClub, DiscoverCard, InstaPayment, InstaPaymentTM, Laser, Dankort, Solo, Switch и Unknown.
   * @type string
   */
  card_type: BankCardType;
  /**
   * @description Карточный продукт платежной системы, с которым ассоциирована банковская карта. Например, карточные продукты платежной системы Мир: Mir Classic, Mir Classic Credit, MIR Privilege Plus и другие.
   * @type object | undefined
   */
  card_product?: BankCardProduct;
  /**
   * @description Код страны, в которой выпущена карта. Передается в формате ISO-3166 alpha-2: https://www.iso.org/obp/ui/#iso:pub:PUB500001:en. Пример: RU.
   * @type string | undefined
   */
  issuer_country?: BankCardIssuerCountry;
  /**
   * @description Наименование банка, выпустившего карту.
   * @type string | undefined
   */
  issuer_name?: BankCardIssuerName;
  /**
   * @description Источник данных банковской карты. Возможные значения: mir_pay, apple_pay, google_pay. Присутствует, если пользователь при оплате выбрал карту, сохраненную в Mir Pay, Apple Pay или Google Pay.
   * @type string | undefined
   */
  source?: BankCardDataSource;
};
