/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Срок действия, год, YYYY.
 * @pattern [0-9]{4}
 * @example 2017
 */
export type BankCardExpiryYear = string;
