/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Имя владельца карты.
 * @pattern [a-zA-Z '-]{0,26}
 * @example John Smith
 */
export type BankCardHolderName = string;
