/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const bankCardTypeEnum = {
  MasterCard: "MasterCard",
  Visa: "Visa",
  Mir: "Mir",
  UnionPay: "UnionPay",
  JCB: "JCB",
  AmericanExpress: "AmericanExpress",
  DinersClub: "DinersClub",
  DiscoverCard: "DiscoverCard",
  InstaPayment: "InstaPayment",
  InstaPaymentTM: "InstaPaymentTM",
  Laser: "Laser",
  Dankort: "Dankort",
  Solo: "Solo",
  Switch: "Switch",
  Unknown: "Unknown",
} as const;

export type BankCardTypeEnumKey =
  (typeof bankCardTypeEnum)[keyof typeof bankCardTypeEnum];

/**
 * @description Тип банковской карты. Возможные значения: MasterCard (для карт Mastercard и Maestro), Visa (для карт Visa и Visa Electron), Mir, UnionPay, JCB, AmericanExpress, DinersClub, DiscoverCard, InstaPayment, InstaPaymentTM, Laser, Dankort, Solo, Switch и Unknown.
 */
export type BankCardType = BankCardTypeEnumKey;
