/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BankCardHolderName } from "./bank-card-holder-name.ts";

/**
 * @description Данные банковской карты (необходимы, если вы собираете данные карты пользователей на своей стороне).
 */
export type CardRequestData = {
  /**
   * @description Номер банковской карты.
   * @pattern [0-9]{14,19}
   * @type string
   */
  number: string;
  /**
   * @description Срок действия, год, YYYY.
   * @pattern [0-9]{4}
   * @type string
   */
  expiry_year: string;
  /**
   * @description Срок действия, месяц, MM.
   * @pattern [0-9]{2}
   * @type string
   */
  expiry_month: string;
  /**
   * @description Имя владельца карты.
   * @pattern [a-zA-Z '-]{0,26}
   * @type string | undefined
   */
  cardholder?: BankCardHolderName;
};
