/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConfirmationData } from "./confirmation-data.ts";

export const confirmationDataEmbeddedTypeEnum = {
  embedded: "embedded",
} as const;

export type ConfirmationDataEmbeddedTypeEnumKey =
  (typeof confirmationDataEmbeddedTypeEnum)[keyof typeof confirmationDataEmbeddedTypeEnum];

export type ConfirmationDataEmbedded = (ConfirmationData & {
  type: "embedded";
}) & {
  type: ConfirmationDataEmbeddedTypeEnumKey;
};
