/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Confirmation } from "./confirmation.ts";

export const confirmationEmbeddedTypeEnum = {
  embedded: "embedded",
} as const;

export type ConfirmationEmbeddedTypeEnumKey =
  (typeof confirmationEmbeddedTypeEnum)[keyof typeof confirmationEmbeddedTypeEnum];

export type ConfirmationEmbedded = (Confirmation & {
  type: "embedded";
}) & {
  /**
   * @description Токен для инициализации платежного виджета ЮKassa: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/widget/basics.
   * @type string
   */
  confirmation_token: string;
  type: ConfirmationEmbeddedTypeEnumKey;
};
