/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Confirmation } from "./confirmation.ts";
import type { ConfirmationUrl } from "./confirmation-url.ts";
import type { Enforce } from "./enforce.ts";
import type { ReturnUrl } from "./return-url.ts";

export const confirmationRedirectTypeEnum = {
  redirect: "redirect",
} as const;

export type ConfirmationRedirectTypeEnumKey =
  (typeof confirmationRedirectTypeEnum)[keyof typeof confirmationRedirectTypeEnum];

export type ConfirmationRedirect = (Confirmation & {
  type: "redirect";
}) & {
  /**
   * @description Запрос на проведение платежа с аутентификацией по 3-D Secure. Будет работать, если оплату банковской картой вы по умолчанию принимаете без подтверждения платежа пользователем. В остальных случаях аутентификацией по 3-D Secure будет управлять ЮKassa. Если хотите принимать платежи без дополнительного подтверждения пользователем, напишите вашему менеджеру ЮKassa.
   * @type boolean | undefined
   */
  enforce?: Enforce;
  /**
   * @description URL, на который вернется пользователь после подтверждения или отмены платежа на веб-странице. Не более 2048 символов.
   * @type string | undefined
   */
  return_url?: ReturnUrl;
  /**
   * @description URL, на который необходимо перенаправить пользователя для подтверждения оплаты.
   * @type string
   */
  confirmation_url: ConfirmationUrl;
  type: ConfirmationRedirectTypeEnumKey;
};
