/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConfirmationData } from "./confirmation-data.ts";
import type { ReturnUrl } from "./return-url.ts";

export const confirmationDataMobileApplicationTypeEnum = {
  mobile_application: "mobile_application",
} as const;

export type ConfirmationDataMobileApplicationTypeEnumKey =
  (typeof confirmationDataMobileApplicationTypeEnum)[keyof typeof confirmationDataMobileApplicationTypeEnum];

export type ConfirmationDataMobileApplication = (ConfirmationData & {
  type: "mobile_application";
}) & {
  /**
   * @description URL, на который вернется пользователь после подтверждения или отмены платежа на веб-странице. Не более 2048 символов.
   * @type string
   */
  return_url: ReturnUrl;
  type: ConfirmationDataMobileApplicationTypeEnumKey;
};
