/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Confirmation } from "./confirmation.ts";

export const confirmationQrTypeEnum = {
  qr: "qr",
} as const;

export type ConfirmationQrTypeEnumKey =
  (typeof confirmationQrTypeEnum)[keyof typeof confirmationQrTypeEnum];

export type ConfirmationQr = (Confirmation & {
  type: "qr";
}) & {
  /**
   * @description Данные для генерации QR-кода.
   * @type string
   */
  confirmation_data: string;
  type: ConfirmationQrTypeEnumKey;
};
