/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BasketId } from "./basket-id.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";

/**
 * @description Данные от ФЭС НСПК для возврата на электронный сертификат.
 */
export type ElectronicCertificateRefundDataResponse = {
  /**
   * @description Идентификатор корзины, сформированной в НСПК.
   * @pattern [0-9]{24}
   * @type string
   */
  basket_id: BasketId;
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  amount: MonetaryAmount;
};
