/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ElectronicCertificateRefundArticle } from "./electronic-certificate-refund-article.ts";
import type { ElectronicCertificateRefundDataResponse } from "./electronic-certificate-refund-data-response.ts";
import type { RefundMethod } from "./refund-method.ts";

export const electronicCertificateRefundMethodTypeEnum = {
  electronic_certificate: "electronic_certificate",
} as const;

export type ElectronicCertificateRefundMethodTypeEnumKey =
  (typeof electronicCertificateRefundMethodTypeEnum)[keyof typeof electronicCertificateRefundMethodTypeEnum];

/**
 * @description Возврат платежа по электронному сертификату.
 */
export type ElectronicCertificateRefundMethod = (RefundMethod & {
  type: "electronic_certificate";
}) & {
  /**
   * @description Данные от ФЭС НСПК для возврата на электронный сертификат.
   * @type object | undefined
   */
  electronic_certificate?: ElectronicCertificateRefundDataResponse;
  /**
   * @description Корзина возврата — список возвращаемых товаров, для оплаты которых использовался электронный сертификат. Присутствует, если оплата была на готовой странице ЮKassa: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/ready-made-payment-form.
   * @type array | undefined
   */
  articles?: ElectronicCertificateRefundArticle[];
  type: ElectronicCertificateRefundMethodTypeEnumKey;
};
