/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BasketId } from "./basket-id.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";

/**
 * @description Данные от ФЭС НСПК для оплаты по электронному сертификату.
 */
export type ElectronicCertificatePayment = {
  amount: MonetaryAmount & any;
  basket_id: BasketId & string & any;
};
