/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BasketId } from "./basket-id.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";

/**
 * @description Данные от ФЭС НСПК для возврата на электронный сертификат. Неоходимо передавать только при оплате со сбором данных на вашей стороне: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/merchant-payment-form.
 */
export type ElectronicCertificateRefundDataRequest = {
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  amount: MonetaryAmount;
  /**
   * @description Идентификатор корзины, сформированной в НСПК.
   * @pattern [0-9]{24}
   * @type string
   */
  basket_id: BasketId;
};
