/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MonetaryAmount } from "./monetary-amount.ts";

/**
 * @description Описание используемого электронного сертификата.
 */
export type ElectronicCertificate = {
  /**
   * @description Идентификатор сертификата. От 20 до 30 символов.
   * @minLength 20
   * @maxLength 30
   * @type string
   */
  certificate_id: string;
  /**
   * @description Количество единиц товара, которое одобрили для оплаты по этому электронному сертификату.
   * @type integer
   */
  tru_quantity: number;
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  available_compensation: MonetaryAmount;
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  applied_compensation: MonetaryAmount;
};
