/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Количество единиц товара. Формат: целое положительное число.
 * @example 4
 */
export type ElectronicCertificateArticleQuantity = number;
