/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Код товара в вашей системе. Максимум 128 символов.
 * @maxLength 128
 * @example 432
 */
export type ElectronicCertificateArticleCode = string;
