/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Порядковый номер товара в корзине. От 1 до 999 включительно.
 * @example 1
 */
export type ElectronicCertificateArticleNumber = number;
