/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./error.ts";

export const forbiddenCodeEnum = {
  forbidden: "forbidden",
} as const;

export type ForbiddenCodeEnumKey =
  (typeof forbiddenCodeEnum)[keyof typeof forbiddenCodeEnum];

/**
 * @description Секретный ключ указан верно, но не хватает прав для совершения операции.
 */
export type Forbidden = Error & {
  /**
   * @description Код ошибки.
   * @type string | undefined
   */
  code?: ForbiddenCodeEnumKey;
};
