/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Идентификатор субаккаунта. Используется для разделения потоков платежей в рамках одного аккаунта.
 * @example 456
 */
export type GatewayId = string;
