/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./error.ts";

export const invalidCredentialsCodeEnum = {
  invalid_credentials: "invalid_credentials",
} as const;

export type InvalidCredentialsCodeEnumKey =
  (typeof invalidCredentialsCodeEnum)[keyof typeof invalidCredentialsCodeEnum];

/**
 * @description В заголовке Authorization указан неверный ключ.
 */
export type InvalidCredentials = Error & {
  /**
   * @description Код ошибки
   * @type string | undefined
   */
  code?: InvalidCredentialsCodeEnumKey;
};
