/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Invoice ID in YooMoney.
 * @minLength 39
 * @maxLength 39
 * @example in-e44e8088-bd73-43b1-959a-954f3a7d0c54
 */
export type InvoiceId = string;
