/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Код бюджетной классификации (КБК).
 * @minLength 1
 * @maxLength 20
 * @pattern ([\d]{20})|(0)
 * @example 70311105013130000120
 */
export type Kbk = string;
