/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Идентификатор покупателя в вашей системе, например электронная почта или номер телефона. Не более 200 символов.
 * @maxLength 200
 * @example user@test.merchant
 */
export type MerchantCustomerId = string;
