/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CurrencyCode } from "./currency-code.ts";

/**
 * @description Сумма в выбранной валюте.
 */
export type MonetaryAmount = {
  /**
   * @description Сумма в выбранной валюте. Всегда дробное значение. Разделитель дробной части — точка, разделитель тысяч отсутствует. Количество знаков после точки зависит от выбранной валюты. Пример: 1000.00.
   * @type string
   */
  value: string;
  /**
   * @description Трехбуквенный код валюты в формате ISO-4217: https://www.iso.org/iso-4217-currency-codes.html. Пример: RUB. Должен соответствовать валюте субаккаунта (recipient.gateway_id), если вы разделяете потоки платежей, и валюте аккаунта (shopId в личном кабинете: https://yookassa.ru/my), если не разделяете.
   * @type string
   */
  currency: CurrencyCode;
};
