/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Указатель на следующий фрагмент списка. Обязательный параметр, если размер списка больше размера выдачи (limit) и конец выдачи не достигнут.
 * @example 37a5c87d-3984-51e8-a7f3-8de646d39ec15
 */
export type NextCursor = string;
