/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Код ОКТМО (Общероссийский классификатор территорий муниципальных образований).
 * @minLength 1
 * @maxLength 8
 * @pattern ([\d]{8})|(0)
 * @example 98627153
 */
export type Oktmo = string;
