/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentMethodsConfirmationTypeEnum = {
  redirect: "redirect",
} as const;

export type PaymentMethodsConfirmationTypeEnumKey =
  (typeof paymentMethodsConfirmationTypeEnum)[keyof typeof paymentMethodsConfirmationTypeEnum];

/**
 * @description Код сценария подтверждения пользователем привязки платежного средства к вашему магазину в ЮKassa.
 * @example redirect
 */
export type PaymentMethodsConfirmationType =
  PaymentMethodsConfirmationTypeEnumKey;
