/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentCancellationDetailsPartyEnum = {
  yoo_money: "yoo_money",
  payment_network: "payment_network",
  merchant: "merchant",
} as const;

export type PaymentCancellationDetailsPartyEnumKey =
  (typeof paymentCancellationDetailsPartyEnum)[keyof typeof paymentCancellationDetailsPartyEnum];

export const paymentCancellationDetailsReasonEnum = {
  "3d_secure_failed": "3d_secure_failed",
  "call_issuer": "call_issuer",
  "card_expired": "card_expired",
  "payment_method_limit_exceeded": "payment_method_limit_exceeded",
  "payment_method_restricted": "payment_method_restricted",
  "country_forbidden": "country_forbidden",
  "general_decline": "general_decline",
  "fraud_suspected": "fraud_suspected",
  "identification_required": "identification_required",
  "insufficient_funds": "insufficient_funds",
  "invalid_card_number": "invalid_card_number",
  "invalid_csc": "invalid_csc",
  "issuer_unavailable": "issuer_unavailable",
  "canceled_by_merchant": "canceled_by_merchant",
  "permission_revoked": "permission_revoked",
  "internal_timeout": "internal_timeout",
  "expired_on_confirmation": "expired_on_confirmation",
  "expired_on_capture": "expired_on_capture",
  "unsupported_mobile_operator": "unsupported_mobile_operator",
  "deal_expired": "deal_expired",
} as const;

export type PaymentCancellationDetailsReasonEnumKey =
  (typeof paymentCancellationDetailsReasonEnum)[keyof typeof paymentCancellationDetailsReasonEnum];

/**
 * @description Commentary to the canceled status: who and why canceled the payment. More about canceled payments: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments
 */
export type PaymentCancellationDetails = {
  /**
   * @description The participant of the payment process that made the decision to cancel the payment. Possible values are yoo_money, payment_network, and merchant. More about initiators of payment cancelation: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments#cancellation-details-party
   * @type string
   */
  party: PaymentCancellationDetailsPartyEnumKey;
  /**
   * @description Reason behind the cancelation. The list and descriptions of possible values: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments#cancellation-details-reason
   * @type string
   */
  reason: PaymentCancellationDetailsReasonEnumKey;
};
