/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodApplePayTypeEnum = {
  apple_pay: "apple_pay",
} as const;

export type PaymentMethodApplePayTypeEnumKey =
  (typeof paymentMethodApplePayTypeEnum)[keyof typeof paymentMethodApplePayTypeEnum];

/**
 * @description Оплата через Apple Pay.
 */
export type PaymentMethodApplePay = (PaymentMethod & {
  type: "apple_pay";
}) & {
  type: PaymentMethodApplePayTypeEnumKey;
};
