/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodGooglePayTypeEnum = {
  google_pay: "google_pay",
} as const;

export type PaymentMethodGooglePayTypeEnumKey =
  (typeof paymentMethodGooglePayTypeEnum)[keyof typeof paymentMethodGooglePayTypeEnum];

/**
 * @description Оплата через Google Pay.
 */
export type PaymentMethodGooglePay = (PaymentMethod & {
  type: "google_pay";
}) & {
  type: PaymentMethodGooglePayTypeEnumKey;
};
