/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodCashTypeEnum = {
  cash: "cash",
} as const;

export type PaymentMethodCashTypeEnumKey =
  (typeof paymentMethodCashTypeEnum)[keyof typeof paymentMethodCashTypeEnum];

/**
 * @description Payments in cash via payment kiosks.
 */
export type PaymentMethodCash = (PaymentMethod & {
  type: "cash";
}) & {
  type: PaymentMethodCashTypeEnumKey;
};
