/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentStatusEnum = {
  pending: "pending",
  waiting_for_capture: "waiting_for_capture",
  succeeded: "succeeded",
  canceled: "canceled",
} as const;

export type PaymentStatusEnumKey =
  (typeof paymentStatusEnum)[keyof typeof paymentStatusEnum];

/**
 * @description Payment status. Possible values: pending, waiting_for_capture, succeeded, and canceled. More about the life cycle of a payment: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-process#lifecycle
 * @example succeeded
 */
export type PaymentStatus = PaymentStatusEnumKey;
