/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";
import type { SbpPayerBankDetails } from "./sbp-payer-bank-details.ts";

export const paymentMethodSbpTypeEnum = {
  sbp: "sbp",
} as const;

export type PaymentMethodSbpTypeEnumKey =
  (typeof paymentMethodSbpTypeEnum)[keyof typeof paymentMethodSbpTypeEnum];

/**
 * @description Оплата через СБП (Система быстрых платежей ЦБ РФ).
 */
export type PaymentMethodSbp = (PaymentMethod & {
  type: "sbp";
}) & {
  /**
   * @description Идентификатор операции в СБП (НСПК). Пример: 1027088AE4CB48CB81287833347A8777 Обязательный параметр для платежей в статусе succeeded. В остальных случаях может отсутствовать.
   * @type string | undefined
   */
  sbp_operation_id?: string;
  /**
   * @description Реквизиты счета, который использовался для оплаты. Обязательный параметр для платежей в статусе succeeded. В остальных случаях может отсутствовать.
   * @type object | undefined
   */
  payer_bank_details?: SbpPayerBankDetails;
  type: PaymentMethodSbpTypeEnumKey;
};
