/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Email } from "./email.ts";
import type { PaymentOverviewStatementDeliveryMethod } from "./payment-overview-statement-delivery-method.ts";

export const paymentOverviewStatementEmailDeliveryMethodTypeEnum = {
  email: "email",
} as const;

export type PaymentOverviewStatementEmailDeliveryMethodTypeEnumKey =
  (typeof paymentOverviewStatementEmailDeliveryMethodTypeEnum)[keyof typeof paymentOverviewStatementEmailDeliveryMethodTypeEnum];

/**
 * @description Cпособ доставки справки.
 */
export type PaymentOverviewStatementEmailDeliveryMethod =
  (PaymentOverviewStatementDeliveryMethod & {
    type: "email";
  }) & {
    /**
     * @description Адрес электронной почты RFC 5322
     * @type string, email
     */
    email: Email;
    type: PaymentOverviewStatementEmailDeliveryMethodTypeEnumKey;
  };
