/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethodData } from "./payment-method-data.ts";

export const paymentMethodDataSberLoanTypeEnum = {
  sber_loan: "sber_loan",
} as const;

export type PaymentMethodDataSberLoanTypeEnumKey =
  (typeof paymentMethodDataSberLoanTypeEnum)[keyof typeof paymentMethodDataSberLoanTypeEnum];

/**
 * @description Данные для оплаты в кредит или рассрочку от СберБанка.
 */
export type PaymentMethodDataSberLoan = (PaymentMethodData & {
  type: "sber_loan";
}) & {
  type: PaymentMethodDataSberLoanTypeEnumKey;
};
