/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BankCardData } from "./bank-card-data.ts";
import type { ElectronicCertificateApprovedPaymentArticle } from "./electronic-certificate-approved-payment-article.ts";
import type { ElectronicCertificatePayment } from "./electronic-certificate-payment.ts";
import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodElectronicCertificateTypeEnum = {
  electronic_certificate: "electronic_certificate",
} as const;

export type PaymentMethodElectronicCertificateTypeEnumKey =
  (typeof paymentMethodElectronicCertificateTypeEnum)[keyof typeof paymentMethodElectronicCertificateTypeEnum];

/**
 * @description Оплата по электронному сертификату.
 */
export type PaymentMethodElectronicCertificate = (PaymentMethod & {
  type: "electronic_certificate";
}) & {
  /**
   * @description Данные банковской карты.
   * @type object | undefined
   */
  card?: BankCardData;
  /**
   * @description Данные от ФЭС НСПК для оплаты по электронному сертификату.
   * @type object | undefined
   */
  electronic_certificate?: ElectronicCertificatePayment;
  /**
   * @description Одобренная корзина покупки — список товаров, одобренных к оплате по электронному сертификату. Присутствует только при оплате на готовой странице ЮKassa: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/ready-made-payment-form.
   * @type array | undefined
   */
  articles?: ElectronicCertificateApprovedPaymentArticle[];
  type: PaymentMethodElectronicCertificateTypeEnumKey;
};
