/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Saved payment method: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/basics\'s ID.
 * @example 1da5c87d-0984-50e8-a7f3-8de646dd9ec9
 */
export type PaymentMethodId = string;
