/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Kbk } from "./kbk.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";
import type { Oktmo } from "./oktmo.ts";
import type { PaymentOrderData } from "./payment-order-data.ts";
import type { PaymentOrderRecipientUtilities } from "./payment-order-recipient-utilities.ts";
import type { PaymentPeriod } from "./payment-period.ts";
import type { PaymentPurpose } from "./payment-purpose.ts";

export const paymentOrderDataUtilitiesTypeEnum = {
  utilities: "utilities",
} as const;

export type PaymentOrderDataUtilitiesTypeEnumKey =
  (typeof paymentOrderDataUtilitiesTypeEnum)[keyof typeof paymentOrderDataUtilitiesTypeEnum];

/**
 * @description Платежное поручение — распоряжение на перевод банку для оплаты жилищно-коммунальных услуг (ЖКУ), сведения о платеже для регистрации в ГИС ЖКХ. Необходимо передавать при оплате ЖКУ: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/utility-payments. Кроме параметров, отмеченных как обязательные, должен быть передан как минимум один параметр из этого списка: payment_document_id, payment_document_number, account_number, unified_account_number или service_id.
 */
export type PaymentOrderDataUtilities = (PaymentOrderData & {
  type: "utilities";
}) & {
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  amount: MonetaryAmount;
  /**
   * @description Назначение платежа (не больше 210 символов).
   * @pattern [\s\S].{1,210}
   * @type string
   */
  payment_purpose: PaymentPurpose;
  /**
   * @description Получатель платежа
   * @type object
   */
  recipient: PaymentOrderRecipientUtilities;
  /**
   * @description Код бюджетной классификации (КБК).
   * @pattern ([\d]{20})|(0)
   * @type string | undefined
   */
  kbk?: Kbk;
  /**
   * @description Код ОКТМО (Общероссийский классификатор территорий муниципальных образований).
   * @pattern ([\d]{8})|(0)
   * @type string | undefined
   */
  oktmo?: Oktmo;
  /**
   * @description Период оплаты, за который выставлены начисления и за который вносится оплата.
   * @type object | undefined
   */
  payment_period?: PaymentPeriod;
  /**
   * @description Идентификатор платежного документа. Обязательный параметр, если не передан payment_document_number, account_number, unified_account_number или service_id.
   * @minLength 18
   * @maxLength 18
   * @type string | undefined
   */
  payment_document_id?: string;
  /**
   * @description Номер платежного документа на стороне поставщика ЖКУ. Обязательный параметр, если не передан payment_document_id, account_number, unified_account_number или service_id.
   * @minLength 1
   * @maxLength 30
   * @pattern (.)([0-9а-яА-Яa-zA-Z]+)(.)
   * @type string | undefined
   */
  payment_document_number?: string;
  /**
   * @description Номер лицевого счета на стороне поставщика ЖКУ. Обязательный параметр, если не передан payment_document_id, payment_document_number, unified_account_number или service_id.
   * @minLength 1
   * @maxLength 30
   * @pattern (.)([0-9а-яА-Яa-zA-Z]+)(.)
   * @type string | undefined
   */
  account_number?: string;
  /**
   * @description Единый лицевой счет. Уникальный идентификатор в ГИС ЖКХ, который характеризует связку «собственник-помещение». Обязательный параметр, если не передан payment_document_id, payment_document_number, account_number или service_id.
   * @minLength 10
   * @maxLength 10
   * @type string | undefined
   */
  unified_account_number?: string;
  /**
   * @description Идентификатор жилищно-коммунальной услуги (ЖКУ). Обязательный параметр, если не передан payment_document_id, payment_document_number, account_number или unified_account_number.
   * @minLength 13
   * @maxLength 13
   * @type string | undefined
   */
  service_id?: string;
  type: PaymentOrderDataUtilitiesTypeEnumKey;
};
