/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Период оплаты, за который выставлены начисления и за который вносится оплата.
 */
export type PaymentPeriod = {
  /**
   * @description Месяц периода. Например, 1 — январь.
   * @minLength 1
   * @maxLength 12
   * @type integer
   */
  month: number;
  /**
   * @description Payment period year. The value must be within the range 1920–2050. For example, 2025.
   * @minLength 1920
   * @maxLength 2050
   * @type integer
   */
  year: number;
};
