/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodInstallmentsTypeEnum = {
  installments: "installments",
} as const;

export type PaymentMethodInstallmentsTypeEnumKey =
  (typeof paymentMethodInstallmentsTypeEnum)[keyof typeof paymentMethodInstallmentsTypeEnum];

/**
 * @description Оплата через сервис «Заплатить по частям» (в кредит или рассрочку).
 */
export type PaymentMethodInstallments = (PaymentMethod & {
  type: "installments";
}) & {
  type: PaymentMethodInstallmentsTypeEnumKey;
};
