/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description One-time payment token generated with Checkout.js: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/checkout-js/basics or mobile SDK: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/mobile-sdks/basics.
 * @example +u7PDjMTkf08NtD66P6+eYWa2yjU3gsSIhOOO+OWsOg=
 */
export type PaymentToken = string;
