/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethodStatus } from "./payment-method-status.ts";
import type { PaymentMethodTitle } from "./payment-method-title.ts";
import type { PaymentMethodType } from "./payment-method-type.ts";

/**
 * @description Payment method: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-methods#all used for this payment.
 */
export type PaymentMethod = {
  /**
   * @description Payment method code is the type of a means of payment used for paying. More about payment methods: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-methods
   * @type string
   */
  type: PaymentMethodType;
  /**
   * @description Payment method ID.
   * @type string
   */
  id: string;
  /**
   * @description Признак сохранения способа оплаты для автоплатежей: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/pay-with-saved. Возможные значения: * true — способ оплаты сохранен для автоплатежей и выплат; * false — способ оплаты не сохранен.
   * @type boolean
   */
  saved: boolean;
  status: PaymentMethodStatus & any;
  /**
   * @description Название способа оплаты.
   * @type string | undefined
   */
  title?: PaymentMethodTitle;
};
