/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentOrderBankUtilities } from "./payment-order-bank-utilities.ts";

/**
 * @description Получатель платежа
 */
export type PaymentOrderRecipientUtilities = {
  /**
   * @description Название получателя.
   * @type string
   */
  name: string;
  /**
   * @description ИНН получателя.
   * @pattern [0-9]{10}
   * @type string
   */
  inn: string;
  /**
   * @description КПП получателя.
   * @pattern [0-9]{9}
   * @type string
   */
  kpp: string;
  /**
   * @description Банк получателя платежа.
   * @type object
   */
  bank: PaymentOrderBankUtilities;
};
