/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethodData } from "./payment-method-data.ts";

export const paymentMethodDataTinkoffBankTypeEnum = {
  tinkoff_bank: "tinkoff_bank",
} as const;

export type PaymentMethodDataTinkoffBankTypeEnumKey =
  (typeof paymentMethodDataTinkoffBankTypeEnum)[keyof typeof paymentMethodDataTinkoffBankTypeEnum];

/**
 * @description Данные для оплаты через T-Pay.
 */
export type PaymentMethodDataTinkoffBank = (PaymentMethodData & {
  type: "tinkoff_bank";
}) & {
  type: PaymentMethodDataTinkoffBankTypeEnumKey;
};
