/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InvoicingBankCardData } from "./invoicing-bank-card-data.ts";
import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodTinkoffBankTypeEnum = {
  tinkoff_bank: "tinkoff_bank",
} as const;

export type PaymentMethodTinkoffBankTypeEnumKey =
  (typeof paymentMethodTinkoffBankTypeEnum)[keyof typeof paymentMethodTinkoffBankTypeEnum];

/**
 * @description Оплата через T-Pay.
 */
export type PaymentMethodTinkoffBank = (PaymentMethod & {
  type: "tinkoff_bank";
}) & {
  /**
   * @description Данные банковской карты.
   * @type object | undefined
   */
  card?: InvoicingBankCardData;
  type: PaymentMethodTinkoffBankTypeEnumKey;
};
