/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardRequestDataWithCsc } from "./card-request-data-with-csc.ts";
import type { PaymentMethodData } from "./payment-method-data.ts";

export const paymentMethodDataBankCardTypeEnum = {
  bank_card: "bank_card",
} as const;

export type PaymentMethodDataBankCardTypeEnumKey =
  (typeof paymentMethodDataBankCardTypeEnum)[keyof typeof paymentMethodDataBankCardTypeEnum];

/**
 * @description Данные для оплаты банковской картой.
 */
export type PaymentMethodDataBankCard = (PaymentMethodData & {
  type: "bank_card";
}) & {
  /**
   * @type object | undefined
   */
  card?: CardRequestDataWithCsc;
  type: PaymentMethodDataBankCardTypeEnumKey;
};
