/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardRequestData } from "./card-request-data.ts";
import type { ElectronicCertificateArticle } from "./electronic-certificate-article.ts";
import type { ElectronicCertificatePaymentData } from "./electronic-certificate-payment-data.ts";
import type { PaymentMethodData } from "./payment-method-data.ts";

export const paymentMethodDataElectronicCertificateTypeEnum = {
  electronic_certificate: "electronic_certificate",
} as const;

export type PaymentMethodDataElectronicCertificateTypeEnumKey =
  (typeof paymentMethodDataElectronicCertificateTypeEnum)[keyof typeof paymentMethodDataElectronicCertificateTypeEnum];

/**
 * @description Данные для оплаты по электронному сертификату.
 */
export type PaymentMethodDataElectronicCertificate = (PaymentMethodData & {
  type: "electronic_certificate";
}) & {
  /**
   * @description Данные банковской карты (необходимы, если вы собираете данные карты пользователей на своей стороне).
   * @type object | undefined
   */
  card?: CardRequestData;
  /**
   * @description Данные от ФЭС НСПК для оплаты по электронному сертификату. Неоходимо передавать только при оплате со сбором данных на вашей стороне: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/merchant-payment-form.
   * @type object | undefined
   */
  electronic_certificate?: ElectronicCertificatePaymentData;
  /**
   * @description Корзина покупки (в терминах НСПК) — список товаров, которые можно оплатить по сертификату. Необходимо передавать только при оплате на готовой странице ЮKassa: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/ready-made-payment-form.
   * @type array | undefined
   */
  articles?: ElectronicCertificateArticle[];
  type: PaymentMethodDataElectronicCertificateTypeEnumKey;
};
