/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodSberBnplTypeEnum = {
  sber_bnpl: "sber_bnpl",
} as const;

export type PaymentMethodSberBnplTypeEnumKey =
  (typeof paymentMethodSberBnplTypeEnum)[keyof typeof paymentMethodSberBnplTypeEnum];

/**
 * @description Оплата через сервис «Плати частями».
 */
export type PaymentMethodSberBnpl = (PaymentMethod & {
  type: "sber_bnpl";
}) & {
  type: PaymentMethodSberBnplTypeEnumKey;
};
