/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentMethodTypeEnum = {
  bank_card: "bank_card",
  cash: "cash",
  alfabank: "alfabank",
  webmoney: "webmoney",
  wechat: "wechat",
  apple_pay: "apple_pay",
  google_pay: "google_pay",
  qiwi: "qiwi",
  installments: "installments",
  yoo_money: "yoo_money",
  sberbank: "sberbank",
  mobile_balance: "mobile_balance",
  b2b_sberbank: "b2b_sberbank",
  tinkoff_bank: "tinkoff_bank",
  sbp: "sbp",
  sber_loan: "sber_loan",
  electronic_certificate: "electronic_certificate",
  sber_bnpl: "sber_bnpl",
} as const;

export type PaymentMethodTypeEnumKey =
  (typeof paymentMethodTypeEnum)[keyof typeof paymentMethodTypeEnum];

/**
 * @description Payment method code is the type of a means of payment used for paying. More about payment methods: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-methods
 * @example bank_card
 */
export type PaymentMethodType = PaymentMethodTypeEnumKey;
