/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BankCardData } from "./bank-card-data.ts";
import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodBankCardTypeEnum = {
  bank_card: "bank_card",
} as const;

export type PaymentMethodBankCardTypeEnumKey =
  (typeof paymentMethodBankCardTypeEnum)[keyof typeof paymentMethodBankCardTypeEnum];

/**
 * @description Оплата банковской картой.
 */
export type PaymentMethodBankCard = (PaymentMethod & {
  type: "bank_card";
}) & {
  /**
   * @description Данные банковской карты.
   * @type object | undefined
   */
  card?: BankCardData;
  type: PaymentMethodBankCardTypeEnumKey;
};
