/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodMobileBalanceTypeEnum = {
  mobile_balance: "mobile_balance",
} as const;

export type PaymentMethodMobileBalanceTypeEnumKey =
  (typeof paymentMethodMobileBalanceTypeEnum)[keyof typeof paymentMethodMobileBalanceTypeEnum];

/**
 * @description Оплата с баланса мобильного телефона.
 */
export type PaymentMethodMobileBalance = (PaymentMethod & {
  type: "mobile_balance";
}) & {
  type: PaymentMethodMobileBalanceTypeEnumKey;
};
