/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethodData } from "./payment-method-data.ts";

export const paymentMethodDataYooMoneyTypeEnum = {
  yoo_money: "yoo_money",
} as const;

export type PaymentMethodDataYooMoneyTypeEnumKey =
  (typeof paymentMethodDataYooMoneyTypeEnum)[keyof typeof paymentMethodDataYooMoneyTypeEnum];

/**
 * @description Data for processing a payment made via the YooMoney wallet.
 */
export type PaymentMethodDataYooMoney = (PaymentMethodData & {
  type: "yoo_money";
}) & {
  type: PaymentMethodDataYooMoneyTypeEnumKey;
};
