/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaymentMethod } from "./payment-method.ts";

export const paymentMethodAlfabankTypeEnum = {
  alfabank: "alfabank",
} as const;

export type PaymentMethodAlfabankTypeEnumKey =
  (typeof paymentMethodAlfabankTypeEnum)[keyof typeof paymentMethodAlfabankTypeEnum];

/**
 * @description Оплата через Альфа-Клик.
 */
export type PaymentMethodAlfabank = (PaymentMethod & {
  type: "alfabank";
}) & {
  /**
   * @description Логин пользователя в Альфа-Клике (привязанный телефон или дополнительный логин).
   * @type string | undefined
   */
  login?: string;
  type: PaymentMethodAlfabankTypeEnumKey;
};
