/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "./bad-request.ts";
import type { ElectronicCertificateRefundMethodData } from "./electronic-certificate-refund-method-data.ts";
import type { Forbidden } from "./forbidden.ts";
import type { InvalidCredentials } from "./invalid-credentials.ts";
import type { Metadata } from "./metadata.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";
import type { PaymentId } from "./payment-id.ts";
import type { ReceiptData } from "./receipt-data.ts";
import type { Refund } from "./refund.ts";
import type { RefundDealData } from "./refund-deal-data.ts";
import type { RefundSourcesData } from "./refund-sources-data.ts";
import type { TooManyRequests } from "./too-many-requests.ts";

export type PostRefundsHeaderParams = {
  /**
   * @maxLength 64
   * @pattern [0-9a-zA-Z+-_.]{1,64}
   * @default "2e1da982-1bb1-41f0-b9cf-758cc8bcf069"
   * @type string
   */
  "Idempotence-Key": string;
};

/**
 * @description Запрос успешно обработан
 */
export type PostRefunds200 = Refund;

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export type PostRefunds400 = BadRequest;

/**
 * @description В заголовке Authorization указан неверный ключ.
 */
export type PostRefunds401 = InvalidCredentials;

/**
 * @description Секретный ключ указан верно, но не хватает прав для совершения операции.
 */
export type PostRefunds403 = Forbidden;

/**
 * @description Внутренняя ошибка сервера ЮKassa.
 */
export type PostRefunds500 = TooManyRequests;

/**
 * RefundRequest
 */
export type PostRefundsMutationRequest = {
  /**
   * @description Идентификатор платежа в ЮKassa.
   * @type string
   */
  payment_id: PaymentId;
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  amount: MonetaryAmount;
  /**
   * @description Комментарий к возврату, основание для возврата денег пользователю.
   * @maxLength 250
   * @type string | undefined
   */
  description?: string;
  /**
   * @description Data for creating a receipt. The parameter is specified if: you are a company or a sole proprietor, and you use Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/basics; you are a company or a sole proprietor, and you use the third-party sales register: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics and send data for creating receipts under one of the following scenarios: Payment and receipt at the same time: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics#payment-and-receipt or Payment after receipt: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics#payment-after-receipt.
   * @type object | undefined
   */
  receipt?: ReceiptData;
  /**
   * @description Данные о том, с какого магазина и какую сумму нужно удержать для проведения возврата. Необходимо передавать, если вы используете Сплитование платежей: https://yookassa.ru/developers/solutions-for-platforms/split-payments/basics. Сейчас в этом параметре можно передать данные только одного магазина.
   * @type array | undefined
   */
  sources?: RefundSourcesData[];
  /**
   * @description Данные о сделке, в составе которой проходит возврат. Необходимо передавать, если вы проводите Безопасную сделку: https://yookassa.ru/developers/solutions-for-platforms/safe-deal/basics.
   * @type object | undefined
   */
  deal?: RefundDealData;
  refund_method_data?: ElectronicCertificateRefundMethodData;
  /**
   * @description Любые дополнительные данные, которые нужны вам для работы (например, ваш внутренний идентификатор заказа). Передаются в виде набора пар «ключ-значение» и возвращаются в ответе от ЮKassa. Ограничения: максимум 16 ключей, имя ключа не больше 32 символов, значение ключа не больше 512 символов, тип данных — строка в формате UTF-8.
   * @type object | undefined
   */
  metadata?: Metadata;
};

export type PostRefundsMutationResponse = PostRefunds200;

export type PostRefundsMutation = {
  Response: PostRefunds200;
  Request: PostRefundsMutationRequest;
  HeaderParams: PostRefundsHeaderParams;
  Errors: PostRefunds400 | PostRefunds401 | PostRefunds403 | PostRefunds500;
};
