/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "./bad-request.ts";
import type { Forbidden } from "./forbidden.ts";
import type { InvalidCredentials } from "./invalid-credentials.ts";
import type { Payment } from "./payment.ts";
import type { PaymentId } from "./payment-id.ts";
import type { TooManyRequests } from "./too-many-requests.ts";

export type PostPaymentsPaymentIdCancelPathParams = {
  /**
   * @description Идентификатор платежа в ЮKassa.
   * @type string
   */
  payment_id: PaymentId;
};

export type PostPaymentsPaymentIdCancelHeaderParams = {
  /**
   * @maxLength 64
   * @pattern [0-9a-zA-Z+-_.]{1,64}
   * @default "2e1da982-1bb1-41f0-b9cf-758cc8bcf069"
   * @type string
   */
  "Idempotence-Key": string;
};

/**
 * @description Запрос успешно обработан
 */
export type PostPaymentsPaymentIdCancel200 = Payment;

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export type PostPaymentsPaymentIdCancel400 = BadRequest;

/**
 * @description В заголовке Authorization указан неверный ключ.
 */
export type PostPaymentsPaymentIdCancel401 = InvalidCredentials;

/**
 * @description Секретный ключ указан верно, но не хватает прав для совершения операции.
 */
export type PostPaymentsPaymentIdCancel403 = Forbidden;

/**
 * @description Внутренняя ошибка сервера ЮKassa.
 */
export type PostPaymentsPaymentIdCancel500 = TooManyRequests;

export type PostPaymentsPaymentIdCancelMutationResponse =
  PostPaymentsPaymentIdCancel200;

export type PostPaymentsPaymentIdCancelMutation = {
  Response: PostPaymentsPaymentIdCancel200;
  PathParams: PostPaymentsPaymentIdCancelPathParams;
  HeaderParams: PostPaymentsPaymentIdCancelHeaderParams;
  Errors:
    | PostPaymentsPaymentIdCancel400
    | PostPaymentsPaymentIdCancel401
    | PostPaymentsPaymentIdCancel403
    | PostPaymentsPaymentIdCancel500;
};
