/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IndustryDetails } from "./industry-details.ts";

/**
 * @description Отраслевой реквизит предмета расчета (тег в 54 ФЗ — 1260). Можно передавать, если используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2.
 */
export type ReceiptItemPaymentSubjectIndustryDetails = IndustryDetails[];
