/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const receiverTypeEnum = {
  mobile_balance: "mobile_balance",
  digital_wallet: "digital_wallet",
  bank_account: "bank_account",
} as const;

export type ReceiverTypeEnumKey =
  (typeof receiverTypeEnum)[keyof typeof receiverTypeEnum];

/**
 * @description Payment receiver code.
 * @example mobile_balance
 */
export type ReceiverType = ReceiverTypeEnumKey;
