/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Product quantity (tag 1023 in 54-FZ). You can set an integer or a decimal value. The decimal separator is a dot; there is no thousands separator. The maximum possible value and the maximum number of digits after the decimal separator (for decimal values) depend on the model of your online sales register. For Receipts from YooMoney, the maximum possible value is 99999.999, with no more than 3 digits after the decimal separator.
 * @example 1
 */
export type ReceiptItemQuantity = number;
