/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const receiptItemMeasureEnum = {
  piece: "piece",
  gram: "gram",
  kilogram: "kilogram",
  ton: "ton",
  centimeter: "centimeter",
  decimeter: "decimeter",
  meter: "meter",
  square_centimeter: "square_centimeter",
  square_decimeter: "square_decimeter",
  square_meter: "square_meter",
  milliliter: "milliliter",
  liter: "liter",
  cubic_meter: "cubic_meter",
  kilowatt_hour: "kilowatt_hour",
  gigacalorie: "gigacalorie",
  day: "day",
  hour: "hour",
  minute: "minute",
  second: "second",
  kilobyte: "kilobyte",
  megabyte: "megabyte",
  gigabyte: "gigabyte",
  terabyte: "terabyte",
  another: "another",
} as const;

export type ReceiptItemMeasureEnumKey =
  (typeof receiptItemMeasureEnum)[keyof typeof receiptItemMeasureEnum];

/**
 * @description Мера количества предмета расчета (тег в 54 ФЗ — 2108) — единица измерения товара, например штуки, граммы. Обязательный параметр, если используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2. Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#measure * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#measure
 * @example piece
 */
export type ReceiptItemMeasure = ReceiptItemMeasureEnumKey;
