/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Receiver } from "./receiver.ts";

export const receiverBankAccountTypeEnum = {
  bank_account: "bank_account",
} as const;

export type ReceiverBankAccountTypeEnumKey =
  (typeof receiverBankAccountTypeEnum)[keyof typeof receiverBankAccountTypeEnum];

/**
 * @description Реквизиты для пополнения банковского счета.
 */
export type ReceiverBankAccount = (Receiver & {
  type: "bank_account";
}) & {
  /**
   * @description Номер банковского счета. Формат — 20 символов.
   * @maxLength 20
   * @pattern \d{20}
   * @type string
   */
  account_number: string;
  /**
   * @description Банковский идентификационный код (БИК) банка, в котором открыт счет. Формат — 9 символов.
   * @maxLength 9
   * @pattern \d{9}
   * @type string
   */
  bic: string;
  type: ReceiverBankAccountTypeEnumKey;
};
