/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReceiverType } from "./receiver-type.ts";

/**
 * @description Payment receiver\'s details specified when you want to add money to e-wallet, bank account, or phone balance: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/receiver-data.
 */
export type Receiver = {
  /**
   * @description Payment receiver code.
   * @type string
   */
  type: ReceiverType;
};
