/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Номер таможенной декларации (от 1 до 32 символов). Тег в 54 ФЗ — 1231. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.
 * @minLength 1
 * @maxLength 32
 * @example 10714040/140917/0090376
 */
export type ReceiptItemCustomsDeclarationNumber = string;
