/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const receiptRegistrationStatusEnum = {
  pending: "pending",
  succeeded: "succeeded",
  canceled: "canceled",
} as const;

export type ReceiptRegistrationStatusEnumKey =
  (typeof receiptRegistrationStatusEnum)[keyof typeof receiptRegistrationStatusEnum];

/**
 * @example succeeded
 */
export type ReceiptRegistrationStatus = ReceiptRegistrationStatusEnumKey;
