/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ElectronicCertificateRefundMethod } from "./electronic-certificate-refund-method.ts";
import type { Metadata } from "./metadata.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";
import type { PaymentId } from "./payment-id.ts";
import type { ReceiptRegistrationStatus } from "./receipt-registration-status.ts";
import type { RefundAuthorizationDetails } from "./refund-authorization-details.ts";
import type { RefundCancellationDetails } from "./refund-cancellation-details.ts";
import type { RefundDealInfo } from "./refund-deal-info.ts";
import type { RefundId } from "./refund-id.ts";
import type { RefundSourcesData } from "./refund-sources-data.ts";
import type { RefundStatus } from "./refund-status.ts";
import type { SbpRefundMethod } from "./sbp-refund-method.ts";

/**
 * @description Refund object (Refund) contains all the relevant information about the payment refund.
 */
export type Refund = {
  /**
   * @description Идентификатор возврата платежа в ЮKassa.
   * @type string
   */
  id: RefundId;
  /**
   * @description Идентификатор платежа в ЮKassa.
   * @type string
   */
  payment_id: PaymentId;
  /**
   * @description Статус возврата платежа. Возможные значения: pending — возврат создан, но пока еще обрабатывается; succeeded — возврат успешно завершен, указанная в запросе сумма переведена на платежное средство пользователя (финальный и неизменяемый статус); canceled — возврат отменен, инициатор и причина отмены указаны в объекте cancellation_details (финальный и неизменяемый статус).
   * @type string
   */
  status: RefundStatus;
  /**
   * @description Комментарий к статусу canceled: кто отменил возврат и по какой причине.
   * @type object | undefined
   */
  cancellation_details?: RefundCancellationDetails;
  /**
   * @description Статус регистрации чека. Возможные значения: pending — данные в обработке; succeeded — чек успешно зарегистрирован; canceled — чек зарегистрировать не удалось; если используете Чеки от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/basics, обратитесь в техническую поддержку, в остальных случаях сформируйте чек вручную. Присутствует, если вы используете решения ЮKassa для отправки чеков в налоговую: https://yookassa.ru/developers/payment-acceptance/receipts/basics.
   * @type string | undefined
   */
  receipt_registration?: ReceiptRegistrationStatus;
  /**
   * @description Время создания возврата. Указывается по UTC: https://ru.wikipedia.org/wiki/%D0%92%D1%81%D0%B5%D0%BC%D0%B8%D1%80%D0%BD%D0%BE%D0%B5_%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5_%D0%B2%D1%80%D0%B5%D0%BC%D1%8F и передается в формате ISO 8601: https://en.wikipedia.org/wiki/ISO_8601, например 2017-11-03T11:52:31.827Z
   * @type string, date-time
   */
  created_at: string;
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  amount: MonetaryAmount;
  /**
   * @description Основание для возврата денег пользователю.
   * @maxLength 250
   * @type string | undefined
   */
  description?: string;
  /**
   * @description Данные о том, с какого магазина и какую сумму нужно удержать для проведения возврата. Присутствует, если вы используете Сплитование платежей: https://yookassa.ru/developers/solutions-for-platforms/split-payments/basics.
   * @type array | undefined
   */
  sources?: RefundSourcesData[];
  /**
   * @description Данные о сделке, в составе которой проходит возврат. Присутствует, если вы проводите Безопасную сделку: https://yookassa.ru/developers/solutions-for-platforms/safe-deal/basics.
   * @type object | undefined
   */
  deal?: RefundDealInfo;
  refund_method?: SbpRefundMethod | ElectronicCertificateRefundMethod;
  /**
   * @description Refund authorization details. Presented only for refunds made by these payment methods: bank card, Mir Pay.
   * @type object | undefined
   */
  refund_authorization_details?: RefundAuthorizationDetails;
  /**
   * @description Любые дополнительные данные, которые нужны вам для работы (например, ваш внутренний идентификатор заказа). Передаются в виде набора пар «ключ-значение» и возвращаются в ответе от ЮKassa. Ограничения: максимум 16 ключей, имя ключа не больше 32 символов, значение ключа не больше 512 символов, тип данных — строка в формате UTF-8.
   * @type object | undefined
   */
  metadata?: Metadata;
};
