/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RefundMethodType } from "./refund-method-type.ts";

/**
 * @description Детали возврата. Зависят от способа оплаты, который использовался при проведении платежа.
 */
export type RefundMethodData = {
  /**
   * @description Код способа оплаты, который использовался при проведении платежа.
   * @type string
   */
  type: RefundMethodType;
};
