/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SettlementRefundArray } from "./settlement-refund-array.ts";

/**
 * @description Данные о сделке, в составе которой проходит возврат. Необходимо передавать, если вы проводите Безопасную сделку: https://yookassa.ru/developers/solutions-for-platforms/safe-deal/basics.
 */
export type RefundDealData = {
  /**
   * @description Данные о распределении денег.
   * @type array
   */
  refund_settlements: SettlementRefundArray;
};
