/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const refundMethodTypeEnum = {
  sbp: "sbp",
  electronic_certificate: "electronic_certificate",
} as const;

export type RefundMethodTypeEnumKey =
  (typeof refundMethodTypeEnum)[keyof typeof refundMethodTypeEnum];

/**
 * @description Код способа оплаты, который использовался при проведении платежа.
 * @example sbp
 */
export type RefundMethodType = RefundMethodTypeEnumKey;
