/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DealId } from "./deal-id.ts";
import type { SettlementRefundArray } from "./settlement-refund-array.ts";

/**
 * @description Данные о сделке, в составе которой проходит возврат. Присутствует, если вы проводите Безопасную сделку: https://yookassa.ru/developers/solutions-for-platforms/safe-deal/basics.
 */
export type RefundDealInfo = {
  /**
   * @description Идентификатор сделки.
   * @type string
   */
  id: DealId;
  /**
   * @description Данные о распределении денег.
   * @type array
   */
  refund_settlements: SettlementRefundArray;
};
