/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const refundStatusEnum = {
  pending: "pending",
  succeeded: "succeeded",
  canceled: "canceled",
} as const;

export type RefundStatusEnumKey =
  (typeof refundStatusEnum)[keyof typeof refundStatusEnum];

/**
 * @description Статус возврата платежа. Возможные значения: pending — возврат создан, но пока еще обрабатывается; succeeded — возврат успешно завершен, указанная в запросе сумма переведена на платежное средство пользователя (финальный и неизменяемый статус); canceled — возврат отменен, инициатор и причина отмены указаны в объекте cancellation_details (финальный и неизменяемый статус).
 * @example succeeded
 */
export type RefundStatus = RefundStatusEnumKey;
