/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Retrieval Reference Number is a identifier of a bank transaction.
 * @example 603668680243
 */
export type Rrn = string;
