/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description ИНН пользователя (10 или 12 цифр).
 * @pattern \d{10}|\d{12}
 * @example 6321341814
 */
export type RussianItn = string;
