/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardRequestData } from "./card-request-data.ts";
import type { SavePaymentMethodData } from "./save-payment-method-data.ts";

export const savePaymentMethodDataBankCardTypeEnum = {
  bank_card: "bank_card",
} as const;

export type SavePaymentMethodDataBankCardTypeEnumKey =
  (typeof savePaymentMethodDataBankCardTypeEnum)[keyof typeof savePaymentMethodDataBankCardTypeEnum];

/**
 * @description Данные для проверки и сохранения банковской карты.
 */
export type SavePaymentMethodDataBankCard = (SavePaymentMethodData & {
  type: "bank_card";
}) & {
  /**
   * @description Данные банковской карты (необходимы, если вы собираете данные карты пользователей на своей стороне).
   * @type object | undefined
   */
  card?: CardRequestData;
  type: SavePaymentMethodDataBankCardTypeEnumKey;
};
