/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AccountId } from "./account-id.ts";
import type { GatewayId } from "./gateway-id.ts";
import type { PaymentMethodStatus } from "./payment-method-status.ts";
import type { PaymentMethodTitle } from "./payment-method-title.ts";
import type { PaymentMethodsConfirmationRedirect } from "./payment-methods-confirmation-redirect.ts";
import type { SavePaymentMethodType } from "./save-payment-method-type.ts";

/**
 * @description Сохраненный способ оплаты.
 */
export type SavePaymentMethod = {
  /**
   * @description Тип способа оплаты.
   * @type string
   */
  type: SavePaymentMethodType;
  /**
   * @description Идентификатор сохраненного способа оплаты.
   * @type string
   */
  id: string;
  /**
   * @description Признак сохранения способа оплаты для автоплатежей: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/pay-with-saved. Возможные значения: * true — способ оплаты сохранен для автоплатежей и выплат; * false — способ оплаты не сохранен.
   * @type boolean
   */
  saved: boolean;
  /**
   * @description Статус проверки и сохранения способа оплаты. Возможные значения: * pending — ожидает действий от пользователя; * active — способ оплаты сохранен, его можно использовать для автоплатежей или выплат; * inactive — способ оплаты не сохранен: пользователь не подтвердил привязку платежного средства или при сохранении способа оплаты возникла ошибка. Чтобы узнать подробности, обратитесь в техническую поддержку ЮKassa.
   * @type string
   */
  status: PaymentMethodStatus;
  /**
   * @description Данные магазина, для которого сохраняется способ оплаты.
   * @type object
   */
  holder: {
    /**
     * @description Идентификатор магазина в ЮKassa.
     * @type string
     */
    account_id: AccountId;
    /**
     * @description Идентификатор субаккаунта. Используется для разделения потоков платежей в рамках одного аккаунта.
     * @type string | undefined
     */
    gateway_id?: GatewayId;
  };
  /**
   * @description Название способа оплаты.
   * @type string | undefined
   */
  title?: PaymentMethodTitle;
  confirmation?: PaymentMethodsConfirmationRedirect;
};
