/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const savePaymentMethodTypeEnum = {
  bank_card: "bank_card",
} as const;

export type SavePaymentMethodTypeEnumKey =
  (typeof savePaymentMethodTypeEnum)[keyof typeof savePaymentMethodTypeEnum];

/**
 * @description Тип способа оплаты.
 * @example bank_card
 */
export type SavePaymentMethodType = SavePaymentMethodTypeEnumKey;
