/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SbpBankBic } from "./sbp-bank-bic.ts";
import type { SbpBankId } from "./sbp-bank-id.ts";

/**
 * @description Реквизиты счета, который использовался для оплаты. Обязательный параметр для платежей в статусе succeeded. В остальных случаях может отсутствовать.
 */
export type SbpPayerBankDetails = {
  /**
   * @description Идентификатор банка или платежного сервиса в СБП (НСПК).
   * @pattern [a-zA-Z0-9]{12}
   * @type string
   */
  bank_id: SbpBankId;
  bic: SbpBankBic & string & any;
};
