/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RefundMethod } from "./refund-method.ts";
import type { SbpOperationId } from "./sbp-operation-id.ts";

export const sbpRefundMethodTypeEnum = {
  sbp: "sbp",
} as const;

export type SbpRefundMethodTypeEnumKey =
  (typeof sbpRefundMethodTypeEnum)[keyof typeof sbpRefundMethodTypeEnum];

/**
 * @description Данные для возврата платежа через СБП (НСПК).
 */
export type SbpRefundMethod = (RefundMethod & {
  type: "sbp";
}) & {
  /**
   * @description Идентификатор операции в СБП (НСПК). Пример: 1027088AE4CB48CB81287833347A8777.
   * @type string | undefined
   */
  sbp_operation_id?: SbpOperationId;
  type: SbpRefundMethodTypeEnumKey;
};
