/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Идентификатор банка или платежного сервиса в СБП (НСПК).
 * @maxLength 12
 * @pattern [a-zA-Z0-9]{12}
 * @example 100000000111
 */
export type SbpBankId = string;
