/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SettlementPaymentItem } from "./settlement-payment-item.ts";

/**
 * @description Данные о распределении денег.
 */
export type SettlementPaymentArray = SettlementPaymentItem[];
