/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const settlementItemTypeEnum = {
  payout: "payout",
} as const;

export type SettlementItemTypeEnumKey =
  (typeof settlementItemTypeEnum)[keyof typeof settlementItemTypeEnum];

/**
 * @description Transaction type.
 * @example payout
 */
export type SettlementItemType = SettlementItemTypeEnumKey;
