/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SettlementPayoutPayment } from "./settlement-payout-payment.ts";

/**
 * @description Данные о распределении денег.
 */
export type SettlementPaymentArray = SettlementPayoutPayment[];
