/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SettlementRefundItem } from "./settlement-refund-item.ts";

/**
 * @description Данные о распределении денег.
 */
export type SettlementRefundArray = SettlementRefundItem[];
