/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MonetaryAmount } from "./monetary-amount.ts";
import type { SettlementItemType } from "./settlement-item-type.ts";

/**
 * @description Данные о распределении денег.
 */
export type SettlementPayoutPayment = {
  /**
   * @description Transaction type.
   * @type string
   */
  type: SettlementItemType;
  /**
   * @description Сумма в выбранной валюте.
   * @type object
   */
  amount: MonetaryAmount;
};
