/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const statementTypeEnum = {
  payment_overview: "payment_overview",
} as const;

export type StatementTypeEnumKey =
  (typeof statementTypeEnum)[keyof typeof statementTypeEnum];

/**
 * @description Data for sending statements. Required if you want the user to receive a statement after they make a payment. Only one type of statement is currently available: payment overview.  This is the information about a successful payment that YooMoney sends to the user\'s email address. An overview may be sent if the payment was made via bank cards, SberPay, or FPS. The option to send overviews is available for all integration scenarios: https://yookassa.ru/developers/payment-acceptance/getting-started/selecting-integration-scenario.
 */
export type Statement = {
  /**
   * @type string
   */
  type: StatementTypeEnumKey;
};
