/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Information about user’s 3‑D Secure authentication for confirming the payment.
 */
export type ThreeDSecureDetails = {
  /**
   * @description Information on whether the 3-D Secure authentication form is displayed to the user for confirming the payment or not. Possible values: true: YooMoney displayed the form to the user, so that they could complete 3-D Secure authentication; false: payment was processed without 3-D Secure authentication.
   * @type boolean
   */
  applied: boolean;
};
