/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AccountId } from "./account-id.ts";
import type { MonetaryAmount } from "./monetary-amount.ts";

/**
 * @description Information about money distribution: the amounts of transfers and the stores to be transferred to. Specified if you use Split payments: https://yookassa.ru/developers/solutions-for-platforms/split-payments/basics.
 */
export type TransferData = {
  account_id: AccountId & any;
  amount: MonetaryAmount & any & object;
  platform_fee_amount?: MonetaryAmount & any & object;
};
