export enum OpenAPITags {
  Auth = "Auth",
  Alerts = "Alerts",
  Attachments = "Attachments",
  Archive = "Archive",
  Billing = "Billing",
  Credits = "Credits",
  Ideas = "Ideas",
  IdeasLists = "Ideas lists",
  LegalDocuments = "Legal documents",
  Tariffs = "Tariffs",
  Platforms = "Platforms",
  Profiles = "Profiles",
  Referral = "Referral",
  Scenarios = "Scenarios",
  Subscriptions = "Subscriptions",
  Templates = "Templates",
  Tones = "Tones",
  VideoDurations = "Video durations",
  VideoTypes = "Video types",
}
