/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/yookassa/client";
import fetch from "@/lib/yookassa/client";

import type {
  GetPaymentsPaymentId400,
  GetPaymentsPaymentId401,
  GetPaymentsPaymentId403,
  GetPaymentsPaymentId404,
  GetPaymentsPaymentId500,
  GetPaymentsPaymentIdPathParams,
  GetPaymentsPaymentIdQueryResponse,
} from "../models/get-payments-payment-id.ts";
import { getPaymentsPaymentIdQueryResponseSchema } from "../zod/get-payments-payment-id-schema.ts";

function getGetPaymentsPaymentIdUrl({
  payment_id,
}: {
  payment_id: GetPaymentsPaymentIdPathParams["payment_id"];
}) {
  const res = { method: "GET", url: `/payments/${payment_id}` as const };
  return res;
}

/**
 * @description This request allows you to get the information about the current payment status by its unique ID.
 * @summary Get payment information
 * {@link /payments/:payment_id}
 */
export async function getPaymentsPaymentId(
  { payment_id }: { payment_id: GetPaymentsPaymentIdPathParams["payment_id"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPaymentsPaymentIdQueryResponse,
    ResponseErrorConfig<
      | GetPaymentsPaymentId400
      | GetPaymentsPaymentId401
      | GetPaymentsPaymentId403
      | GetPaymentsPaymentId404
      | GetPaymentsPaymentId500
    >,
    unknown
  >({
    method: "GET",
    url: getGetPaymentsPaymentIdUrl({ payment_id }).url.toString(),
    ...requestConfig,
  });
  return getPaymentsPaymentIdQueryResponseSchema.parse(res.data);
}
