/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/yookassa/client";
import fetch from "@/lib/yookassa/client";

import type {
  PostPaymentsPaymentIdCapture400,
  PostPaymentsPaymentIdCapture401,
  PostPaymentsPaymentIdCapture403,
  PostPaymentsPaymentIdCapture500,
  PostPaymentsPaymentIdCaptureHeaderParams,
  PostPaymentsPaymentIdCaptureMutationRequest,
  PostPaymentsPaymentIdCaptureMutationResponse,
  PostPaymentsPaymentIdCapturePathParams,
} from "../models/post-payments-payment-id-capture.ts";
import {
  postPaymentsPaymentIdCaptureMutationRequestSchema,
  postPaymentsPaymentIdCaptureMutationResponseSchema,
} from "../zod/post-payments-payment-id-capture-schema.ts";

function getPostPaymentsPaymentIdCaptureUrl({
  payment_id,
}: {
  payment_id: PostPaymentsPaymentIdCapturePathParams["payment_id"];
}) {
  const res = {
    method: "POST",
    url: `/payments/${payment_id}/capture` as const,
  };
  return res;
}

/**
 * @description Confirm you’re ready to accept the payment. Once the payment is captured, the status will change to succeeded. After that, you can provide the customer with the product or service. You can only capture payments with the waiting_for_capture status, and only for a certain amount of time (depending on the payment method). If you do not capture the payment within the allotted time, the status will change to canceled, and the money will be returned to the user. More about capturing and canceling payments: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-process#capture-and-cancel
 * @summary Capture a payment
 * {@link /payments/:payment_id/capture}
 */
export async function postPaymentsPaymentIdCapture(
  {
    payment_id,
    data,
    headers,
  }: {
    payment_id: PostPaymentsPaymentIdCapturePathParams["payment_id"];
    data: PostPaymentsPaymentIdCaptureMutationRequest;
    headers: PostPaymentsPaymentIdCaptureHeaderParams;
  },
  config: Partial<
    RequestConfig<PostPaymentsPaymentIdCaptureMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    postPaymentsPaymentIdCaptureMutationRequestSchema.parse(data);

  const res = await request<
    PostPaymentsPaymentIdCaptureMutationResponse,
    ResponseErrorConfig<
      | PostPaymentsPaymentIdCapture400
      | PostPaymentsPaymentIdCapture401
      | PostPaymentsPaymentIdCapture403
      | PostPaymentsPaymentIdCapture500
    >,
    PostPaymentsPaymentIdCaptureMutationRequest
  >({
    method: "POST",
    url: getPostPaymentsPaymentIdCaptureUrl({ payment_id }).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return postPaymentsPaymentIdCaptureMutationResponseSchema.parse(res.data);
}
