/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/yookassa/client";
import fetch from "@/lib/yookassa/client";

import type {
  PostPaymentMethods400,
  PostPaymentMethods401,
  PostPaymentMethods403,
  PostPaymentMethods429,
  PostPaymentMethods500,
  PostPaymentMethodsHeaderParams,
  PostPaymentMethodsMutationRequest,
  PostPaymentMethodsMutationResponse,
} from "../models/post-payment-methods.ts";
import {
  postPaymentMethodsMutationRequestSchema,
  postPaymentMethodsMutationResponseSchema,
} from "../zod/post-payment-methods-schema.ts";

function getPostPaymentMethodsUrl() {
  const res = { method: "POST", url: `/payment_methods` as const };
  return res;
}

/**
 * @description Используйте этот запрос, чтобы создать в ЮKassa объект способа оплаты: https://yookassa.ru/developers/api#payment_method_object. В запросе необходимо передать код способа оплаты, который вы хотите сохранить, и при необходимости дополнительные параметры, связанные с той функциональностью, которую вы хотите использовать. Идентификатор созданного способа оплаты вы можете использовать при проведении автоплатежей: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/create-recurring или выплат: https://yookassa.ru/developers/payouts/scenario-extensions/multipurpose-token.
 * @summary Создание способа оплаты
 * {@link /payment_methods}
 */
export async function postPaymentMethods(
  {
    data,
    headers,
  }: {
    data: PostPaymentMethodsMutationRequest;
    headers: PostPaymentMethodsHeaderParams;
  },
  config: Partial<RequestConfig<PostPaymentMethodsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = postPaymentMethodsMutationRequestSchema.parse(data);

  const res = await request<
    PostPaymentMethodsMutationResponse,
    ResponseErrorConfig<
      | PostPaymentMethods400
      | PostPaymentMethods401
      | PostPaymentMethods403
      | PostPaymentMethods429
      | PostPaymentMethods500
    >,
    PostPaymentMethodsMutationRequest
  >({
    method: "POST",
    url: getPostPaymentMethodsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return postPaymentMethodsMutationResponseSchema.parse(res.data);
}
