/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/yookassa/client";
import fetch from "@/lib/yookassa/client";

import type {
  PostRefunds400,
  PostRefunds401,
  PostRefunds403,
  PostRefunds500,
  PostRefundsHeaderParams,
  PostRefundsMutationRequest,
  PostRefundsMutationResponse,
} from "../models/post-refunds.ts";
import {
  postRefundsMutationRequestSchema,
  postRefundsMutationResponseSchema,
} from "../zod/post-refunds-schema.ts";

function getPostRefundsUrl() {
  const res = { method: "POST", url: `/refunds` as const };
  return res;
}

/**
 * @description Создает возврат успешного платежа на указанную сумму. Платеж можно вернуть только в течение трех лет с момента его создания: https://yookassa.ru/developers/api#create_payment. Комиссия ЮKassa за проведение платежа не возвращается.
 * @summary Создание возврата
 * {@link /refunds}
 */
export async function postRefunds(
  {
    data,
    headers,
  }: { data: PostRefundsMutationRequest; headers: PostRefundsHeaderParams },
  config: Partial<RequestConfig<PostRefundsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = postRefundsMutationRequestSchema.parse(data);

  const res = await request<
    PostRefundsMutationResponse,
    ResponseErrorConfig<
      PostRefunds400 | PostRefunds401 | PostRefunds403 | PostRefunds500
    >,
    PostRefundsMutationRequest
  >({
    method: "POST",
    url: getPostRefundsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return postRefundsMutationResponseSchema.parse(res.data);
}
