/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringCreatePaymentOperationResponseModel } from "./acquiring-create-payment-operation-response-model.ts";
import type { LinkModel } from "./link-model.ts";
import type { MetaModel } from "./meta-model.ts";

/**
 * AcquiringCreatePaymentOperationResponseDataModel
 */
export type AcquiringCreatePaymentOperationResponseDataModel = {
  /**
   * @type object
   */
  Data: AcquiringCreatePaymentOperationResponseModel;
  /**
   * @type object
   */
  Links: LinkModel;
  /**
   * @type object
   */
  Meta: MetaModel;
};
