/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringRetailerModel } from "./acquiring-retailer-model.ts";

/**
 * AcquiringRetailerListModel
 */
export type AcquiringRetailerListModel = {
  /**
   * @type array
   */
  Retailer: AcquiringRetailerModel[];
};
