/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringPaymentMode } from "./acquiring-payment-mode.ts";
import type { AcquiringPaymentStatus } from "./acquiring-payment-status.ts";
import type { ExternalAcquiringPaymentTypeEnum } from "./external-acquiring-payment-type-enum.ts";
import type { OrderModel } from "./order-model.ts";
import type { ReceiptClientModel } from "./receipt-client-model.ts";
import type { ReceiptItemResponseModel } from "./receipt-item-response-model.ts";
import type { SupplierModel } from "./supplier-model.ts";
import type { TaxSystemCodeOutput } from "./tax-system-code-output.ts";

/**
 * AcquiringGetPaymentOperationListItemModel
 */
export type AcquiringGetPaymentOperationListItemModel = {
  /**
   * @minLength 9
   * @maxLength 9
   * @type string
   */
  customerCode: string;
  /**
   * @description Перечисление для выдачи результатов из openapi.
   * @type string | undefined
   */
  taxSystemCode?: TaxSystemCodeOutput;
  /**
   * @description Присутствует, если оплата произведена
   * @type string | undefined
   */
  paymentType?: ExternalAcquiringPaymentTypeEnum;
  /**
   * @type string | undefined
   */
  paymentId?: string;
  /**
   * @description Используется для возврата при оплате по СБП
   * @type string | undefined
   */
  transactionId?: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type array | undefined
   */
  paymentMode?: AcquiringPaymentMode[];
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  redirectUrl?: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  failRedirectUrl?: string;
  /**
   * @type object | undefined
   */
  Client?: ReceiptClientModel;
  /**
   * @type array | undefined
   */
  Items?: ReceiptItemResponseModel[];
  /**
   * @description Отсутствует, если при создании платежа назначение не было указано
   * @type string | undefined
   */
  purpose?: string;
  /**
   * @type number
   */
  amount: number;
  /**
   * @type string
   */
  status: AcquiringPaymentStatus;
  /**
   * @type string
   */
  operationId: string;
  /**
   * @type string
   */
  paymentLink: string;
  /**
   * @type string | undefined
   */
  merchantId?: string;
  /**
   * @type string | undefined
   */
  consumerId?: string;
  /**
   * @type array
   */
  Order: OrderModel[];
  /**
   * @type object | undefined
   */
  Supplier?: SupplierModel;
  /**
   * @type boolean | undefined
   */
  preAuthorization?: boolean;
  /**
   * @type string | undefined
   */
  paidAt?: string;
  /**
   * @minLength 1
   * @maxLength 45
   * @type string | undefined
   */
  paymentLinkId?: string;
};
