/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const acquiringPaymentModeEnum = {
  sbp: "sbp",
  card: "card",
  tinkoff: "tinkoff",
  dolyame: "dolyame",
} as const;

export type AcquiringPaymentModeEnumKey =
  (typeof acquiringPaymentModeEnum)[keyof typeof acquiringPaymentModeEnum];

/**
 * AcquiringPaymentMode
 */
export type AcquiringPaymentMode = AcquiringPaymentModeEnumKey;
