/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * AcquiringPaymentOperationRefundModel
 */
export type AcquiringPaymentOperationRefundModel = {
  /**
   * @type boolean
   */
  isRefund: boolean;
  /**
   * @type string
   */
  operationId: string;
  /**
   * @type number
   */
  amount: number;
  /**
   * @type string, date
   */
  date: string;
  /**
   * @type string
   */
  orderId: string;
};
