/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringPaymentMode } from "./acquiring-payment-mode.ts";
import type { AcquiringPaymentStatus } from "./acquiring-payment-status.ts";
import type { ReceiptClientModel } from "./receipt-client-model.ts";
import type { ReceiptItemModelOutput } from "./receipt-item-model-output.ts";
import type { SupplierModel } from "./supplier-model.ts";
import type { TaxSystemCodeInput } from "./tax-system-code-input.ts";

/**
 * AcquiringCreatePaymentOperationWithReceiptResponseModel
 */
export type AcquiringCreatePaymentOperationWithReceiptResponseModel = {
  /**
   * @type string
   */
  purpose: string;
  /**
   * @type string | undefined
   */
  status?: AcquiringPaymentStatus;
  /**
   * @type number
   */
  amount: number;
  /**
   * @type string
   */
  operationId: string;
  /**
   * @type string
   */
  paymentLink: string;
  /**
   * @type string | undefined
   */
  consumerId?: string;
  /**
   * @type string | undefined
   */
  merchantId?: string;
  /**
   * @type boolean | undefined
   */
  preAuthorization?: boolean;
  /**
   * @minLength 1
   * @maxLength 44640
   * @default 10080
   * @type integer | undefined
   */
  ttl?: number;
  /**
   * @minLength 1
   * @maxLength 45
   * @type string | undefined
   */
  paymentLinkId?: string;
  /**
   * @type array
   */
  paymentMode: AcquiringPaymentMode[];
  /**
   * @minLength 9
   * @maxLength 9
   * @type string
   */
  customerCode: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  redirectUrl?: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  failRedirectUrl?: string;
  /**
   * @type string | undefined
   */
  taxSystemCode?: TaxSystemCodeInput;
  /**
   * @type object
   */
  Client: ReceiptClientModel;
  /**
   * @type array
   */
  Items: ReceiptItemModelOutput[];
  /**
   * @type object | undefined
   */
  Supplier?: SupplierModel;
};
