/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringGetPaymentOperationListResponseModel } from "./acquiring-get-payment-operation-list-response-model.ts";
import type { LinkModel } from "./link-model.ts";
import type { MetaModel } from "./meta-model.ts";

/**
 * AcquiringGetPaymentOperationInfoResponseDataModel
 */
export type AcquiringGetPaymentOperationInfoResponseDataModel = {
  /**
   * @type object
   */
  Data: AcquiringGetPaymentOperationListResponseModel;
  /**
   * @type object
   */
  Links: LinkModel;
  /**
   * @type object
   */
  Meta: MetaModel;
};
