/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * AcquiringPaymentOrderRefundRequestModel
 */
export type AcquiringPaymentOrderRefundRequestModel = {
  /**
   * @description Не больше суммы оплаты
   * @type number
   */
  amount: number;
};
