/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringGetPaymentOperationListItemModel } from "./acquiring-get-payment-operation-list-item-model.ts";

/**
 * AcquiringGetPaymentOperationListResponseModel
 */
export type AcquiringGetPaymentOperationListResponseModel = {
  /**
   * @type array
   */
  Operation: AcquiringGetPaymentOperationListItemModel[];
};
