/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const acquiringRetailerStatusEnum = {
  NEW: "NEW",
  ADDRESS_DADATA: "ADDRESS_DADATA",
  OPEN_ACCOUNT: "OPEN_ACCOUNT",
  TWPG_SENDED: "TWPG_SENDED",
  RETAILER_CREATED: "RETAILER_CREATED",
  TERMINAL_CREATED: "TERMINAL_CREATED",
  FILE_SENT: "FILE_SENT",
  REG: "REG",
  CLOSE: "CLOSE",
} as const;

export type AcquiringRetailerStatusEnumKey =
  (typeof acquiringRetailerStatusEnum)[keyof typeof acquiringRetailerStatusEnum];

/**
 * AcquiringRetailerStatus
 */
export type AcquiringRetailerStatus = AcquiringRetailerStatusEnumKey;
