/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestError } from "./bad-request-error.ts";

/**
 * BadRequestErrorResponse
 */
export type BadRequestErrorResponse = {
  /**
   * @maxLength 40
   * @type string
   */
  code: string;
  /**
   * @maxLength 40
   * @type string
   */
  id: string;
  /**
   * @maxLength 600
   * @type string
   */
  message: string;
  /**
   * @type array
   */
  Errors: BadRequestError[];
};
