/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringCapturePaymentResponseModel } from "./acquiring-capture-payment-response-model.ts";
import type { BadRequestErrorResponse } from "./bad-request-error-response.ts";
import type { ErrorResponse } from "./error-response.ts";
import type { ForbiddenErrorResponse } from "./forbidden-error-response.ts";
import type { NotFoundErrorResponse } from "./not-found-error-response.ts";
import type { UnauthorizedErrorResponse } from "./unauthorized-error-response.ts";

export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePostPathParams =
  {
    /**
     * @description Идентификатор подписки
     * @type string
     */
    operationId: string;
  };

/**
 * AcquiringCapturePaymentResponseModel
 * @description Successful Response
 */
export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePost200 =
  AcquiringCapturePaymentResponseModel;

/**
 * BadRequestErrorResponse
 * @description Bad Request
 */
export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePost400 =
  BadRequestErrorResponse;

/**
 * UnauthorizedErrorResponse
 * @description Unauthorized
 */
export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePost401 =
  UnauthorizedErrorResponse;

/**
 * ForbiddenErrorResponse
 * @description Forbidden
 */
export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePost403 =
  ForbiddenErrorResponse;

/**
 * NotFoundErrorResponse
 * @description Not Found
 */
export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePost404 =
  NotFoundErrorResponse;

/**
 * ErrorResponse
 * @description Server error
 */
export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePost500 =
  ErrorResponse;

export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePostMutationResponse =
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePost200;

export type CapturePaymentAcquiringV10PaymentsOperationIdCapturePostMutation = {
  Response: CapturePaymentAcquiringV10PaymentsOperationIdCapturePost200;
  PathParams: CapturePaymentAcquiringV10PaymentsOperationIdCapturePostPathParams;
  Errors:
    | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost400
    | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost401
    | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost403
    | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost404
    | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost500;
};
