/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringCreatePaymentOperationWithReceiptRequestDataModel } from "./acquiring-create-payment-operation-with-receipt-request-data-model.ts";
import type { AcquiringCreatePaymentOperationWithReceiptResponseDataModel } from "./acquiring-create-payment-operation-with-receipt-response-data-model.ts";
import type { BadRequestErrorResponse } from "./bad-request-error-response.ts";
import type { ErrorResponse } from "./error-response.ts";
import type { ForbiddenErrorResponse } from "./forbidden-error-response.ts";
import type { NotFoundErrorResponse } from "./not-found-error-response.ts";
import type { UnauthorizedErrorResponse } from "./unauthorized-error-response.ts";

/**
 * AcquiringCreatePaymentOperationWithReceiptResponseDataModel
 * @description Successful Response
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost200 =
  AcquiringCreatePaymentOperationWithReceiptResponseDataModel;

/**
 * BadRequestErrorResponse
 * @description Bad Request
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost400 =
  BadRequestErrorResponse;

/**
 * UnauthorizedErrorResponse
 * @description Unauthorized
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost401 =
  UnauthorizedErrorResponse;

/**
 * ForbiddenErrorResponse
 * @description Forbidden
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost403 =
  ForbiddenErrorResponse;

/**
 * NotFoundErrorResponse
 * @description Not Found
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost404 =
  NotFoundErrorResponse;

/**
 * ErrorResponse
 * @description Server error
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost500 =
  ErrorResponse;

/**
 * AcquiringCreatePaymentOperationWithReceiptRequestDataModel
 */
export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequest =
  AcquiringCreatePaymentOperationWithReceiptRequestDataModel;

export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationResponse =
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost200;

export type CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutation =
  {
    Response: CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost200;
    Request: CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequest;
    Errors:
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost400
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost401
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost403
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost404
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost500;
  };
