/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./error-model.ts";

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * @maxLength 40
   * @type string
   */
  code: string;
  /**
   * @maxLength 40
   * @type string
   */
  id: string;
  /**
   * @maxLength 600
   * @type string
   */
  message: string;
  /**
   * @type array
   */
  Errors: ErrorModel[];
};
