/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * @type string
   */
  errorCode: string;
  /**
   * @maxLength 603
   * @type string
   */
  message: string;
  /**
   * @type string
   */
  url: string;
};
