/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const externalAcquiringPaymentTypeEnumEnum = {
  sbp: "sbp",
  card: "card",
  tinkoff: "tinkoff",
  dolyame: "dolyame",
} as const;

export type ExternalAcquiringPaymentTypeEnumEnumKey =
  (typeof externalAcquiringPaymentTypeEnumEnum)[keyof typeof externalAcquiringPaymentTypeEnumEnum];

/**
 * ExternalAcquiringPaymentTypeEnum
 */
export type ExternalAcquiringPaymentTypeEnum =
  ExternalAcquiringPaymentTypeEnumEnumKey;
