/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ForbiddenError } from "./forbidden-error.ts";

/**
 * ForbiddenErrorResponse
 */
export type ForbiddenErrorResponse = {
  /**
   * @maxLength 40
   * @type string
   */
  code: string;
  /**
   * @maxLength 40
   * @type string
   */
  id: string;
  /**
   * @maxLength 600
   * @type string
   */
  message: string;
  /**
   * @type array
   */
  Errors: ForbiddenError[];
};
