/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringRetailerListResponseModel } from "./acquiring-retailer-list-response-model.ts";
import type { BadRequestErrorResponse } from "./bad-request-error-response.ts";
import type { ErrorResponse } from "./error-response.ts";
import type { ForbiddenErrorResponse } from "./forbidden-error-response.ts";
import type { NotFoundErrorResponse } from "./not-found-error-response.ts";
import type { UnauthorizedErrorResponse } from "./unauthorized-error-response.ts";

export type GetRetailersAcquiringV10RetailersGetQueryParams = {
  /**
   * @description Уникальный код клиента
   * @type string
   */
  customerCode: string;
};

/**
 * AcquiringRetailerListResponseModel
 * @description Successful Response
 */
export type GetRetailersAcquiringV10RetailersGet200 =
  AcquiringRetailerListResponseModel;

/**
 * BadRequestErrorResponse
 * @description Bad Request
 */
export type GetRetailersAcquiringV10RetailersGet400 = BadRequestErrorResponse;

/**
 * UnauthorizedErrorResponse
 * @description Unauthorized
 */
export type GetRetailersAcquiringV10RetailersGet401 = UnauthorizedErrorResponse;

/**
 * ForbiddenErrorResponse
 * @description Forbidden
 */
export type GetRetailersAcquiringV10RetailersGet403 = ForbiddenErrorResponse;

/**
 * NotFoundErrorResponse
 * @description Not Found
 */
export type GetRetailersAcquiringV10RetailersGet404 = NotFoundErrorResponse;

/**
 * ErrorResponse
 * @description Server error
 */
export type GetRetailersAcquiringV10RetailersGet500 = ErrorResponse;

export type GetRetailersAcquiringV10RetailersGetQueryResponse =
  GetRetailersAcquiringV10RetailersGet200;

export type GetRetailersAcquiringV10RetailersGetQuery = {
  Response: GetRetailersAcquiringV10RetailersGet200;
  QueryParams: GetRetailersAcquiringV10RetailersGetQueryParams;
  Errors:
    | GetRetailersAcquiringV10RetailersGet400
    | GetRetailersAcquiringV10RetailersGet401
    | GetRetailersAcquiringV10RetailersGet403
    | GetRetailersAcquiringV10RetailersGet404
    | GetRetailersAcquiringV10RetailersGet500;
};
