/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringPaymentRegistryResponseDataModel } from "./acquiring-payment-registry-response-data-model.ts";
import type { BadRequestErrorResponse } from "./bad-request-error-response.ts";
import type { ErrorResponse } from "./error-response.ts";
import type { ForbiddenErrorResponse } from "./forbidden-error-response.ts";
import type { NotFoundErrorResponse } from "./not-found-error-response.ts";
import type { UnauthorizedErrorResponse } from "./unauthorized-error-response.ts";

export type GetPaymentRegistryAcquiringV10RegistryGetQueryParams = {
  /**
   * @description Уникальный код клиента
   * @type string
   */
  customerCode: string;
  /**
   * @description Идентификатор торговой точки в интернет-эквайринге
   * @type string
   */
  merchantId: string;
  /**
   * @description Уникальный идентификатор платежа, по которому произошла транзакция
   * @type string | undefined
   */
  paymentId?: string;
  /**
   * @description Дата реестра
   * @type string
   */
  date: string;
};

/**
 * AcquiringPaymentRegistryResponseDataModel
 * @description Successful Response
 */
export type GetPaymentRegistryAcquiringV10RegistryGet200 =
  AcquiringPaymentRegistryResponseDataModel;

/**
 * BadRequestErrorResponse
 * @description Bad Request
 */
export type GetPaymentRegistryAcquiringV10RegistryGet400 =
  BadRequestErrorResponse;

/**
 * UnauthorizedErrorResponse
 * @description Unauthorized
 */
export type GetPaymentRegistryAcquiringV10RegistryGet401 =
  UnauthorizedErrorResponse;

/**
 * ForbiddenErrorResponse
 * @description Forbidden
 */
export type GetPaymentRegistryAcquiringV10RegistryGet403 =
  ForbiddenErrorResponse;

/**
 * NotFoundErrorResponse
 * @description Not Found
 */
export type GetPaymentRegistryAcquiringV10RegistryGet404 =
  NotFoundErrorResponse;

/**
 * ErrorResponse
 * @description Server error
 */
export type GetPaymentRegistryAcquiringV10RegistryGet500 = ErrorResponse;

export type GetPaymentRegistryAcquiringV10RegistryGetQueryResponse =
  GetPaymentRegistryAcquiringV10RegistryGet200;

export type GetPaymentRegistryAcquiringV10RegistryGetQuery = {
  Response: GetPaymentRegistryAcquiringV10RegistryGet200;
  QueryParams: GetPaymentRegistryAcquiringV10RegistryGetQueryParams;
  Errors:
    | GetPaymentRegistryAcquiringV10RegistryGet400
    | GetPaymentRegistryAcquiringV10RegistryGet401
    | GetPaymentRegistryAcquiringV10RegistryGet403
    | GetPaymentRegistryAcquiringV10RegistryGet404
    | GetPaymentRegistryAcquiringV10RegistryGet500;
};
