/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AcquiringGetPaymentOperationInfoResponseDataModel } from "./acquiring-get-payment-operation-info-response-data-model.ts";
import type { BadRequestErrorResponse } from "./bad-request-error-response.ts";
import type { ErrorResponse } from "./error-response.ts";
import type { ForbiddenErrorResponse } from "./forbidden-error-response.ts";
import type { NotFoundErrorResponse } from "./not-found-error-response.ts";
import type { UnauthorizedErrorResponse } from "./unauthorized-error-response.ts";

export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetPathParams =
  {
    /**
     * @description Идентификатор платежа
     * @type string
     */
    operationId: string;
  };

/**
 * AcquiringGetPaymentOperationInfoResponseDataModel
 * @description Successful Response
 */
export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet200 =
  AcquiringGetPaymentOperationInfoResponseDataModel;

/**
 * BadRequestErrorResponse
 * @description Bad Request
 */
export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet400 =
  BadRequestErrorResponse;

/**
 * UnauthorizedErrorResponse
 * @description Unauthorized
 */
export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet401 =
  UnauthorizedErrorResponse;

/**
 * ForbiddenErrorResponse
 * @description Forbidden
 */
export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet403 =
  ForbiddenErrorResponse;

/**
 * NotFoundErrorResponse
 * @description Not Found
 */
export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet404 =
  NotFoundErrorResponse;

/**
 * ErrorResponse
 * @description Server error
 */
export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet500 =
  ErrorResponse;

export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQueryResponse =
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet200;

export type GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQuery = {
  Response: GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet200;
  PathParams: GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetPathParams;
  Errors:
    | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet400
    | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet401
    | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet403
    | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet404
    | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet500;
};
