/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * LinkModel
 */
export type LinkModel = {
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string, uri
   */
  self: string;
};
