/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const orderTypeEnum = {
  refund: "refund",
  approval: "approval",
  authorized: "authorized",
} as const;

export type OrderTypeEnumKey =
  (typeof orderTypeEnum)[keyof typeof orderTypeEnum];

/**
 * OrderType
 */
export type OrderType = OrderTypeEnumKey;
