/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * PaginatedLinkModel
 */
export type PaginatedLinkModel = {
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string, uri
   */
  self: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  first?: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  prev?: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  next?: string;
  /**
   * @minLength 1
   * @maxLength 2083
   * @type string | undefined, uri
   */
  last?: string;
};
