/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentObjectEnum = {
  goods: "goods",
  service: "service",
  work: "work",
} as const;

export type PaymentObjectEnumKey =
  (typeof paymentObjectEnum)[keyof typeof paymentObjectEnum];

/**
 * PaymentObject
 */
export type PaymentObject = PaymentObjectEnumKey;
