/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentMethodEnum = {
  full_payment: "full_payment",
  full_prepayment: "full_prepayment",
} as const;

export type PaymentMethodEnumKey =
  (typeof paymentMethodEnum)[keyof typeof paymentMethodEnum];

/**
 * PaymentMethod
 */
export type PaymentMethod = PaymentMethodEnumKey;
