/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ReceiptClientModel
 */
export type ReceiptClientModel = {
  /**
   * @type string | undefined
   */
  name?: string;
  /**
   * @type string, email
   */
  email: string;
  /**
   * @type string | undefined
   */
  phone?: string;
};
