/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SupplierModel
 */
export type SupplierModel = {
  /**
   * @minLength 11
   * @maxLength 15
   * @pattern ^\+?\d+$
   * @type string
   */
  phone: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @minLength 10
   * @maxLength 12
   * @pattern ^\d+$
   * @type string
   */
  taxCode: string;
};
