/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const taxSystemCodeOutputEnum = {
  osn: "osn",
  usn_income: "usn_income",
  usn_income_outcome: "usn_income_outcome",
  esn: "esn",
  patent: "patent",
  envd: "envd",
} as const;

export type TaxSystemCodeOutputEnumKey =
  (typeof taxSystemCodeOutputEnum)[keyof typeof taxSystemCodeOutputEnum];

/**
 * TaxSystemCodeOutput
 * @description Перечисление для выдачи результатов из openapi.
 */
export type TaxSystemCodeOutput = TaxSystemCodeOutputEnumKey;
