/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UnauthorizedError } from "./unauthorized-error.ts";

/**
 * UnauthorizedErrorResponse
 */
export type UnauthorizedErrorResponse = {
  /**
   * @maxLength 40
   * @type string
   */
  code: string;
  /**
   * @maxLength 40
   * @type string
   */
  id: string;
  /**
   * @maxLength 600
   * @type string
   */
  message: string;
  /**
   * @type array
   */
  Errors: UnauthorizedError[];
};
