/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const vatTypeHistoricalEnum = {
  none: "none",
  vat0: "vat0",
  vat5: "vat5",
  vat7: "vat7",
  vat10: "vat10",
  vat20: "vat20",
  vat22: "vat22",
  vat105: "vat105",
  vat107: "vat107",
  vat110: "vat110",
  vat120: "vat120",
  vat122: "vat122",
} as const;

export type VatTypeHistoricalEnumKey =
  (typeof vatTypeHistoricalEnum)[keyof typeof vatTypeHistoricalEnum];

/**
 * VatTypeHistorical
 */
export type VatTypeHistorical = VatTypeHistoricalEnumKey;
