/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/tochka/api/client.ts";
import fetch from "@/lib/tochka/api/client.ts";

import type {
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePost400,
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePost401,
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePost403,
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePost404,
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePost500,
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePostMutationResponse,
  CapturePaymentAcquiringV10PaymentsOperationIdCapturePostPathParams,
} from "../models/capture-payment-acquiring-v10-payments-operation-id-capture-post.ts";
import { capturePaymentAcquiringV10PaymentsOperationIdCapturePostMutationResponseSchema } from "../zod/capture-payment-acquiring-v10-payments-operation-id-capture-post-schema.ts";

function getCapturePaymentAcquiringV10PaymentsOperationIdCapturePostUrl({
  operationId,
}: {
  operationId: CapturePaymentAcquiringV10PaymentsOperationIdCapturePostPathParams["operationId"];
}) {
  const res = {
    method: "POST",
    url: `/acquiring/v1.0/payments/${operationId}/capture` as const,
  };
  return res;
}

/**
 * @description Метод для списания средств при двухэтапной оплате
 * @summary Capture Payment
 * {@link /acquiring/v1.0/payments/:operationId/capture}
 */
export async function capturePaymentAcquiringV10PaymentsOperationIdCapturePost(
  {
    operationId,
  }: {
    operationId: CapturePaymentAcquiringV10PaymentsOperationIdCapturePostPathParams["operationId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CapturePaymentAcquiringV10PaymentsOperationIdCapturePostMutationResponse,
    ResponseErrorConfig<
      | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost400
      | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost401
      | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost403
      | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost404
      | CapturePaymentAcquiringV10PaymentsOperationIdCapturePost500
    >,
    unknown
  >({
    method: "POST",
    url: getCapturePaymentAcquiringV10PaymentsOperationIdCapturePostUrl({
      operationId,
    }).url.toString(),
    ...requestConfig,
  });
  return capturePaymentAcquiringV10PaymentsOperationIdCapturePostMutationResponseSchema.parse(
    res.data,
  );
}
