/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/tochka/client";
import fetch from "@/lib/tochka/client";

import type {
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost400,
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost401,
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost403,
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost404,
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost500,
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequest,
  CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationResponse,
} from "../models/create-payment-operation-with-receipt-acquiring-v10-payments-with-receipt-post.ts";
import {
  createPaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequestSchema,
  createPaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationResponseSchema,
} from "../zod/create-payment-operation-with-receipt-acquiring-v10-payments-with-receipt-post-schema.ts";

function getCreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostUrl() {
  const res = {
    method: "POST",
    url: `/acquiring/v1.0/payments_with_receipt` as const,
  };
  return res;
}

/**
 * @description Метод для создания ссылки на оплату и отправки чека
 * @summary Create Payment Operation With Receipt
 * {@link /acquiring/v1.0/payments_with_receipt}
 */
export async function createPaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost(
  {
    data,
  }: {
    data: CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequest;
  },
  config: Partial<
    RequestConfig<CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    createPaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequestSchema.parse(
      data,
    );

  const res = await request<
    CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationResponse,
    ResponseErrorConfig<
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost400
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost401
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost403
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost404
      | CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPost500
    >,
    CreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationRequest
  >({
    method: "POST",
    url: getCreatePaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return createPaymentOperationWithReceiptAcquiringV10PaymentsWithReceiptPostMutationResponseSchema.parse(
    res.data,
  );
}
