/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/tochka/api/client.ts";
import fetch from "@/lib/tochka/api/client.ts";

import type {
  CreatePaymentOperationAcquiringV10PaymentsPost400,
  CreatePaymentOperationAcquiringV10PaymentsPost401,
  CreatePaymentOperationAcquiringV10PaymentsPost403,
  CreatePaymentOperationAcquiringV10PaymentsPost404,
  CreatePaymentOperationAcquiringV10PaymentsPost500,
  CreatePaymentOperationAcquiringV10PaymentsPostMutationRequest,
  CreatePaymentOperationAcquiringV10PaymentsPostMutationResponse,
} from "../models/create-payment-operation-acquiring-v10-payments-post.ts";
import {
  createPaymentOperationAcquiringV10PaymentsPostMutationRequestSchema,
  createPaymentOperationAcquiringV10PaymentsPostMutationResponseSchema,
} from "../zod/create-payment-operation-acquiring-v10-payments-post-schema.ts";

function getCreatePaymentOperationAcquiringV10PaymentsPostUrl() {
  const res = { method: "POST", url: `/acquiring/v1.0/payments` as const };
  return res;
}

/**
 * @description Метод для создания ссылки на оплату
 * @summary Create Payment Operation
 * {@link /acquiring/v1.0/payments}
 */
export async function createPaymentOperationAcquiringV10PaymentsPost(
  {
    data,
  }: { data: CreatePaymentOperationAcquiringV10PaymentsPostMutationRequest },
  config: Partial<
    RequestConfig<CreatePaymentOperationAcquiringV10PaymentsPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    createPaymentOperationAcquiringV10PaymentsPostMutationRequestSchema.parse(
      data,
    );

  const res = await request<
    CreatePaymentOperationAcquiringV10PaymentsPostMutationResponse,
    ResponseErrorConfig<
      | CreatePaymentOperationAcquiringV10PaymentsPost400
      | CreatePaymentOperationAcquiringV10PaymentsPost401
      | CreatePaymentOperationAcquiringV10PaymentsPost403
      | CreatePaymentOperationAcquiringV10PaymentsPost404
      | CreatePaymentOperationAcquiringV10PaymentsPost500
    >,
    CreatePaymentOperationAcquiringV10PaymentsPostMutationRequest
  >({
    method: "POST",
    url: getCreatePaymentOperationAcquiringV10PaymentsPostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return createPaymentOperationAcquiringV10PaymentsPostMutationResponseSchema.parse(
    res.data,
  );
}
