/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/tochka/client";
import fetch from "@/lib/tochka/client";

import type {
  GetRetailersAcquiringV10RetailersGet400,
  GetRetailersAcquiringV10RetailersGet401,
  GetRetailersAcquiringV10RetailersGet403,
  GetRetailersAcquiringV10RetailersGet404,
  GetRetailersAcquiringV10RetailersGet500,
  GetRetailersAcquiringV10RetailersGetQueryParams,
  GetRetailersAcquiringV10RetailersGetQueryResponse,
} from "../models/get-retailers-acquiring-v10-retailers-get.ts";
import { getRetailersAcquiringV10RetailersGetQueryResponseSchema } from "../zod/get-retailers-acquiring-v10-retailers-get-schema.ts";

function getGetRetailersAcquiringV10RetailersGetUrl() {
  const res = { method: "GET", url: `/acquiring/v1.0/retailers` as const };
  return res;
}

/**
 * @description Метод для получения информации о ретейлере
 * - *NEW* - Ретейлер создан
 * - *ADDRESS_DADATA* - Адрес уточнен
 * - *OPEN_ACCOUNT* - Счёт открыт
 * - *TWPG_SENDED* - Данные мерчанта и терминала отправлены в процессинг
 * - *RETAILER_CREATED* - Мерчант создан в процессинге
 * - *TERMINAL_CREATED* - Терминал создан в процессинге
 * - *FILE_SENT* - файл отправлен в НСПК
 * - *REG* - Зарегистрирован
 * - *CLOSE* - Закрыт
 * @summary Get Retailers
 * {@link /acquiring/v1.0/retailers}
 */
export async function getRetailersAcquiringV10RetailersGet(
  { params }: { params: GetRetailersAcquiringV10RetailersGetQueryParams },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetRetailersAcquiringV10RetailersGetQueryResponse,
    ResponseErrorConfig<
      | GetRetailersAcquiringV10RetailersGet400
      | GetRetailersAcquiringV10RetailersGet401
      | GetRetailersAcquiringV10RetailersGet403
      | GetRetailersAcquiringV10RetailersGet404
      | GetRetailersAcquiringV10RetailersGet500
    >,
    unknown
  >({
    method: "GET",
    url: getGetRetailersAcquiringV10RetailersGetUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return getRetailersAcquiringV10RetailersGetQueryResponseSchema.parse(
    res.data,
  );
}
