/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/tochka/client";
import fetch from "@/lib/tochka/client";

import type {
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet400,
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet401,
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet403,
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet404,
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet500,
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetPathParams,
  GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQueryResponse,
} from "../models/get-payment-operation-info-acquiring-v10-payments-operation-id-get.ts";
import { getPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQueryResponseSchema } from "../zod/get-payment-operation-info-acquiring-v10-payments-operation-id-get-schema.ts";

function getGetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetUrl({
  operationId,
}: {
  operationId: GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetPathParams["operationId"];
}) {
  const res = {
    method: "GET",
    url: `/acquiring/v1.0/payments/${operationId}` as const,
  };
  return res;
}

/**
 * @description Метод для получения информации о конкретной операции
 * - *CREATED* - Операция создана
 * - *APPROVED* - Операция одобрена (оплата прошла успешно)
 * - *ON-REFUND* - Операция заблокирована на время выполнения возврата
 * - *REFUNDED* - Осуществлен возврат
 * - *EXPIRED* - Истек срок действия
 * @summary Get Payment Operation Info
 * {@link /acquiring/v1.0/payments/:operationId}
 */
export async function getPaymentOperationInfoAcquiringV10PaymentsOperationIdGet(
  {
    operationId,
  }: {
    operationId: GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetPathParams["operationId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQueryResponse,
    ResponseErrorConfig<
      | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet400
      | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet401
      | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet403
      | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet404
      | GetPaymentOperationInfoAcquiringV10PaymentsOperationIdGet500
    >,
    unknown
  >({
    method: "GET",
    url: getGetPaymentOperationInfoAcquiringV10PaymentsOperationIdGetUrl({
      operationId,
    }).url.toString(),
    ...requestConfig,
  });
  return getPaymentOperationInfoAcquiringV10PaymentsOperationIdGetQueryResponseSchema.parse(
    res.data,
  );
}
