/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/tochka/client";
import fetch from "@/lib/tochka/client";

import type {
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost400,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost401,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost403,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost404,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost500,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationRequest,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationResponse,
  RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostPathParams,
} from "../models/refund-payment-operation-acquiring-v10-payments-operation-id-refund-post.ts";
import {
  refundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationRequestSchema,
  refundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationResponseSchema,
} from "../zod/refund-payment-operation-acquiring-v10-payments-operation-id-refund-post-schema.ts";

function getRefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostUrl({
  operationId,
}: {
  operationId: RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostPathParams["operationId"];
}) {
  const res = {
    method: "POST",
    url: `/acquiring/v1.0/payments/${operationId}/refund` as const,
  };
  return res;
}

/**
 * @description Метод для возврата платежей, созданных через платёжную ссылку
 * Возврат возможен только для платежа со статусом APPROVED
 * @summary Refund Payment Operation
 * {@link /acquiring/v1.0/payments/:operationId/refund}
 */
export async function refundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost(
  {
    operationId,
    data,
  }: {
    operationId: RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostPathParams["operationId"];
    data: RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationRequest;
  },
  config: Partial<
    RequestConfig<RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    refundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationRequestSchema.parse(
      data,
    );

  const res = await request<
    RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationResponse,
    ResponseErrorConfig<
      | RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost400
      | RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost401
      | RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost403
      | RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost404
      | RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPost500
    >,
    RefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationRequest
  >({
    method: "POST",
    url: getRefundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostUrl({
      operationId,
    }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return refundPaymentOperationAcquiringV10PaymentsOperationIdRefundPostMutationResponseSchema.parse(
    res.data,
  );
}
