/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Идентификатор магазина в ЮKassa.
 */
export const accountIdSchema = z
  .string()
  .describe("Идентификатор магазина в ЮKassa.");
