/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { airlineLegSchema } from "./airline-leg-schema.ts";
import { airlinePassengerSchema } from "./airline-passenger-schema.ts";

/**
 * @description Объект с данными для продажи авиабилетов: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/airline-tickets. Используется только для платежей банковской картой.
 */
export const airlineSchema = z
  .object({
    ticket_number: z.optional(
      z
        .string()
        .min(1)
        .max(150)
        .regex(/[0-9]{1,150}/)
        .describe(
          "Unique ticket number. If you already know the ticket number during payment creation, ticket_number is a required parameter. If you don't, specify booking_reference instead of ticket_number.",
        ),
    ),
    booking_reference: z.optional(
      z
        .string()
        .min(1)
        .max(20)
        .describe(
          "Booking reference number, required if ticket_number is not specified.",
        ),
    ),
    get passengers() {
      return z
        .array(airlinePassengerSchema.describe("Информация о пассажире."))
        .min(0)
        .max(500)
        .describe("List of passengers.")
        .optional();
    },
    get legs() {
      return z
        .array(airlineLegSchema.describe("Информация о перелете."))
        .min(0)
        .max(4)
        .describe("List of flight legs.")
        .optional();
    },
  })
  .describe(
    "Объект с данными для продажи авиабилетов: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/airline-tickets. Используется только для платежей банковской картой.",
  );
