/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Информация о пассажире.
 */
export const airlinePassengerSchema = z
  .object({
    first_name: z
      .string()
      .min(1)
      .max(64)
      .describe(
        "Passenger's first name. Only use Latin characters, for example, SERGEI.",
      ),
    last_name: z
      .string()
      .min(1)
      .max(64)
      .describe(
        "Passenger's last name. Only use Latin characters, for example, IVANOV.",
      ),
  })
  .describe("Информация о пассажире.");
