/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { B2BSberbankVatDataTypeSchema } from "./b2-b-sberbank-vat-data-type-schema.ts";

/**
 * @description Данные о налоге на добавленную стоимость (НДС). Платеж может облагаться или не облагаться НДС. Товары могут облагаться по одной ставке НДС или по разным.
 */
export const B2BSberbankVatDataSchema = z
  .object({
    get type() {
      return B2BSberbankVatDataTypeSchema.describe("Тип способа расчета НДС.");
    },
  })
  .describe(
    "Данные о налоге на добавленную стоимость (НДС). Платеж может облагаться или не облагаться НДС. Товары могут облагаться по одной ставке НДС или по разным.",
  );
