/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Банковские реквизиты плательщика (юридического лица или ИП).
 */
export const B2BSberbankPayerBankDetailsSchema = z
  .object({
    full_name: z.string().max(800).describe("Полное наименование организации."),
    short_name: z
      .string()
      .max(160)
      .describe("Сокращенное наименование организации."),
    address: z.string().max(500).describe("Адрес организации."),
    inn: z
      .string()
      .regex(/\d{10}|\d{12}/)
      .describe("Индивидуальный налоговый номер (ИНН) организации."),
    bank_name: z
      .string()
      .min(1)
      .max(350)
      .describe("Наименование банка организации."),
    bank_branch: z
      .string()
      .min(1)
      .max(140)
      .describe("Отделение банка организации."),
    bank_bik: z
      .string()
      .regex(/\d{9}/)
      .describe("Банковский идентификационный код (БИК) банка организации."),
    account: z
      .string()
      .regex(/\d{20}/)
      .describe("Номер счета организации."),
    kpp: z.optional(
      z
        .string()
        .regex(/\d{9}/)
        .describe("Код причины постановки на учет (КПП) организации."),
    ),
  })
  .describe("Банковские реквизиты плательщика (юридического лица или ИП).");
