/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { B2BSberbankVatDataSchema } from "./b2-b-sberbank-vat-data-schema.ts";

/**
 * @description Данные об НДС, если товар или услуга не облагается налогом (в параметре type передано значение untaxed).
 */
export const B2BSberbankUntaxedVatDataSchema = z
  .lazy(() => B2BSberbankVatDataSchema)
  .and(
    z.object({
      type: z.literal("untaxed"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["untaxed"]),
    }),
  )
  .describe(
    "Данные об НДС, если товар или услуга не облагается налогом (в параметре type передано значение untaxed).",
  );
