/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Тип способа расчета НДС.
 */
export const B2BSberbankVatDataTypeSchema = z
  .enum(["calculated", "untaxed", "mixed"])
  .describe("Тип способа расчета НДС.");
