/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { B2BSberbankVatDataSchema } from "./b2-b-sberbank-vat-data-schema.ts";
import { monetaryAmountSchema } from "./monetary-amount-schema.ts";

/**
 * @description Данные об НДС, если создается платеж на несколько товаров или услуг с разными ставками НДС (в параметре type передано значение mixed).
 */
export const B2BSberbankMixedVatDataSchema = z
  .lazy(() => B2BSberbankVatDataSchema)
  .and(
    z.object({
      type: z.literal("mixed"),
    }),
  )
  .and(
    z.object({
      get amount() {
        return monetaryAmountSchema.and(z.any());
      },
      type: z.enum(["mixed"]),
    }),
  )
  .describe(
    "Данные об НДС, если создается платеж на несколько товаров или услуг с разными ставками НДС (в параметре type передано значение mixed).",
  );
