/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { errorSchema } from "./error-schema.ts";

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export const badRequestSchema = z
  .lazy(() => errorSchema)
  .and(
    z.object({
      code: z.optional(z.enum(["invalid_request"]).describe("Код ошибки")),
    }),
  )
  .describe(
    "Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.",
  );
