/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Карточный продукт платежной системы, с которым ассоциирована банковская карта. Например, карточные продукты платежной системы Мир: Mir Classic, Mir Classic Credit, MIR Privilege Plus и другие.
 */
export const bankCardProductSchema = z
  .object({
    code: z.string().describe("Код карточного продукта. Пример: MCP"),
    name: z.optional(
      z
        .string()
        .describe("Название карточного продукта. Пример: MIR Privilege"),
    ),
  })
  .describe(
    "Карточный продукт платежной системы, с которым ассоциирована банковская карта. Например, карточные продукты платежной системы Мир: Mir Classic, Mir Classic Credit, MIR Privilege Plus и другие.",
  );
