/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Последние 4 цифры номера карты.
 */
export const bankCardLast4Schema = z
  .string()
  .regex(/[0-9]{4}/)
  .describe("Последние 4 цифры номера карты.");
