/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Имя владельца карты.
 */
export const bankCardHolderNameSchema = z
  .string()
  .regex(/[a-zA-Z '-]{0,26}/)
  .describe("Имя владельца карты.");
