/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { confirmationSchema } from "./confirmation-schema.ts";
import { confirmationUrlSchema } from "./confirmation-url-schema.ts";

export const confirmationMobileApplicationSchema = z
  .lazy(() => confirmationSchema)
  .and(
    z.object({
      type: z.literal("mobile_application"),
    }),
  )
  .and(
    z.object({
      get confirmation_url() {
        return confirmationUrlSchema.describe(
          "URL, на который необходимо перенаправить пользователя для подтверждения оплаты.",
        );
      },
      type: z.enum(["mobile_application"]),
    }),
  );
