/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { confirmationDataSchema } from "./confirmation-data-schema.ts";
import { enforceSchema } from "./enforce-schema.ts";
import { returnUrlSchema } from "./return-url-schema.ts";

export const confirmationDataRedirectSchema = z
  .lazy(() => confirmationDataSchema)
  .and(
    z.object({
      type: z.literal("redirect"),
    }),
  )
  .and(
    z.object({
      get enforce() {
        return enforceSchema
          .describe(
            "Запрос на проведение платежа с аутентификацией по 3-D Secure. Будет работать, если оплату банковской картой вы по умолчанию принимаете без подтверждения платежа пользователем. В остальных случаях аутентификацией по 3-D Secure будет управлять ЮKassa. Если хотите принимать платежи без дополнительного подтверждения пользователем, напишите вашему менеджеру ЮKassa.",
          )
          .optional();
      },
      get return_url() {
        return returnUrlSchema.describe(
          "URL, на который вернется пользователь после подтверждения или отмены платежа на веб-странице. Не более 2048 символов.",
        );
      },
      type: z.enum(["redirect"]),
    }),
  );
