/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { confirmationDataSchema } from "./confirmation-data-schema.ts";

export const confirmationDataExternalSchema = z
  .lazy(() => confirmationDataSchema)
  .and(
    z.object({
      type: z.literal("external"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["external"]),
    }),
  );
