/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { confirmationDataSchema } from "./confirmation-data-schema.ts";
import { returnUrlSchema } from "./return-url-schema.ts";

export const confirmationDataMobileApplicationSchema = z
  .lazy(() => confirmationDataSchema)
  .and(
    z.object({
      type: z.literal("mobile_application"),
    }),
  )
  .and(
    z.object({
      get return_url() {
        return returnUrlSchema.describe(
          "URL, на который вернется пользователь после подтверждения или отмены платежа на веб-странице. Не более 2048 символов.",
        );
      },
      type: z.enum(["mobile_application"]),
    }),
  );
