/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Идентификатор сделки.
 */
export const dealIdSchema = z
  .string()
  .min(36)
  .max(50)
  .describe("Идентификатор сделки.");
