/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Порядковый номер товара в корзине. От 1 до 999 включительно.
 */
export const electronicCertificateArticleNumberSchema = z
  .int()
  .min(1)
  .max(999)
  .describe("Порядковый номер товара в корзине. От 1 до 999 включительно.");
