/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { electronicCertificateArticleNumberSchema } from "./electronic-certificate-article-number-schema.ts";
import { electronicCertificateTruCodeSchema } from "./electronic-certificate-tru-code-schema.ts";

/**
 * @description Товарная позиция в корзине возврата при возврате на электронный сертификат.
 */
export const electronicCertificateRefundArticleSchema = z
  .object({
    get article_number() {
      return electronicCertificateArticleNumberSchema.describe(
        "Порядковый номер товара в корзине. От 1 до 999 включительно.",
      );
    },
    get payment_article_number() {
      return electronicCertificateArticleNumberSchema.describe(
        "Порядковый номер товара в корзине. От 1 до 999 включительно.",
      );
    },
    get tru_code() {
      return electronicCertificateTruCodeSchema.describe(
        "Код ТРУ. 30 символов, две группы цифр, разделенные точкой. Формат: NNNNNNNNN.NNNNNNNNNYYYYMMMMZZZ, где NNNNNNNNN.NNNNNNNNN — код вида ТРУ по Перечню ТРУ: https://esnsi.gosuslugi.ru/classifiers/10616/data?pg=1&p=1, YYYY — код производителя, MMMM — код модели, ZZZ — код страны производителя. Пример: 329921120.06001010200080001643 Как сформировать код ТРУ: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/basics#payments-preparations-tru-code",
      );
    },
    quantity: z
      .int()
      .min(1)
      .describe(
        "Количество возвращаемых единиц товара. Формат: целое положительное число.",
      ),
  })
  .describe(
    "Товарная позиция в корзине возврата при возврате на электронный сертификат.",
  );
