/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Количество единиц товара. Формат: целое положительное число.
 */
export const electronicCertificateArticleQuantitySchema = z
  .int()
  .describe("Количество единиц товара. Формат: целое положительное число.");
