/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { basketIdSchema } from "./basket-id-schema.ts";
import { monetaryAmountSchema } from "./monetary-amount-schema.ts";

/**
 * @description Данные от ФЭС НСПК для возврата на электронный сертификат. Неоходимо передавать только при оплате со сбором данных на вашей стороне: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/merchant-payment-form.
 */
export const electronicCertificateRefundDataRequestSchema = z
  .object({
    get amount() {
      return monetaryAmountSchema.describe("Сумма в выбранной валюте.");
    },
    get basket_id() {
      return basketIdSchema.describe(
        "Идентификатор корзины, сформированной в НСПК.",
      );
    },
  })
  .describe(
    "Данные от ФЭС НСПК для возврата на электронный сертификат. Неоходимо передавать только при оплате со сбором данных на вашей стороне: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/merchant-payment-form.",
  );
