/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { monetaryAmountSchema } from "./monetary-amount-schema.ts";

/**
 * @description Описание используемого электронного сертификата.
 */
export const electronicCertificateSchema = z
  .object({
    certificate_id: z
      .string()
      .min(20)
      .max(30)
      .describe("Идентификатор сертификата. От 20 до 30 символов."),
    tru_quantity: z
      .int()
      .describe(
        "Количество единиц товара, которое одобрили для оплаты по этому электронному сертификату.",
      ),
    get available_compensation() {
      return monetaryAmountSchema.and(z.any());
    },
    get applied_compensation() {
      return monetaryAmountSchema.and(z.any());
    },
  })
  .describe("Описание используемого электронного сертификата.");
