/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { basketIdSchema } from "./basket-id-schema.ts";
import { monetaryAmountSchema } from "./monetary-amount-schema.ts";

/**
 * @description Данные от ФЭС НСПК для оплаты по электронному сертификату.
 */
export const electronicCertificatePaymentSchema = z
  .object({
    get amount() {
      return monetaryAmountSchema.and(z.any());
    },
    get basket_id() {
      return basketIdSchema.and(z.any());
    },
  })
  .describe("Данные от ФЭС НСПК для оплаты по электронному сертификату.");
