/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Код товара в вашей системе. Максимум 128 символов.
 */
export const electronicCertificateArticleCodeSchema = z
  .string()
  .max(128)
  .describe("Код товара в вашей системе. Максимум 128 символов.");
