/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Объект ошибки.
 */
export const errorSchema = z
  .object({
    type: z.optional(z.enum(["error"]).describe("Тип объекта.")),
    id: z.optional(
      z
        .string()
        .describe(
          "Идентификатор ошибки. Используйте его, если возникла необходимость обратиться в техническую поддержку.",
        ),
    ),
    description: z.optional(z.string().describe("Подробное описание ошибки.")),
    parameter: z.optional(
      z
        .string()
        .describe("Название параметра, из-за которого произошла ошибка."),
    ),
    retry_after: z.optional(
      z
        .int()
        .describe(
          "Рекомендуемое количество миллисекунд, спустя которое следует повторить запрос.",
        ),
    ),
  })
  .describe("Объект ошибки.");
