/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestSchema } from "./bad-request-schema.ts";
import { forbiddenSchema } from "./forbidden-schema.ts";
import { invalidCredentialsSchema } from "./invalid-credentials-schema.ts";
import { paymentIdSchema } from "./payment-id-schema.ts";
import { refundListSchema } from "./refund-list-schema.ts";
import { refundStatusSchema } from "./refund-status-schema.ts";
import { tooManyRequestsSchema } from "./too-many-requests-schema.ts";

export const getRefundsQueryParamsSchema = z.object({
  "created_at.gte": z.optional(
    z.iso
      .datetime()
      .describe(
        "Фильтр по времени создания: время должно быть больше указанного значения или равно ему («с такого-то момента включительно»). Указывается в формате ISO 8601: https://en.wikipedia.org/wiki/ISO_8601. Пример: created_at.gte=2018-07-18T10:51:18.139Z",
      ),
  ),
  "created_at.gt": z.optional(
    z.iso
      .datetime()
      .describe(
        "Фильтр по времени создания: время должно быть больше указанного значения («с такого-то момента, не включая его»). Указывается в формате ISO 8601: https://en.wikipedia.org/wiki/ISO_8601. Пример: created_at.gt=2018-07-18T10:51:18.139Z",
      ),
  ),
  "created_at.lte": z.optional(
    z.iso
      .datetime()
      .describe(
        "Фильтр по времени создания: время должно быть меньше указанного значения или равно ему («по такой-то момент включительно»). Указывается в формате ISO 8601: https://en.wikipedia.org/wiki/ISO_8601. Пример: created_at.lte=2018-07-18T10:51:18.139Z",
      ),
  ),
  "created_at.lt": z.optional(
    z.iso
      .datetime()
      .describe(
        "Фильтр по времени создания: время должно быть меньше указанного значения («по такой-то момент, не включая его»). Указывается в формате ISO 8601: https://en.wikipedia.org/wiki/ISO_8601. Пример: created_at.lt=2018-07-18T10:51:18.139Z",
      ),
  ),
  get "payment_id"() {
    return paymentIdSchema
      .describe("Идентификатор платежа в ЮKassa.")
      .optional();
  },
  get "status"() {
    return refundStatusSchema
      .describe(
        "Статус возврата платежа. Возможные значения: pending — возврат создан, но пока еще обрабатывается; succeeded — возврат успешно завершен, указанная в запросе сумма переведена на платежное средство пользователя (финальный и неизменяемый статус); canceled — возврат отменен, инициатор и причина отмены указаны в объекте cancellation_details (финальный и неизменяемый статус).",
      )
      .optional();
  },
  "limit": z.coerce
    .number()
    .int()
    .min(1)
    .max(100)
    .default(10)
    .describe(
      "Размер выдачи результатов запроса — количество объектов, передаваемых в ответе. Возможные значения: от 1 до 100. Пример: limit=50 Значение по умолчанию: 10",
    ),
  "cursor": z.optional(
    z
      .string()
      .describe(
        "Указатель на следующий фрагмент списка. Пример: cursor=37a5c87d-3984-51e8-a7f3-8de646d39ec15 В качестве указателя необходимо использовать значение параметра next_cursor, полученное в ответе на предыдущий запрос. Используется, если в списке больше объектов, чем может поместиться в выдаче (limit), и конец выдачи не достигнут. Пример использования: https://yookassa.ru/developers/using-api/lists#pagination",
      ),
  ),
});

/**
 * @description Запрос успешно обработан
 */
export const getRefunds200Schema = z
  .lazy(() => refundListSchema)
  .describe(
    "Список возвратов. Возвраты отсортированы по времени создания в порядке убывания (от новых к старым). Если результатов больше, чем задано в limit, список будет выводиться фрагментами. В этом случае в ответе на запрос вернется фрагмент списка и параметр next_cursor с указателем на следующий фрагмент.",
  );

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export const getRefunds400Schema = z
  .lazy(() => badRequestSchema)
  .describe(
    "Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.",
  );

/**
 * @description В заголовке Authorization указан неверный ключ.
 */
export const getRefunds401Schema = z
  .lazy(() => invalidCredentialsSchema)
  .describe("В заголовке Authorization указан неверный ключ.");

/**
 * @description Секретный ключ указан верно, но не хватает прав для совершения операции.
 */
export const getRefunds403Schema = z
  .lazy(() => forbiddenSchema)
  .describe(
    "Секретный ключ указан верно, но не хватает прав для совершения операции.",
  );

/**
 * @description Внутренняя ошибка сервера ЮKassa.
 */
export const getRefunds500Schema = z
  .lazy(() => tooManyRequestsSchema)
  .describe(
    "Слишком много запросов одновременно отправляется в API. Повторите запрос позже.",
  );

export const getRefundsQueryResponseSchema = z.lazy(() => getRefunds200Schema);
