/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestSchema } from "./bad-request-schema.ts";
import { forbiddenSchema } from "./forbidden-schema.ts";
import { invalidCredentialsSchema } from "./invalid-credentials-schema.ts";
import { notFoundSchema } from "./not-found-schema.ts";
import { refundSchema } from "./refund-schema.ts";
import { tooManyRequestsSchema } from "./too-many-requests-schema.ts";

export const getRefundsRefundIdPathParamsSchema = z.object({
  refund_id: z
    .string()
    .min(36)
    .max(36)
    .default("cae993f2-eb15-45f5-91c5-efb87107ae10")
    .describe("Идентификатор возврата."),
});

/**
 * @description Запрос успешно обработан
 */
export const getRefundsRefundId200Schema = z
  .lazy(() => refundSchema)
  .describe(
    "Refund object (Refund) contains all the relevant information about the payment refund.",
  );

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export const getRefundsRefundId400Schema = z
  .lazy(() => badRequestSchema)
  .describe(
    "Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.",
  );

/**
 * @description В заголовке Authorization указан неверный ключ.
 */
export const getRefundsRefundId401Schema = z
  .lazy(() => invalidCredentialsSchema)
  .describe("В заголовке Authorization указан неверный ключ.");

/**
 * @description Секретный ключ указан верно, но не хватает прав для совершения операции.
 */
export const getRefundsRefundId403Schema = z
  .lazy(() => forbiddenSchema)
  .describe(
    "Секретный ключ указан верно, но не хватает прав для совершения операции.",
  );

/**
 * @description Сущность не найдена.
 */
export const getRefundsRefundId404Schema = z
  .lazy(() => notFoundSchema)
  .describe("Сущность не найдена.");

/**
 * @description Внутренняя ошибка сервера ЮKassa.
 */
export const getRefundsRefundId500Schema = z
  .lazy(() => tooManyRequestsSchema)
  .describe(
    "Слишком много запросов одновременно отправляется в API. Повторите запрос позже.",
  );

export const getRefundsRefundIdQueryResponseSchema = z.lazy(
  () => getRefundsRefundId200Schema,
);
