/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Данные отраслевого реквизита.
 */
export const industryDetailsSchema = z
  .object({
    federal_id: z
      .string()
      .regex(/(^00[1-9]{1}$)|(^0[1-6]{1}[0-9]{1}$)|(^07[0-3]{1}$)/)
      .describe(
        "Идентификатор федерального органа исполнительной власти (тег в 54 ФЗ — 1262).",
      ),
    document_date: z.iso
      .date()
      .describe(
        "Дата документа основания (тег в 54 ФЗ — 1263). Передается в формате ISO 8601: https://en.wikipedia.org/wiki/ISO_8601",
      ),
    document_number: z
      .string()
      .max(32)
      .describe(
        "Номер нормативного акта федерального органа исполнительной власти, регламентирующего порядок заполнения реквизита «значение отраслевого реквизита» (тег в 54 ФЗ — 1264).",
      ),
    value: z
      .string()
      .max(256)
      .describe("Значение отраслевого реквизита (тег в 54 ФЗ — 1265)."),
  })
  .describe("Данные отраслевого реквизита.");
