/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { bankCardExpiryMonthSchema } from "./bank-card-expiry-month-schema.ts";
import { bankCardExpiryYearSchema } from "./bank-card-expiry-year-schema.ts";
import { bankCardFirst6Schema } from "./bank-card-first6-schema.ts";
import { bankCardLast4Schema } from "./bank-card-last4-schema.ts";
import { bankCardTypeSchema } from "./bank-card-type-schema.ts";

/**
 * @description Данные банковской карты.
 */
export const invoicingBankCardDataSchema = z
  .object({
    get first6() {
      return bankCardFirst6Schema.and(z.any());
    },
    get last4() {
      return bankCardLast4Schema.describe("Последние 4 цифры номера карты.");
    },
    get expiry_year() {
      return bankCardExpiryYearSchema.describe("Срок действия, год, YYYY.");
    },
    get expiry_month() {
      return bankCardExpiryMonthSchema.describe("Срок действия, месяц, MM.");
    },
    get card_type() {
      return bankCardTypeSchema.describe(
        "Тип банковской карты. Возможные значения: MasterCard (для карт Mastercard и Maestro), Visa (для карт Visa и Visa Electron), Mir, UnionPay, JCB, AmericanExpress, DinersClub, DiscoverCard, InstaPayment, InstaPaymentTM, Laser, Dankort, Solo, Switch и Unknown.",
      );
    },
  })
  .describe("Данные банковской карты.");
