/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Код бюджетной классификации (КБК).
 */
export const kbkSchema = z
  .string()
  .min(1)
  .max(20)
  .regex(/([\d]{20})|(0)/)
  .describe("Код бюджетной классификации (КБК).");
