/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Код товара (тег в 54 ФЗ — 1163). Обязательный параметр, если одновременно выполняются эти условия: * вы используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2; * товар нужно маркировать: http://docs.cntd.ru/document/902192509. Должно быть заполнено хотя бы одно поле.
 */
export const markCodeInfoSchema = z
  .object({
    mark_code_raw: z.optional(
      z
        .string()
        .describe(
          "Код товара в том виде, в котором он был прочитан сканером (тег в 54 ФЗ — 2000). Нужно передавать, если используете онлайн-кассу Orange Data. Пример: 010460406000590021N4N57RTCBUZTQ\\u001d2403054002410161218\\u001d1424010191ffd0\\u001g92tIAF/YVpU4roQS3M/m4z78yFq0nc/WsSmLeX6QkF/YVWwy5IMYAeiQ91Xa2m/fFSJcOkb2N+uUUtfr4n0mOX0Q==",
        ),
    ),
    unknown: z.optional(
      z
        .string()
        .min(1)
        .max(32)
        .describe("Нераспознанный код товара (тег в 54 ФЗ — 1300)."),
    ),
    ean_8: z.optional(
      z
        .string()
        .min(8)
        .max(8)
        .describe("Код товара в формате EAN-8 (тег в 54 ФЗ — 1301)."),
    ),
    ean_13: z.optional(
      z
        .string()
        .min(13)
        .max(13)
        .describe("Код товара в формате EAN-13 (тег в 54 ФЗ — 1302)."),
    ),
    itf_14: z.optional(
      z
        .string()
        .min(14)
        .max(14)
        .describe("Код товара в формате ITF-14 (тег в 54 ФЗ — 1303)."),
    ),
    gs_10: z.optional(
      z
        .string()
        .min(1)
        .max(38)
        .describe(
          "Код товара в формате GS1.0 (тег в 54 ФЗ — 1304). Можно передавать, если используете онлайн-кассу Orange Data, aQsi, Кит Инвест, АТОЛ Онлайн.",
        ),
    ),
    gs_1m: z.optional(
      z
        .string()
        .min(1)
        .max(200)
        .describe("Код товара в формате GS1.M (тег в 54 ФЗ — 1305)."),
    ),
    short: z.optional(
      z
        .string()
        .min(1)
        .max(38)
        .describe(
          "Код товара в формате короткого кода маркировки (тег в 54 ФЗ — 1306).",
        ),
    ),
    fur: z.optional(
      z
        .string()
        .min(20)
        .max(20)
        .describe(
          "Контрольно-идентификационный знак мехового изделия (тег в 54 ФЗ — 1307).",
        ),
    ),
    egais_20: z.optional(
      z
        .string()
        .min(33)
        .max(33)
        .describe("Код товара в формате ЕГАИС-2.0 (тег в 54 ФЗ — 1308)."),
    ),
    egais_30: z.optional(
      z
        .string()
        .min(14)
        .max(14)
        .describe("Код товара в формате ЕГАИС-3.0 (тег в 54 ФЗ — 1309)."),
    ),
  })
  .describe(
    "Код товара (тег в 54 ФЗ — 1163). Обязательный параметр, если одновременно выполняются эти условия: * вы используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2; * товар нужно маркировать: http://docs.cntd.ru/document/902192509. Должно быть заполнено хотя бы одно поле.",
  );
