/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Идентификатор покупателя в вашей системе, например электронная почта или номер телефона. Не более 200 символов.
 */
export const merchantCustomerIdSchema = z
  .string()
  .max(200)
  .describe(
    "Идентификатор покупателя в вашей системе, например электронная почта или номер телефона. Не более 200 символов.",
  );
