/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { bankCardDataSchema } from "./bank-card-data-schema.ts";
import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата банковской картой.
 */
export const paymentMethodBankCardSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("bank_card"),
    }),
  )
  .and(
    z.object({
      get card() {
        return bankCardDataSchema
          .describe("Данные банковской карты.")
          .optional();
      },
      type: z.enum(["bank_card"]),
    }),
  )
  .describe("Оплата банковской картой.");
