/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата через сервис «Плати частями».
 */
export const paymentMethodSberBnplSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("sber_bnpl"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["sber_bnpl"]),
    }),
  )
  .describe("Оплата через сервис «Плати частями».");
