/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { confirmationUrlSchema } from "./confirmation-url-schema.ts";
import { enforceSchema } from "./enforce-schema.ts";
import { paymentMethodsConfirmationSchema } from "./payment-methods-confirmation-schema.ts";
import { returnUrlSchema } from "./return-url-schema.ts";

/**
 * @description Перенаправление пользователя на сайт ЮKassa для подтверждения привязки или страницу банка-эмитента для аутентификации по 3-D Secure.
 */
export const paymentMethodsConfirmationRedirectSchema = z
  .lazy(() => paymentMethodsConfirmationSchema)
  .and(
    z.object({
      type: z.literal("redirect"),
    }),
  )
  .and(
    z.object({
      get confirmation_url() {
        return confirmationUrlSchema.describe(
          "URL, на который необходимо перенаправить пользователя для подтверждения оплаты.",
        );
      },
      get enforce() {
        return enforceSchema
          .default(false)
          .describe(
            "Запрос на проведение платежа с аутентификацией по 3-D Secure. Будет работать, если оплату банковской картой вы по умолчанию принимаете без подтверждения платежа пользователем. В остальных случаях аутентификацией по 3-D Secure будет управлять ЮKassa. Если хотите принимать платежи без дополнительного подтверждения пользователем, напишите вашему менеджеру ЮKassa.",
          )
          .optional();
      },
      get return_url() {
        return returnUrlSchema
          .describe(
            "URL, на который вернется пользователь после подтверждения или отмены платежа на веб-странице. Не более 2048 символов.",
          )
          .optional();
      },
      type: z.enum(["redirect"]),
    }),
  )
  .describe(
    "Перенаправление пользователя на сайт ЮKassa для подтверждения привязки или страницу банка-эмитента для аутентификации по 3-D Secure.",
  );
