/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const paymentOverviewStatementDeliveryMethodTypeSchema = z.enum([
  "email",
]);
