/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodDataSchema } from "./payment-method-data-schema.ts";

/**
 * @description Данные для оплаты через СБП
 */
export const paymentMethodDataSbpSchema = z
  .lazy(() => paymentMethodDataSchema)
  .and(
    z.object({
      type: z.literal("sbp"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["sbp"]),
    }),
  )
  .describe("Данные для оплаты через СБП");
