/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";
import { sbpOperationIdSchema } from "./sbp-operation-id-schema.ts";
import { sbpPayerBankDetailsSchema } from "./sbp-payer-bank-details-schema.ts";

/**
 * @description Оплата через СБП (Система быстрых платежей ЦБ РФ).
 */
export const paymentMethodSbpSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("sbp"),
    }),
  )
  .and(
    z.object({
      get sbp_operation_id() {
        return sbpOperationIdSchema
          .describe(
            "Идентификатор операции в СБП (НСПК). Пример: 1027088AE4CB48CB81287833347A8777.",
          )
          .optional();
      },
      get payer_bank_details() {
        return sbpPayerBankDetailsSchema
          .describe(
            "Реквизиты счета, который использовался для оплаты. Обязательный параметр для платежей в статусе succeeded. В остальных случаях может отсутствовать.",
          )
          .optional();
      },
      type: z.enum(["sbp"]),
    }),
  )
  .describe("Оплата через СБП (Система быстрых платежей ЦБ РФ).");
