/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { bankCardDataSchema } from "./bank-card-data-schema.ts";
import { electronicCertificateApprovedPaymentArticleSchema } from "./electronic-certificate-approved-payment-article-schema.ts";
import { electronicCertificatePaymentSchema } from "./electronic-certificate-payment-schema.ts";
import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата по электронному сертификату.
 */
export const paymentMethodElectronicCertificateSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("electronic_certificate"),
    }),
  )
  .and(
    z.object({
      get card() {
        return bankCardDataSchema.and(z.any()).optional();
      },
      get electronic_certificate() {
        return electronicCertificatePaymentSchema
          .describe(
            "Данные от ФЭС НСПК для оплаты по электронному сертификату.",
          )
          .optional();
      },
      get articles() {
        return z
          .array(
            electronicCertificateApprovedPaymentArticleSchema.describe(
              "Товарная позиция в одобренной корзине покупки при оплате по электронному сертификату.",
            ),
          )
          .describe(
            "Одобренная корзина покупки — список товаров, одобренных к оплате по электронному сертификату. Присутствует только при оплате на готовой странице ЮKassa: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/other/electronic-certificate/ready-made-payment-form.",
          )
          .optional();
      },
      type: z.enum(["electronic_certificate"]),
    }),
  )
  .describe("Оплата по электронному сертификату.");
