/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { B2BSberbankCalculatedVatDataSchema } from "./b2-b-sberbank-calculated-vat-data-schema.ts";
import { B2BSberbankMixedVatDataSchema } from "./b2-b-sberbank-mixed-vat-data-schema.ts";
import { B2BSberbankPayerBankDetailsSchema } from "./b2-b-sberbank-payer-bank-details-schema.ts";
import { B2BSberbankVatDataSchema } from "./b2-b-sberbank-vat-data-schema.ts";
import { paymentMethodSchema } from "./payment-method-schema.ts";
import { paymentPurposeSchema } from "./payment-purpose-schema.ts";

/**
 * @description Оплата через Сбербанк Бизнес Онлайн.
 */
export const paymentMethodB2BSberbankSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("b2b_sberbank"),
    }),
  )
  .and(
    z.object({
      get payment_purpose() {
        return paymentPurposeSchema.describe(
          "Назначение платежа (не больше 210 символов).",
        );
      },
      get vat_data() {
        return z.union([
          B2BSberbankCalculatedVatDataSchema,
          B2BSberbankVatDataSchema,
          B2BSberbankMixedVatDataSchema,
        ]);
      },
      get payer_bank_details() {
        return B2BSberbankPayerBankDetailsSchema.describe(
          "Банковские реквизиты плательщика (юридического лица или ИП).",
        ).optional();
      },
      type: z.enum(["b2b_sberbank"]),
    }),
  )
  .describe("Оплата через Сбербанк Бизнес Онлайн.");
