/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { dealIdSchema } from "./deal-id-schema.ts";
import { settlementPaymentArraySchema } from "./settlement-payment-array-schema.ts";

export const paymentDealInfoSchema = z.object({
  get id() {
    return dealIdSchema.describe("Идентификатор сделки.");
  },
  get settlements() {
    return settlementPaymentArraySchema.describe(
      "Данные о распределении денег.",
    );
  },
});
