/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentOverviewStatementDeliveryMethodTypeSchema } from "./payment-overview-statement-delivery-method-type-schema.ts";

/**
 * @description Данные о выбранном способе доставки справки.
 */
export const paymentOverviewStatementDeliveryMethodSchema = z
  .object({
    get type() {
      return paymentOverviewStatementDeliveryMethodTypeSchema;
    },
  })
  .describe("Данные о выбранном способе доставки справки.");
