/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата через Apple Pay.
 */
export const paymentMethodApplePaySchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("apple_pay"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["apple_pay"]),
    }),
  )
  .describe("Оплата через Apple Pay.");
