/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Commentary to the canceled status: who and why canceled the payment. More about canceled payments: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments
 */
export const paymentCancellationDetailsSchema = z
  .object({
    party: z
      .enum(["yoo_money", "payment_network", "merchant"])
      .describe(
        "The participant of the payment process that made the decision to cancel the payment. Possible values are yoo_money, payment_network, and merchant. More about initiators of payment cancelation: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments#cancellation-details-party",
      ),
    reason: z
      .enum([
        "3d_secure_failed",
        "call_issuer",
        "card_expired",
        "payment_method_limit_exceeded",
        "payment_method_restricted",
        "country_forbidden",
        "general_decline",
        "fraud_suspected",
        "identification_required",
        "insufficient_funds",
        "invalid_card_number",
        "invalid_csc",
        "issuer_unavailable",
        "canceled_by_merchant",
        "permission_revoked",
        "internal_timeout",
        "expired_on_confirmation",
        "expired_on_capture",
        "unsupported_mobile_operator",
        "deal_expired",
      ])
      .describe(
        "Reason behind the cancelation. The list and descriptions of possible values: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments#cancellation-details-reason",
      ),
  })
  .describe(
    "Commentary to the canceled status: who and why canceled the payment. More about canceled payments: https://yookassa.ru/developers/payment-acceptance/after-the-payment/declined-payments",
  );
