/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата с баланса мобильного телефона.
 */
export const paymentMethodMobileBalanceSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("mobile_balance"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["mobile_balance"]),
    }),
  )
  .describe("Оплата с баланса мобильного телефона.");
