/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Payments in cash via payment kiosks.
 */
export const paymentMethodCashSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("cash"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["cash"]),
    }),
  )
  .describe("Payments in cash via payment kiosks.");
