/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата через Google Pay.
 */
export const paymentMethodGooglePaySchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("google_pay"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["google_pay"]),
    }),
  )
  .describe("Оплата через Google Pay.");
