/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Saved payment method: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/basics\'s ID.
 */
export const paymentMethodIdSchema = z
  .string()
  .describe(
    "Saved payment method: https://yookassa.ru/developers/payment-acceptance/scenario-extensions/recurring-payments/basics's ID.",
  );
