/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { cardRequestDataSchema } from "./card-request-data-schema.ts";
import { paymentMethodDataSchema } from "./payment-method-data-schema.ts";

/**
 * @description Данные для оплаты банковской картой.
 */
export const paymentMethodDataBankCardSchema = z
  .lazy(() => paymentMethodDataSchema)
  .and(
    z.object({
      type: z.literal("bank_card"),
    }),
  )
  .and(
    z.object({
      get card() {
        return cardRequestDataSchema
          .describe(
            "Данные банковской карты (необходимы, если вы собираете данные карты пользователей на своей стороне).",
          )
          .optional();
      },
      type: z.enum(["bank_card"]),
    }),
  )
  .describe("Данные для оплаты банковской картой.");
