/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { emailSchema } from "./email-schema.ts";
import { paymentOverviewStatementDeliveryMethodSchema } from "./payment-overview-statement-delivery-method-schema.ts";

/**
 * @description Cпособ доставки справки.
 */
export const paymentOverviewStatementEmailDeliveryMethodSchema = z
  .lazy(() => paymentOverviewStatementDeliveryMethodSchema)
  .and(
    z.object({
      type: z.literal("email"),
    }),
  )
  .and(
    z.object({
      get email() {
        return emailSchema.and(z.any());
      },
      type: z.enum(["email"]),
    }),
  )
  .describe("Cпособ доставки справки.");
