/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Payment method code is the type of a means of payment used for paying. More about payment methods: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-methods
 */
export const paymentMethodTypeSchema = z
  .enum([
    "bank_card",
    "cash",
    "alfabank",
    "webmoney",
    "wechat",
    "apple_pay",
    "google_pay",
    "qiwi",
    "installments",
    "yoo_money",
    "sberbank",
    "mobile_balance",
    "b2b_sberbank",
    "tinkoff_bank",
    "sbp",
    "sber_loan",
    "electronic_certificate",
    "sber_bnpl",
  ])
  .describe(
    "Payment method code is the type of a means of payment used for paying. More about payment methods: https://yookassa.ru/developers/payment-acceptance/getting-started/payment-methods",
  );
