/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodDataSchema } from "./payment-method-data-schema.ts";

/**
 * @description Данные для оплаты через SberPay.
 */
export const paymentMethodDataSberbankSchema = z
  .lazy(() => paymentMethodDataSchema)
  .and(
    z.object({
      type: z.literal("sberbank"),
    }),
  )
  .and(
    z.object({
      phone: z.optional(
        z
          .string()
          .regex(/[0-9]{4,15}/)
          .describe(
            "Телефон пользователя, на который зарегистрирован аккаунт в SberPay. Необходим для подтверждения оплаты по смс (сценарий подтверждения external). Указывается в формате ITU-T E.164: https://ru.wikipedia.org/wiki/E.164, например 79000000000.",
          ),
      ),
      type: z.enum(["sberbank"]),
    }),
  )
  .describe("Данные для оплаты через SberPay.");
