/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Data for making payments using a certain method: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/basics#integration-options (payment_method). You can send the request without this object. If you do so, the user will be able to select the payment method on the YooMoney\'s side.
 */
export const paymentMethodDataSbpSchema = z
  .object({
    type: z.enum([
      "bank_card",
      "cash",
      "sberbank",
      "tinkoff_bank",
      "yoo_money",
      "mobile_balance",
      "b2b_sberbank",
      "sbp",
      "sber_loan",
      "electronic_certificate",
      "sber_bnpl",
    ]),
  })
  .describe(
    "Data for making payments using a certain method: https://yookassa.ru/developers/payment-acceptance/integration-scenarios/manual-integration/basics#integration-options (payment_method). You can send the request without this object. If you do so, the user will be able to select the payment method on the YooMoney's side.",
  );
