/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата через Альфа-Клик.
 */
export const paymentMethodAlfabankSchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("alfabank"),
    }),
  )
  .and(
    z.object({
      login: z.optional(
        z
          .string()
          .describe(
            "Логин пользователя в Альфа-Клике (привязанный телефон или дополнительный логин).",
          ),
      ),
      type: z.enum(["alfabank"]),
    }),
  )
  .describe("Оплата через Альфа-Клик.");
