/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Банк получателя платежа.
 */
export const paymentOrderBankUtilitiesSchema = z
  .object({
    name: z
      .string()
      .max(45)
      .describe("Name of the recipient's bank. Maximum of 45 characters."),
    bic: z
      .string()
      .regex(/[0-9]{9}/)
      .describe("БИК банка получателя."),
    account: z.string().describe("Счет получателя в банке."),
    correspondent_account: z
      .string()
      .describe("Корреспондентский счет банка получателя."),
  })
  .describe("Банк получателя платежа.");
