/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodDataSchema } from "./payment-method-data-schema.ts";

/**
 * @description Data for processing a payment made via the YooMoney wallet.
 */
export const paymentMethodDataYooMoneySchema = z
  .lazy(() => paymentMethodDataSchema)
  .and(
    z.object({
      type: z.literal("yoo_money"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["yoo_money"]),
    }),
  )
  .describe("Data for processing a payment made via the YooMoney wallet.");
