/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentMethodSchema } from "./payment-method-schema.ts";

/**
 * @description Оплата из кошелька WebMoney.
 */
export const paymentMethodWebmoneySchema = z
  .lazy(() => paymentMethodSchema)
  .and(
    z.object({
      type: z.literal("webmoney"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["webmoney"]),
    }),
  )
  .describe("Оплата из кошелька WebMoney.");
