/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestSchema } from "./bad-request-schema.ts";
import { forbiddenSchema } from "./forbidden-schema.ts";
import { invalidCredentialsSchema } from "./invalid-credentials-schema.ts";
import { savePaymentMethodBankCardSchema } from "./save-payment-method-bank-card-schema.ts";
import { savePaymentMethodDataBankCardSchema } from "./save-payment-method-data-bank-card-schema.ts";
import { tooManyRequestsSchema } from "./too-many-requests-schema.ts";

export const postPaymentMethodsHeaderParamsSchema = z.object({
  "Idempotence-Key": z
    .string()
    .max(64)
    .regex(/[0-9a-zA-Z+-_.]{1,64}/)
    .default("2e1da982-1bb1-41f0-b9cf-758cc8bcf069"),
});

/**
 * @description Запрос успешно обработан
 */
export const postPaymentMethods200Schema = z.lazy(
  () => savePaymentMethodBankCardSchema,
);

/**
 * @description Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.
 */
export const postPaymentMethods400Schema = z
  .lazy(() => badRequestSchema)
  .describe(
    "Запрос не может быть обработан. Причиной может быть неправильный синтаксис запроса, ошибка в обязательных параметрах запроса, их отсутствие или неподдерживаемый метод.",
  );

/**
 * @description В заголовке Authorization указан неверный ключ.
 */
export const postPaymentMethods401Schema = z
  .lazy(() => invalidCredentialsSchema)
  .describe("В заголовке Authorization указан неверный ключ.");

/**
 * @description Секретный ключ указан верно, но не хватает прав для совершения операции.
 */
export const postPaymentMethods403Schema = z
  .lazy(() => forbiddenSchema)
  .describe(
    "Секретный ключ указан верно, но не хватает прав для совершения операции.",
  );

/**
 * @description Слишком много запросов одновременно отправляется в API. Повторите запрос позже.
 */
export const postPaymentMethods429Schema = z
  .lazy(() => tooManyRequestsSchema)
  .describe(
    "Слишком много запросов одновременно отправляется в API. Повторите запрос позже.",
  );

/**
 * @description Внутренняя ошибка сервера ЮKassa.
 */
export const postPaymentMethods500Schema = z
  .lazy(() => tooManyRequestsSchema)
  .describe(
    "Слишком много запросов одновременно отправляется в API. Повторите запрос позже.",
  );

export const postPaymentMethodsMutationRequestSchema = z.lazy(
  () => savePaymentMethodDataBankCardSchema,
);

export const postPaymentMethodsMutationResponseSchema = z.lazy(
  () => postPaymentMethods200Schema,
);
