/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Признак предмета расчета (тег в 54 ФЗ — 1212) — это то, за что принимается оплата, например товар, услуга. Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#payment-subject * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#payment-subject
 */
export const receiptItemPaymentSubjectSchema = z
  .enum([
    "commodity",
    "excise",
    "job",
    "service",
    "gambling_bet",
    "gambling_prize",
    "lottery",
    "lottery_prize",
    "intellectual_activity",
    "payment",
    "agent_commission",
    "property_right",
    "non_operating_gain",
    "insurance_premium",
    "sales_tax",
    "resort_fee",
    "composite",
    "another",
    "fine",
    "tax",
    "lien",
    "cost",
    "pension_insurance_without_payouts",
    "pension_insurance_with_payouts",
    "health_insurance_without_payouts",
    "health_insurance_with_payouts",
    "health_insurance",
    "casino",
    "agent_withdrawals",
    "non_marked_excise",
    "marked_excise",
    "marked",
    "non_marked",
  ])
  .describe(
    "Признак предмета расчета (тег в 54 ФЗ — 1212) — это то, за что принимается оплата, например товар, услуга. Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#payment-subject * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#payment-subject",
  );
