/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { industryDetailsSchema } from "./industry-details-schema.ts";
import { operationalDetailsSchema } from "./operational-details-schema.ts";
import { receiptDataCustomerSchema } from "./receipt-data-customer-schema.ts";
import { receiptDataItemSchema } from "./receipt-data-item-schema.ts";
import { taxSystemCodeSchema } from "./tax-system-code-schema.ts";

/**
 * @description Data for creating a receipt. The parameter is specified if: you are a company or a sole proprietor, and you use Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/basics; you are a company or a sole proprietor, and you use the third-party sales register: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics and send data for creating receipts under one of the following scenarios: Payment and receipt at the same time: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics#payment-and-receipt or Payment after receipt: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics#payment-after-receipt.
 */
export const receiptDataSchema = z
  .object({
    get customer() {
      return receiptDataCustomerSchema
        .describe(
          "Информация о пользователе. Необходимо указать как минимум контактные данные: для Чеков от ЮKassa — электронную почту (customer.email), в остальных случаях — электронную почту (customer.email) или номер телефона (customer.phone).",
        )
        .optional();
    },
    get items() {
      return z
        .array(
          receiptDataItemSchema.describe(
            "Информация о товарной позиции в заказе. Используется для формирования чека.",
          ),
        )
        .describe(
          "List of products in an order. If you use Receipts from YooMoney, you can specify up to 80 items. If you use a third-party online sales register, you can specify up to 100 items.",
        );
    },
    internet: z.optional(
      z
        .boolean()
        .describe(
          "Признак проведения платежа в интернете (тег в 54 ФЗ — 1125) — указывает на оплату через интернет. Возможные значения: true — оплата прошла онлайн, через интернет (например, на вашем сайте или в приложении); false — оплата прошла офлайн, при личном взаимодействии (например, в торговой точке или при встрече с курьером). По умолчанию true. Если вы принимаете платежи офлайн, передайте в запросе значение false.",
        ),
    ),
    get tax_system_code() {
      return taxSystemCodeSchema
        .describe(
          "Система налогообложения магазина (тег в 54 ФЗ — 1055). Для сторонних онлайн-касс: обязательный параметр, если вы используете онлайн-кассу Атол Онлайн, обновленную до ФФД 1.2, или у вас несколько систем налогообложения, в остальных случаях не передается. Перечень возможных значений: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#tax-systems Для Чеков от ЮKassa: параметр передавать не нужно, ЮKassa его проигнорирует.",
        )
        .optional();
    },
    timezone: z.optional(
      z
        .int()
        .min(1)
        .max(11)
        .describe(
          "Номер часовой зоны для адреса, по которому вы принимаете платежи (тег в 54 ФЗ — 1011). Указывается, только если в чеке есть товары, которые подлежат обязательной маркировке (в items.mark_code_info передается параметр gs_1m, short или fur). Перечень возможных значений: для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#timezone; для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#timezone.",
        ),
    ),
    get receipt_industry_details() {
      return z
        .array(industryDetailsSchema.describe("Данные отраслевого реквизита."))
        .describe(
          "Отраслевой реквизит чека (тег в 54 ФЗ — 1261). Можно передавать, если используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2.",
        )
        .optional();
    },
    get receipt_operational_details() {
      return operationalDetailsSchema.and(z.any()).optional();
    },
  })
  .describe(
    "Data for creating a receipt. The parameter is specified if: you are a company or a sole proprietor, and you use Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/basics; you are a company or a sole proprietor, and you use the third-party sales register: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics and send data for creating receipts under one of the following scenarios: Payment and receipt at the same time: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics#payment-and-receipt or Payment after receipt: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/basics#payment-after-receipt.",
  );
