/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { emailSchema } from "./email-schema.ts";
import { phoneSchema } from "./phone-schema.ts";
import { russianItnSchema } from "./russian-itn-schema.ts";

/**
 * @description Информация о пользователе. Необходимо указать как минимум контактные данные: для Чеков от ЮKassa — электронную почту (customer.email), в остальных случаях — электронную почту (customer.email) или номер телефона (customer.phone).
 */
export const receiptDataCustomerSchema = z
  .object({
    full_name: z.optional(
      z
        .string()
        .describe(
          "Для юрлица — название организации, для ИП и физического лица — ФИО. Если у физлица отсутствует ИНН, в этом же параметре передаются паспортные данные. Не более 256 символов. Можно передавать, если используете Чеки от ЮKassa или онлайн-кассу Orange Data, Атол Онлайн.",
        ),
    ),
    get inn() {
      return russianItnSchema.and(z.any()).optional();
    },
    get email() {
      return emailSchema.and(z.any()).optional();
    },
    get phone() {
      return phoneSchema.and(z.any()).optional();
    },
  })
  .describe(
    "Информация о пользователе. Необходимо указать как минимум контактные данные: для Чеков от ЮKassa — электронную почту (customer.email), в остальных случаях — электронную почту (customer.email) или номер телефона (customer.phone).",
  );
