/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { markCodeInfoSchema } from "./mark-code-info-schema.ts";
import { markModeSchema } from "./mark-mode-schema.ts";
import { markQuantitySchema } from "./mark-quantity-schema.ts";
import { monetaryAmountSchema } from "./monetary-amount-schema.ts";
import { receiptItemCountryOfOriginCodeSchema } from "./receipt-item-country-of-origin-code-schema.ts";
import { receiptItemCustomsDeclarationNumberSchema } from "./receipt-item-customs-declaration-number-schema.ts";
import { receiptItemDescriptionSchema } from "./receipt-item-description-schema.ts";
import { receiptItemExciseSchema } from "./receipt-item-excise-schema.ts";
import { receiptItemMeasureSchema } from "./receipt-item-measure-schema.ts";
import { receiptItemPaymentModeSchema } from "./receipt-item-payment-mode-schema.ts";
import { receiptItemPaymentSubjectIndustryDetailsSchema } from "./receipt-item-payment-subject-industry-details-schema.ts";
import { receiptItemPaymentSubjectSchema } from "./receipt-item-payment-subject-schema.ts";
import { receiptItemPlannedStatusSchema } from "./receipt-item-planned-status-schema.ts";
import { receiptItemProductCodeSchema } from "./receipt-item-product-code-schema.ts";
import { receiptItemQuantitySchema } from "./receipt-item-quantity-schema.ts";
import { receiptItemVatCodeSchema } from "./receipt-item-vat-code-schema.ts";

/**
 * @description Информация о товарной позиции в заказе. Используется для формирования чека.
 */
export const receiptDataItemSchema = z
  .object({
    get description() {
      return receiptItemDescriptionSchema.describe(
        "Название товара (от 1 до 128 символов). Тег в 54 ФЗ — 1030.",
      );
    },
    get amount() {
      return monetaryAmountSchema.describe("Сумма в выбранной валюте.");
    },
    get vat_code() {
      return receiptItemVatCodeSchema.describe(
        "Ставка НДС (тег в 54 ФЗ — 1199). Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#vat-codes * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#vat-codes",
      );
    },
    get quantity() {
      return receiptItemQuantitySchema.describe(
        "Product quantity (tag 1023 in 54-FZ). You can set an integer or a decimal value. The decimal separator is a dot; there is no thousands separator. The maximum possible value and the maximum number of digits after the decimal separator (for decimal values) depend on the model of your online sales register. For Receipts from YooMoney, the maximum possible value is 99999.999, with no more than 3 digits after the decimal separator.",
      );
    },
    get measure() {
      return receiptItemMeasureSchema
        .describe(
          "Мера количества предмета расчета (тег в 54 ФЗ — 2108) — единица измерения товара, например штуки, граммы. Обязательный параметр, если используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2. Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#measure * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#measure",
        )
        .optional();
    },
    get mark_quantity() {
      return markQuantitySchema
        .describe(
          "Дробное количество маркированного товара (тег в 54 ФЗ — 1291). Обязательный параметр, если одновременно выполняются эти условия: * вы используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2; * товар нужно маркировать: http://docs.cntd.ru/document/902192509; * поле measure имеет значение piece. Пример: вы продаете поштучно карандаши. Они поставляются пачками по 100 штук с одним кодом маркировки. При продаже одного карандаша нужно в numerator передать 1, а в denominator — 100.",
        )
        .optional();
    },
    get payment_subject() {
      return receiptItemPaymentSubjectSchema
        .describe(
          "Признак предмета расчета (тег в 54 ФЗ — 1212) — это то, за что принимается оплата, например товар, услуга. Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#payment-subject * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#payment-subject",
        )
        .optional();
    },
    get payment_mode() {
      return receiptItemPaymentModeSchema
        .describe(
          "Признак способа расчета (тег в 54 ФЗ — 1214) — отражает тип оплаты и факт передачи товара. Пример: покупатель полностью оплачивает товар и сразу получает его. В этом случае нужно передать значение full_payment (полный расчет). Перечень возможных значений: * для Чеков от ЮKassa: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#payment-mode * для сторонних онлайн-касс: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#payment-mode",
        )
        .optional();
    },
    get country_of_origin_code() {
      return receiptItemCountryOfOriginCodeSchema
        .describe(
          "Код страны происхождения товара по общероссийскому классификатору стран мира (OК (MК (ИСО 3166) 004-97) 025-2001: http://docs.cntd.ru/document/842501280). Тег в 54 ФЗ — 1230. Пример: RU. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.",
        )
        .optional();
    },
    get customs_declaration_number() {
      return receiptItemCustomsDeclarationNumberSchema
        .describe(
          "Номер таможенной декларации (от 1 до 32 символов). Тег в 54 ФЗ — 1231. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.",
        )
        .optional();
    },
    get excise() {
      return receiptItemExciseSchema
        .describe(
          "Сумма акциза товара с учетом копеек (тег в 54 ФЗ — 1229). Десятичное число с точностью до 2 знаков после точки. Можно передавать, если используете онлайн-кассу Orange Data, Кит Инвест.",
        )
        .optional();
    },
    get product_code() {
      return receiptItemProductCodeSchema
        .describe(
          "Product code (tag 1162 in 54-FZ) is a unique number assigned to a unit of product during marking process. Format: hexadecimal number with spaces. Maximum length is 32 bytes. Example: 00 00 00 01 00 21 FA 41 00 23 05 41 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 12 00 AB 00. This parameter is required if both conditions apply: your online sales register is updated to FFD 1.05 or 1.1; the product is subject to mandatory marking: http://docs.cntd.ru/document/902192509. The parameter must not be included in the request if you are using Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/basics or an online sales register updated to FFD 1.2: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/marking.",
        )
        .optional();
    },
    get planned_status() {
      return receiptItemPlannedStatusSchema
        .describe(
          "Planned product status. Tag in 54-FZ: 2003. To be specified only for products that are subject to mandatory marking (parameter gs_1m, short, or fur is set in items.mark_code_info). Possible values are: for Receipts from YooMoney: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/yoomoney/parameters-values#planned-status; for third party online sales registers: https://yookassa.ru/developers/payment-acceptance/receipts/54fz/other-services/parameters-values#planned-status.",
        )
        .optional();
    },
    get mark_code_info() {
      return markCodeInfoSchema
        .describe(
          "Код товара (тег в 54 ФЗ — 1163). Обязательный параметр, если одновременно выполняются эти условия: * вы используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2; * товар нужно маркировать: http://docs.cntd.ru/document/902192509. Должно быть заполнено хотя бы одно поле.",
        )
        .optional();
    },
    get mark_mode() {
      return markModeSchema
        .describe(
          "Режим обработки кода маркировки (тег в 54 ФЗ — 2102). Обязательный параметр, если одновременно выполняются эти условия: * вы используете Чеки от ЮKassa или онлайн-кассу Атол Онлайн или BusinessRu, обновленную до ФФД 1.2; * товар нужно маркировать: http://docs.cntd.ru/document/902192509. Должен принимать значение равное «0».",
        )
        .optional();
    },
    get payment_subject_industry_details() {
      return receiptItemPaymentSubjectIndustryDetailsSchema
        .describe(
          "Отраслевой реквизит предмета расчета (тег в 54 ФЗ — 1260). Можно передавать, если используете Чеки от ЮKassa или онлайн-кассу, обновленную до ФФД 1.2.",
        )
        .optional();
    },
  })
  .describe(
    "Информация о товарной позиции в заказе. Используется для формирования чека.",
  );
