/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { phoneSchema } from "./phone-schema.ts";
import { receiverSchema } from "./receiver-schema.ts";

/**
 * @description Реквизиты для пополнения баланса телефона.
 */
export const receiverMobileBalanceSchema = z
  .lazy(() => receiverSchema)
  .and(
    z.object({
      type: z.literal("mobile_balance"),
    }),
  )
  .and(
    z.object({
      get phone() {
        return phoneSchema.and(z.any()).and(z.any());
      },
      type: z.enum(["mobile_balance"]),
    }),
  )
  .describe("Реквизиты для пополнения баланса телефона.");
