/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { gatewayIdSchema } from "./gateway-id-schema.ts";

/**
 * @description Получатель платежа. Нужен, если вы разделяете потоки платежей в рамках одного аккаунта или создаете платеж в адрес другого аккаунта.
 */
export const recipientSchema = z
  .object({
    get gateway_id() {
      return gatewayIdSchema.describe(
        "Идентификатор субаккаунта. Используется для разделения потоков платежей в рамках одного аккаунта.",
      );
    },
  })
  .describe(
    "Получатель платежа. Нужен, если вы разделяете потоки платежей в рамках одного аккаунта или создаете платеж в адрес другого аккаунта.",
  );
