/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { refundMethodTypeSchema } from "./refund-method-type-schema.ts";

/**
 * @description Детали возврата. Зависят от способа оплаты, который использовался при проведении платежа.
 */
export const refundMethodSchema = z
  .object({
    get type() {
      return refundMethodTypeSchema.describe(
        "Код способа оплаты, который использовался при проведении платежа.",
      );
    },
  })
  .describe(
    "Детали возврата. Зависят от способа оплаты, который использовался при проведении платежа.",
  );
