/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Комментарий к статусу canceled: кто отменил возврат и по какой причине.
 */
export const refundCancellationDetailsSchema = z
  .object({
    party: z
      .enum(["yoo_money", "refund_network"])
      .describe(
        "Участник процесса возврата, который принял решение отменить транзакцию. Перечень и описание возможных значений: https://yookassa.ru/developers/payment-acceptance/after-the-payment/refunds#declined-refunds-cancellation-details-party",
      ),
    reason: z
      .enum([
        "yoo_money_account_closed",
        "insufficient_funds",
        "general_decline",
        "rejected_by_payee",
        "rejected_by_timeout",
        "payment_basket_id_not_found",
        "payment_article_number_not_found",
        "payment_tru_code_not_found",
        "too_many_refunding_articles",
        "some_articles_already_refunded",
      ])
      .describe(
        "Причина отмены возврата. Перечень и описание возможных значений: https://yookassa.ru/developers/payment-acceptance/after-the-payment/refunds#declined-refunds-cancellation-details-reason",
      ),
  })
  .describe(
    "Комментарий к статусу canceled: кто отменил возврат и по какой причине.",
  );
