/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Идентификатор возврата платежа в ЮKassa.
 */
export const refundIdSchema = z
  .string()
  .min(36)
  .max(36)
  .describe("Идентификатор возврата платежа в ЮKassa.");
