/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { accountIdSchema } from "./account-id-schema.ts";
import { monetaryAmountSchema } from "./monetary-amount-schema.ts";

/**
 * @description Данные о том, с какого магазина и какую сумму нужно удержать для проведения возврата. Сейчас в этом параметре можно передать данные только одного магазина.
 */
export const refundSourcesDataSchema = z
  .object({
    get account_id() {
      return accountIdSchema.describe("Идентификатор магазина в ЮKassa.");
    },
    get amount() {
      return monetaryAmountSchema.describe("Сумма в выбранной валюте.");
    },
    get platform_fee_amount() {
      return monetaryAmountSchema
        .describe("Сумма в выбранной валюте.")
        .optional();
    },
  })
  .describe(
    "Данные о том, с какого магазина и какую сумму нужно удержать для проведения возврата. Сейчас в этом параметре можно передать данные только одного магазина.",
  );
