/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { settlementRefundArraySchema } from "./settlement-refund-array-schema.ts";

/**
 * @description Данные о сделке, в составе которой проходит возврат. Необходимо передавать, если вы проводите Безопасную сделку: https://yookassa.ru/developers/solutions-for-platforms/safe-deal/basics.
 */
export const refundDealDataSchema = z
  .object({
    get refund_settlements() {
      return settlementRefundArraySchema.describe(
        "Данные о распределении денег.",
      );
    },
  })
  .describe(
    "Данные о сделке, в составе которой проходит возврат. Необходимо передавать, если вы проводите Безопасную сделку: https://yookassa.ru/developers/solutions-for-platforms/safe-deal/basics.",
  );
