/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { cardRequestDataWithCscSchema } from "./card-request-data-with-csc-schema.ts";
import { savePaymentMethodDataSchema } from "./save-payment-method-data-schema.ts";

/**
 * @description Данные для проверки и сохранения банковской карты.
 */
export const savePaymentMethodDataBankCardSchema = z
  .lazy(() => savePaymentMethodDataSchema)
  .and(
    z.object({
      type: z.literal("bank_card"),
    }),
  )
  .and(
    z.object({
      get card() {
        return cardRequestDataWithCscSchema.optional();
      },
      type: z.enum(["bank_card"]),
    }),
  )
  .describe("Данные для проверки и сохранения банковской карты.");
