/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { bankCardDataSchema } from "./bank-card-data-schema.ts";
import { savePaymentMethodSchema } from "./save-payment-method-schema.ts";

/**
 * @description Сохраненная банковская карта.
 */
export const savePaymentMethodBankCardSchema = z
  .lazy(() => savePaymentMethodSchema)
  .and(
    z.object({
      type: z.literal("bank_card"),
    }),
  )
  .and(
    z.object({
      get card() {
        return bankCardDataSchema
          .describe("Данные банковской карты.")
          .optional();
      },
      type: z.enum(["bank_card"]),
    }),
  )
  .describe("Сохраненная банковская карта.");
