/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Идентификатор операции в СБП (НСПК). Пример: 1027088AE4CB48CB81287833347A8777.
 */
export const sbpOperationIdSchema = z
  .string()
  .describe(
    "Идентификатор операции в СБП (НСПК). Пример: 1027088AE4CB48CB81287833347A8777.",
  );
