/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { sbpBankBicSchema } from "./sbp-bank-bic-schema.ts";
import { sbpBankIdSchema } from "./sbp-bank-id-schema.ts";

/**
 * @description Реквизиты счета, который использовался для оплаты. Обязательный параметр для платежей в статусе succeeded. В остальных случаях может отсутствовать.
 */
export const sbpPayerBankDetailsSchema = z
  .object({
    get bank_id() {
      return sbpBankIdSchema.describe(
        "Идентификатор банка или платежного сервиса в СБП (НСПК).",
      );
    },
    get bic() {
      return sbpBankBicSchema.and(z.any());
    },
  })
  .describe(
    "Реквизиты счета, который использовался для оплаты. Обязательный параметр для платежей в статусе succeeded. В остальных случаях может отсутствовать.",
  );
