/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { settlementPaymentItemSchema } from "./settlement-payment-item-schema.ts";

export const settlementPayoutPaymentSchema = z
  .lazy(() => settlementPaymentItemSchema)
  .and(
    z.object({
      type: z.literal("payout"),
    }),
  )
  .and(
    z.object({
      type: z.enum(["payout"]),
    }),
  );
