/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { settlementPaymentItemSchema } from "./settlement-payment-item-schema.ts";

/**
 * @description Данные о распределении денег.
 */
export const settlementPaymentArraySchema = z
  .array(z.lazy(() => settlementPaymentItemSchema))
  .describe("Данные о распределении денег.");
