/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { monetaryAmountSchema } from "./monetary-amount-schema.ts";
import { settlementItemTypeSchema } from "./settlement-item-type-schema.ts";

/**
 * @description Данные о распределении денег.
 */
export const settlementPaymentItemSchema = z
  .object({
    get type() {
      return settlementItemTypeSchema.describe("Transaction type.");
    },
    get amount() {
      return monetaryAmountSchema.describe("Сумма в выбранной валюте.");
    },
  })
  .describe("Данные о распределении денег.");
