/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Признак тестовой операции.
 */
export const testSchema = z.boolean().describe("Признак тестовой операции.");
