/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { errorSchema } from "./error-schema.ts";

/**
 * @description Слишком много запросов одновременно отправляется в API. Повторите запрос позже.
 */
export const tooManyRequestsSchema = z
  .lazy(() => errorSchema)
  .and(
    z.object({
      code: z.optional(z.enum(["too_many_requests"]).describe("Код ошибки.")),
    }),
  )
  .describe(
    "Слишком много запросов одновременно отправляется в API. Повторите запрос позже.",
  );
