/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Status of the money distribution between stores. Possible values: pending, waiting_for_capture, succeeded, canceled.
 */
export const transferStatusSchema = z
  .enum(["pending", "waiting_for_capture", "succeeded", "canceled"])
  .describe(
    "Status of the money distribution between stores. Possible values: pending, waiting_for_capture, succeeded, canceled.",
  );
