/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Типичный JSON при 404 и части других ошибок API.
 */
export const errorBodySchema = z
  .object({
    detail: z.string().describe("Текст сообщения об ошибке"),
  })
  .catchall(z.any())
  .describe("Типичный JSON при 404 и части других ошибок API.");
