/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { errorBodySchema } from "./error-body-schema.ts";
import { userProfileSchema } from "./user-profile-schema.ts";

export const getUserProfilePathParamsSchema = z.object({
  author_id: z
    .string()
    .regex(/^[0-9]+$/)
    .describe("Числовой id автора (как в URL канала на сайте)."),
});

/**
 * @description Успешный ответ
 */
export const getUserProfile200Schema = z.lazy(() => userProfileSchema);

/**
 * @description Ресурс не найден или ошибка клиента. Тело может быть JSON с `detail` или HTML-страница.
 */
export const getUserProfile404Schema = z
  .lazy(() => errorBodySchema)
  .describe("Типичный JSON при 404 и части других ошибок API.");

/**
 * @description Ошибка сервера. Тело может быть JSON с `detail` или HTML-страница.
 */
export const getUserProfile500Schema = z
  .lazy(() => errorBodySchema)
  .describe("Типичный JSON при 404 и части других ошибок API.");

export const getUserProfileQueryResponseSchema = z.lazy(
  () => getUserProfile200Schema,
);
