/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const pgRatingSchema = z
  .object({
    age: z.optional(z.int()),
    logo: z.optional(z.url()),
  })
  .catchall(z.any());
