/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const videoAuthorSchema = z
  .object({
    id: z.optional(z.int()),
    name: z.optional(z.string()),
    avatar_url: z.optional(z.url()),
    site_url: z.optional(z.url()),
    is_allowed_offline: z.optional(z.boolean()),
  })
  .catchall(z.any());
