/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { videoListItemSchema } from "./video-list-item-schema.ts";

export const videoListPageSchema = z
  .object({
    has_next: z.boolean(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    page: z.int(),
    per_page: z.int(),
    num_pages: z.int(),
    get results() {
      return z.array(
        videoListItemSchema.describe(
          "Элемент списка видео; набор полей может расширяться.",
        ),
      );
    },
  })
  .catchall(z.any());
