/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Типичный JSON при 404 и части других ошибок API.
 */
export type ErrorBody = {
  /**
   * @description Текст сообщения об ошибке
   * @type string
   */
  detail: string;
  [key: string]: unknown;
};
