/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorBody } from "./error-body.ts";
import type { UserProfile } from "./user-profile.ts";

export type GetUserProfilePathParams = {
  /**
   * @description Числовой id автора (как в URL канала на сайте).
   * @pattern ^[0-9]+$
   * @type string
   */
  author_id: string;
};

/**
 * @description Успешный ответ
 */
export type GetUserProfile200 = UserProfile;

/**
 * @description Ресурс не найден или ошибка клиента. Тело может быть JSON с `detail` или HTML-страница.
 */
export type GetUserProfile404 = ErrorBody;

/**
 * @description Ошибка сервера. Тело может быть JSON с `detail` или HTML-страница.
 */
export type GetUserProfile500 = ErrorBody;

export type GetUserProfileQueryResponse = GetUserProfile200;

export type GetUserProfileQuery = {
  Response: GetUserProfile200;
  PathParams: GetUserProfilePathParams;
  Errors: GetUserProfile404 | GetUserProfile500;
};
