/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PgRating = {
  /**
   * @type integer | undefined
   */
  age?: number;
  /**
   * @type string | undefined, uri
   */
  logo?: string;
  [key: string]: unknown;
};
