/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type VideoAuthor = {
  /**
   * @type integer | undefined
   */
  id?: number;
  /**
   * @type string | undefined
   */
  name?: string;
  /**
   * @type string | undefined, uri
   */
  avatar_url?: string;
  /**
   * @type string | undefined, uri
   */
  site_url?: string;
  /**
   * @type boolean | undefined
   */
  is_allowed_offline?: boolean;
  [key: string]: unknown;
};
