/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type VideoCategory = {
  /**
   * @type integer | undefined
   */
  id?: number;
  /**
   * @type string | undefined, uri
   */
  category_url?: string;
  /**
   * @type string | undefined
   */
  name?: string;
  [key: string]: unknown;
};
